create or replace table `shopify-pubsub-project.Data_Warehouse_GoogleAds_Staging.account_performance_report`
partition by date_trunc(_airbyte_extracted_at, day)
as
-- select count(distinct customer_time_zone) from shopify-pubsub-project.pilgrim_bi_google_ads.account_performance_report

select 
_airbyte_raw_id,
_airbyte_extracted_at,
_airbyte_meta,
_airbyte_generation_id,
rn,
customer_id,
segments_date,
metrics_ctr,
segments_ad_network_type,
segments_week,
segments_year,
metrics_clicks,
segments_month,
segments_device,
customer_manager,
segments_quarter,
customer_time_zone,
metrics_average_cpc,
metrics_average_cpe,
metrics_average_cpm,
metrics_average_cpv,
metrics_conversions,
metrics_cost_micros,
metrics_engagements,
metrics_impressions,
metrics_video_views,
metrics_average_cost,
metrics_interactions,
segments_day_of_week,
customer_test_account,
customer_currency_code,
metrics_active_view_cpm,
metrics_active_view_ctr,
metrics_all_conversions,
metrics_engagement_rate,
metrics_video_view_rate,
metrics_interaction_rate,
customer_descriptive_name,
metrics_conversions_value,
metrics_cost_per_conversion,
metrics_value_per_conversion,
customer_auto_tagging_enabled,
metrics_all_conversions_value,
metrics_active_view_impressions,
metrics_active_view_viewability,
metrics_interaction_event_types,
metrics_search_impression_share,
metrics_content_impression_share,
metrics_cost_per_all_conversions,
metrics_cross_device_conversions,
metrics_view_through_conversions,
metrics_active_view_measurability,
metrics_value_per_all_conversions,
metrics_search_rank_lost_impression_share,
metrics_active_view_measurable_cost_micros,
metrics_active_view_measurable_impressions,
metrics_content_rank_lost_impression_share,
metrics_conversions_from_interactions_rate,
metrics_search_budget_lost_impression_share,
metrics_search_exact_match_impression_share,
metrics_content_budget_lost_impression_share,
metrics_all_conversions_from_interactions_rate,


from
(
select
*,
row_number() over(partition by customer_id,segments_date,segments_device,segments_ad_network_type order by _airbyte_extracted_at) as rn
from shopify-pubsub-project.pilgrim_bi_google_ads.account_performance_report
)
where rn > 1
-- order by segments_date,segments_device,segments_ad_network_type
