MERGE INTO `shopify-pubsub-project.Data_Warehouse_Amazon_ads.display_report_stream` AS target
USING (
  SELECT 
    _airbyte_extracted_at,
    JSON_EXTRACT_SCALAR(metric, '$.adGroupId') AS adGroupId,
    JSON_EXTRACT_SCALAR(metric, '$.adGroupName') AS adGroupName,
    JSON_EXTRACT_SCALAR(metric, '$.adId') AS adId,
    JSON_EXTRACT_SCALAR(metric, '$.addToCart') AS addToCart,
    JSON_EXTRACT_SCALAR(metric, '$.addToCartClicks') AS addToCartClicks,
    JSON_EXTRACT_SCALAR(metric, '$.addToCartRate') AS addToCartRate,
    JSON_EXTRACT_SCALAR(metric, '$.addToCartViews') AS addToCartViews,
    JSON_EXTRACT_SCALAR(metric, '$.addToList') AS addToList,
    JSON_EXTRACT_SCALAR(metric, '$.addToListFromClicks') AS addToListFromClicks,
    JSON_EXTRACT_SCALAR(metric, '$.addToListFromViews') AS addToListFromViews,
    JSON_EXTRACT_SCALAR(metric, '$.bidOptimization') AS bidOptimization,
    JSON_EXTRACT_SCALAR(metric, '$.brandedSearchRate') AS brandedSearchRate,
    JSON_EXTRACT_SCALAR(metric, '$.brandedSearches') AS brandedSearches,
    JSON_EXTRACT_SCALAR(metric, '$.brandedSearchesClicks') AS brandedSearchesClicks,
    JSON_EXTRACT_SCALAR(metric, '$.brandedSearchesViews') AS brandedSearchesViews,
    JSON_EXTRACT_SCALAR(metric, '$.campaignBudgetCurrencyCode') AS campaignBudgetCurrencyCode,
    JSON_EXTRACT_SCALAR(metric, '$.campaignId') AS campaignId,
    JSON_EXTRACT_SCALAR(metric, '$.campaignName') AS campaignName,
    JSON_EXTRACT_SCALAR(metric, '$.clicks') AS clicks,
    JSON_EXTRACT_SCALAR(metric, '$.cost') AS cost,
    JSON_EXTRACT_SCALAR(metric, '$.cumulativeReach') AS cumulativeReach,
    JSON_EXTRACT_SCALAR(metric, '$.detailPageViews') AS detailPageViews,
    JSON_EXTRACT_SCALAR(metric, '$.detailPageViewsClicks') AS detailPageViewsClicks,
    JSON_EXTRACT_SCALAR(metric, '$.eCPAddToCart') AS eCPAddToCart,
    JSON_EXTRACT_SCALAR(metric, '$.eCPBrandSearch') AS eCPBrandSearch,
    JSON_EXTRACT_SCALAR(metric, '$.endDate') AS endDate,
    JSON_EXTRACT_SCALAR(metric, '$.impressions') AS impressions,
    JSON_EXTRACT_SCALAR(metric, '$.impressionsFrequencyAverage') AS impressionsFrequencyAverage,
    JSON_EXTRACT_SCALAR(metric, '$.impressionsViews') AS impressionsViews,
    JSON_EXTRACT_SCALAR(metric, '$.leadFormOpens') AS leadFormOpens,
    JSON_EXTRACT_SCALAR(metric, '$.leads') AS leads,
    JSON_EXTRACT_SCALAR(metric, '$.linkOuts') AS linkOuts,
    JSON_EXTRACT_SCALAR(metric, '$.newToBrandDetailPageViewClicks') AS newToBrandDetailPageViewClicks,
    JSON_EXTRACT_SCALAR(metric, '$.newToBrandDetailPageViewRate') AS newToBrandDetailPageViewRate,
    JSON_EXTRACT_SCALAR(metric, '$.newToBrandDetailPageViewViews') AS newToBrandDetailPageViewViews,
    JSON_EXTRACT_SCALAR(metric, '$.newToBrandDetailPageViews') AS newToBrandDetailPageViews,
    JSON_EXTRACT_SCALAR(metric, '$.newToBrandECPDetailPageView') AS newToBrandECPDetailPageView,
    JSON_EXTRACT_SCALAR(metric, '$.newToBrandPurchases') AS newToBrandPurchases,
    JSON_EXTRACT_SCALAR(metric, '$.newToBrandPurchasesClicks') AS newToBrandPurchasesClicks,
    JSON_EXTRACT_SCALAR(metric, '$.newToBrandSales') AS newToBrandSales,
    JSON_EXTRACT_SCALAR(metric, '$.newToBrandSalesClicks') AS newToBrandSalesClicks,
    JSON_EXTRACT_SCALAR(metric, '$.newToBrandUnitsSold') AS newToBrandUnitsSold,
    JSON_EXTRACT_SCALAR(metric, '$.newToBrandUnitsSoldClicks') AS newToBrandUnitsSoldClicks,
    JSON_EXTRACT_SCALAR(metric, '$.promotedAsin') AS promotedAsin,
    JSON_EXTRACT_SCALAR(metric, '$.promotedSku') AS promotedSku,
    JSON_EXTRACT_SCALAR(metric, '$.purchases') AS purchases,
    JSON_EXTRACT_SCALAR(metric, '$.purchasesClicks') AS purchasesClicks,
    JSON_EXTRACT_SCALAR(metric, '$.purchasesPromotedClicks') AS purchasesPromotedClicks,
    JSON_EXTRACT_SCALAR(metric, '$.qualifiedBorrows') AS qualifiedBorrows,
    JSON_EXTRACT_SCALAR(metric, '$.qualifiedBorrowsFromClicks') AS qualifiedBorrowsFromClicks,
    JSON_EXTRACT_SCALAR(metric, '$.qualifiedBorrowsFromViews') AS qualifiedBorrowsFromViews,
    JSON_EXTRACT_SCALAR(metric, '$.royaltyQualifiedBorrows') AS royaltyQualifiedBorrows,
    JSON_EXTRACT_SCALAR(metric, '$.royaltyQualifiedBorrowsFromClicks') AS royaltyQualifiedBorrowsFromClicks,
    JSON_EXTRACT_SCALAR(metric, '$.royaltyQualifiedBorrowsFromViews') AS royaltyQualifiedBorrowsFromViews,
    JSON_EXTRACT_SCALAR(metric, '$.sales') AS sales,
    JSON_EXTRACT_SCALAR(metric, '$.salesClicks') AS salesClicks,
    JSON_EXTRACT_SCALAR(metric, '$.salesPromotedClicks') AS salesPromotedClicks,
    JSON_EXTRACT_SCALAR(metric, '$.startDate') AS startDate,
    JSON_EXTRACT_SCALAR(metric, '$.unitsSold') AS unitsSold,
    JSON_EXTRACT_SCALAR(metric, '$.unitsSoldClicks') AS unitsSoldClicks,
    JSON_EXTRACT_SCALAR(metric, '$.videoCompleteViews') AS videoCompleteViews,
    JSON_EXTRACT_SCALAR(metric, '$.videoFirstQuartileViews') AS videoFirstQuartileViews,
    JSON_EXTRACT_SCALAR(metric, '$.videoMidpointViews') AS videoMidpointViews,
    JSON_EXTRACT_SCALAR(metric, '$.videoThirdQuartileViews') AS videoThirdQuartileViews,
    JSON_EXTRACT_SCALAR(metric, '$.videoUnmutes') AS videoUnmutes,
    JSON_EXTRACT_SCALAR(metric, '$.viewClickThroughRate') AS viewClickThroughRate,
    JSON_EXTRACT_SCALAR(metric, '$.viewabilityRate') AS viewabilityRate, 
    recordId,
    profileId,
    recordType,
    reportDate
  FROM 
    `shopify-pubsub-project.pilgrim_bi_airbyte_amazon_ads.sponsored_display_report_stream` 
    WHERE _airbyte_extracted_at > (
    SELECT MAX(_airbyte_extracted_at)
    FROM `shopify-pubsub-project.Data_Warehouse_Amazon_ads.display_product_ads`
  )
) AS source
ON FALSE
WHEN NOT MATCHED THEN
  INSERT (
    _airbyte_extracted_at,
    adGroupId,
    adGroupName,
    adId,
    addToCart,
    addToCartClicks,
    addToCartRate,
    addToCartViews,
    addToList,
    addToListFromClicks,
    addToListFromViews,
    bidOptimization,
    brandedSearchRate,
    brandedSearches,
    brandedSearchesClicks,
    brandedSearchesViews,
    campaignBudgetCurrencyCode,
    campaignId,
    campaignName,
    clicks,
    cost,
    cumulativeReach,
    detailPageViews,
    detailPageViewsClicks,
    eCPAddToCart,
    eCPBrandSearch,
    endDate,
    impressions,
    impressionsFrequencyAverage,
    impressionsViews,
    leadFormOpens,
    leads,
    linkOuts,
    newToBrandDetailPageViewClicks,
    newToBrandDetailPageViewRate,
    newToBrandDetailPageViewViews,
    newToBrandDetailPageViews,
    newToBrandECPDetailPageView,
    newToBrandPurchases,
    newToBrandPurchasesClicks,
    newToBrandSales,
    newToBrandSalesClicks,
    newToBrandUnitsSold,
    newToBrandUnitsSoldClicks,
    promotedAsin,
    promotedSku,
    purchases,
    purchasesClicks,
    purchasesPromotedClicks,
    qualifiedBorrows,
    qualifiedBorrowsFromClicks,
    qualifiedBorrowsFromViews,
    royaltyQualifiedBorrows,
    royaltyQualifiedBorrowsFromClicks,
    royaltyQualifiedBorrowsFromViews,
    sales,
    salesClicks,
    salesPromotedClicks,
    startDate,
    unitsSold,
    unitsSoldClicks,
    videoCompleteViews,
    videoFirstQuartileViews,
    videoMidpointViews,
    videoThirdQuartileViews,
    videoUnmutes,
    viewClickThroughRate,
    viewabilityRate,
    recordId,
    profileId,
    recordType,
    reportDate
  ) VALUES (
    source._airbyte_extracted_at,
    source.adGroupId,
    source.adGroupName,
    source.adId,
    source.addToCart,
    source.addToCartClicks,
    source.addToCartRate,
    source.addToCartViews,
    source.addToList,
    source.addToListFromClicks,
    source.addToListFromViews,
    source.bidOptimization,
    source.brandedSearchRate,
    source.brandedSearches,
    source.brandedSearchesClicks,
    source.brandedSearchesViews,
    source.campaignBudgetCurrencyCode,
    source.campaignId,
    source.campaignName,
    source.clicks,
    source.cost,
    source.cumulativeReach,
    source.detailPageViews,
    source.detailPageViewsClicks,
    source.eCPAddToCart,
    source.eCPBrandSearch,
    source.endDate,
    source.impressions,
    source.impressionsFrequencyAverage,
    source.impressionsViews,
    source.leadFormOpens,
    source.leads,
    source.linkOuts,
    source.newToBrandDetailPageViewClicks,
    source.newToBrandDetailPageViewRate,
    source.newToBrandDetailPageViewViews,
    source.newToBrandDetailPageViews,
    source.newToBrandECPDetailPageView,
    source.newToBrandPurchases,
    source.newToBrandPurchasesClicks,
    source.newToBrandSales,
    source.newToBrandSalesClicks,
    source.newToBrandUnitsSold,
    source.newToBrandUnitsSoldClicks,
    source.promotedAsin,
    source.promotedSku,
    source.purchases,
    source.purchasesClicks,
    source.purchasesPromotedClicks,
    source.qualifiedBorrows,
    source.qualifiedBorrowsFromClicks,
    source.qualifiedBorrowsFromViews,
    source.royaltyQualifiedBorrows,
    source.royaltyQualifiedBorrowsFromClicks,
    source.royaltyQualifiedBorrowsFromViews,
    source.sales,
    source.salesClicks,
    source.salesPromotedClicks,
    source.startDate,
    source.unitsSold,
    source.unitsSoldClicks,
    source.videoCompleteViews,
    source.videoFirstQuartileViews,
    source.videoMidpointViews,
    source.videoThirdQuartileViews,
    source.videoUnmutes,
    source.viewClickThroughRate,
    source.viewabilityRate,
    source.recordId,
    source.profileId,
    source.recordType,
    source.reportDate
  );
