
MERGE INTO `shopify-pubsub-project.Shopify_staging.Orders` AS target

USING (
  SELECT
  _airbyte_extracted_at,
   note as Order_note,
cancel_reason as Order_cancelled_reason,
cancelled_at as Order_cancelled_at,
landing_site as landing_weburl,
referring_site as referring_weburl,
cart_token as Order_cart_token,
browser_ip as browser_ip_id,
checkout_id as Order_checkout_id,
checkout_token as Order_checkout_token,
closed_at as Order_closed_at,
fulfillment_status as Order_fulfillment_status,
currency as Order_currency,
shop_url as Order_shop_url,
confirmed as Order_confirmed,
estimated_taxes as Order_estimated_taxes,
test as isTestOrder,
taxes_included as Order_taxes_included,
financial_status as Order_financial_status,
source_name as Order_source_name,
app_id as Order_app_id,
total_line_items_price as total_line_items_price,
total_tax as total_tax,
total_price as Order_total_price,
total_discounts as Order_total_discounts,
tags as Order_tags,
updated_at as Order_updated_at,
created_at as Order_created_at,
processed_at as Order_processed_at,
name as Order_name,
id as Order_id,
token as Order_token,
order_number as Order_order_number,

JSON_EXTRACT(refunds, '$[0].created_at') AS Refund_created_at,
JSON_EXTRACT(refunds, '$[0].id') AS Refund_id,
JSON_EXTRACT(refunds, '$[0].note') AS Refund_note,
JSON_EXTRACT(refunds, '$[0].order_id') AS Refund_Order_id,
JSON_EXTRACT(refunds, '$[0].processed_at') AS Refund_processed_at,
JSON_EXTRACT(refunds, '$[0].order_adjustments.amount') AS order_adjustments_amount,
JSON_EXTRACT(refunds, '$[0].order_adjustments.id') AS order_adjustments_id,
JSON_EXTRACT(refunds, '$[0].order_adjustments.kind') AS order_adjustments_kind,
JSON_EXTRACT(refunds, '$[0].order_adjustments.reason') AS order_adjustments_reason,

JSON_EXTRACT(customer, '$.id') AS customer_id,

JSON_EXTRACT(tax_lines, '$[0].channel_liable') AS tax_channel_liable,
JSON_EXTRACT(tax_lines, '$[0].price') AS tax_price,
JSON_EXTRACT(tax_lines, '$[0].rate') AS tax_rate,
JSON_EXTRACT(tax_lines, '$[0].title') AS tax_title,

JSON_EXTRACT(client_details, '$.accept_language') AS browser_language,
JSON_EXTRACT(client_details, '$.browser_height') AS browser_height,
JSON_EXTRACT(client_details, '$.browser_ip') AS browser_ip,
JSON_EXTRACT(client_details, '$.browser_width') AS browser_width,
JSON_EXTRACT(client_details, '$.session_hash') AS session_hash,
JSON_EXTRACT(client_details, '$.user_agent') AS browser_agent,

JSON_EXTRACT(discount_codes, '$[0].amount') AS discount_amount,
JSON_EXTRACT(discount_codes, '$[0].code') AS discount_code,
JSON_EXTRACT(discount_codes, '$[0].type') AS discount_type,

JSON_EXTRACT(billing_address, '$.address1') AS billing_address,
JSON_EXTRACT(billing_address, '$.city') AS billing_city,
JSON_EXTRACT(billing_address, '$.country') AS billing_country,
JSON_EXTRACT(billing_address, '$.country_code') AS billing_country_code,
JSON_EXTRACT(billing_address, '$.province') AS billing_province,
JSON_EXTRACT(billing_address, '$.province_code') AS billing_province_code,
JSON_EXTRACT(billing_address, '$.zip') AS billing_zip,

JSON_EXTRACT(shipping_address, '$.address1') AS shipping_address,
JSON_EXTRACT(shipping_address, '$.city') AS shipping_city,
JSON_EXTRACT(shipping_address, '$.country') AS shipping_country,
JSON_EXTRACT(shipping_address, '$.country_code') AS shipping_country_code,
JSON_EXTRACT(shipping_address, '$.province') AS shipping_province,
JSON_EXTRACT(shipping_address, '$.province_code') AS shipping_province_code,
JSON_EXTRACT(shipping_address, '$.zip') AS shipping_zip,

JSON_EXTRACT(payment_gateway_names, '$') AS payment_gateway_names,

  FROM `shopify-pubsub-project.airbyte711.orders`
  WHERE date(_airbyte_extracted_at) >= DATE_SUB(CURRENT_DATE("Asia/Kolkata"), INTERVAL 1 DAY)
 
 ) AS source
ON target.Order_name = source.Order_name
WHEN MATCHED AND source._airbyte_extracted_at > target._airbyte_extracted_at THEN UPDATE SET
 
target._airbyte_extracted_at = source._airbyte_extracted_at,
target.Order_note = source.Order_note,
target.Order_cancelled_reason = source.Order_cancelled_reason,
target.Order_cancelled_at = source.Order_cancelled_at,
target.landing_weburl = source.landing_weburl,
target.referring_weburl = source.referring_weburl,
target.Order_cart_token = source.Order_cart_token,
target.browser_ip_id = source.browser_ip_id,
target.Order_checkout_id = source.Order_checkout_id,
target.Order_checkout_token = source.Order_checkout_token,
target.Order_closed_at = source.Order_closed_at,
target.Order_fulfillment_status = source.Order_fulfillment_status,
target.Order_currency = source.Order_currency,
target.Order_shop_url = source.Order_shop_url,
target.Order_confirmed = source.Order_confirmed,
target.Order_estimated_taxes = source.Order_estimated_taxes,
target.isTestOrder = source.isTestOrder,
target.Order_taxes_included = source.Order_taxes_included,
target.Order_financial_status = source.Order_financial_status,
target.Order_source_name = source.Order_source_name,
target.Order_app_id = source.Order_app_id,
target.total_line_items_price = source.total_line_items_price,
target.total_tax = source.total_tax,
target.Order_total_price = source.Order_total_price,
target.Order_total_discounts = source.Order_total_discounts,
target.Order_tags = source.Order_tags,
target.Order_updated_at = source.Order_updated_at,
target.Order_created_at = source.Order_created_at,
target.Order_processed_at = source.Order_processed_at,
target.Order_name = source.Order_name,
target.Order_id = source.Order_id,
target.Order_token = source.Order_token,
target.Order_order_number = source.Order_order_number,
target.Refund_created_at = source.Refund_created_at,
target.Refund_id = source.Refund_id,
target.Refund_note = source.Refund_note,
target.Refund_Order_id = source.Refund_Order_id,
target.Refund_processed_at = source.Refund_processed_at,
target.order_adjustments_amount = source.order_adjustments_amount,
target.order_adjustments_id = source.order_adjustments_id,
target.order_adjustments_kind = source.order_adjustments_kind,
target.order_adjustments_reason = source.order_adjustments_reason,
target.customer_id = source.customer_id,
target.tax_channel_liable = source.tax_channel_liable,
target.tax_price = source.tax_price,
target.tax_rate = source.tax_rate,
target.tax_title = source.tax_title,
target.browser_language = source.browser_language,
target.browser_height = source.browser_height,
target.browser_ip = source.browser_ip,
target.browser_width = source.browser_width,
target.session_hash = source.session_hash,
target.browser_agent = source.browser_agent,
target.discount_amount = source.discount_amount,
target.discount_code = source.discount_code,
target.discount_type = source.discount_type,
target.billing_address = source.billing_address,
target.billing_city = source.billing_city,
target.billing_country = source.billing_country,
target.billing_country_code = source.billing_country_code,
target.billing_province = source.billing_province,
target.billing_province_code = source.billing_province_code,
target.billing_zip = source.billing_zip,
target.shipping_address = source.shipping_address,
target.shipping_city = source.shipping_city,
target.shipping_country = source.shipping_country,
target.shipping_country_code = source.shipping_country_code,
target.shipping_province = source.shipping_province,
target.shipping_province_code = source.shipping_province_code,
target.shipping_zip = source.shipping_zip,
target.payment_gateway_names = source.payment_gateway_names

WHEN NOT MATCHED THEN INSERT (
 _airbyte_extracted_at,
Order_note,
Order_cancelled_reason,
Order_cancelled_at,
landing_weburl,
referring_weburl,
Order_cart_token,
browser_ip_id,
Order_checkout_id,
Order_checkout_token,
Order_closed_at,
Order_fulfillment_status,
Order_currency,
Order_shop_url,
Order_confirmed,
Order_estimated_taxes,
isTestOrder,
Order_taxes_included,
Order_financial_status,
Order_source_name,
Order_app_id,
total_line_items_price,
total_tax,
Order_total_price,
Order_total_discounts,
Order_tags,
Order_updated_at,
Order_created_at,
Order_processed_at,
Order_name,
Order_id,
Order_token,
Order_order_number,
Refund_created_at,
Refund_id,
Refund_note,
Refund_Order_id,
Refund_processed_at,
order_adjustments_amount,
order_adjustments_id,
order_adjustments_kind,
order_adjustments_reason,
customer_id,
tax_channel_liable,
tax_price,
tax_rate,
tax_title,
browser_language,
browser_height,
browser_ip,
browser_width,
session_hash,
browser_agent,
discount_amount,
discount_code,
discount_type,
billing_address,
billing_city,
billing_country,
billing_country_code,
billing_province,
billing_province_code,
billing_zip,
shipping_address,
shipping_city,
shipping_country,
shipping_country_code,
shipping_province,
shipping_province_code,
shipping_zip,
payment_gateway_names
)
  VALUES (
source._airbyte_extracted_at,
source.Order_note,
source.Order_cancelled_reason,
source.Order_cancelled_at,
source.landing_weburl,
source.referring_weburl,
source.Order_cart_token,
source.browser_ip_id,
source.Order_checkout_id,
source.Order_checkout_token,
source.Order_closed_at,
source.Order_fulfillment_status,
source.Order_currency,
source.Order_shop_url,
source.Order_confirmed,
source.Order_estimated_taxes,
source.isTestOrder,
source.Order_taxes_included,
source.Order_financial_status,
source.Order_source_name,
source.Order_app_id,
source.total_line_items_price,
source.total_tax,
source.Order_total_price,
source.Order_total_discounts,
source.Order_tags,
source.Order_updated_at,
source.Order_created_at,
source.Order_processed_at,
source.Order_name,
source.Order_id,
source.Order_token,
source.Order_order_number,
source.Refund_created_at,
source.Refund_id,
source.Refund_note,
source.Refund_Order_id,
source.Refund_processed_at,
source.order_adjustments_amount,
source.order_adjustments_id,
source.order_adjustments_kind,
source.order_adjustments_reason,
source.customer_id,
source.tax_channel_liable,
source.tax_price,
source.tax_rate,
source.tax_title,
source.browser_language,
source.browser_height,
source.browser_ip,
source.browser_width,
source.session_hash,
source.browser_agent,
source.discount_amount,
source.discount_code,
source.discount_type,
source.billing_address,
source.billing_city,
source.billing_country,
source.billing_country_code,
source.billing_province,
source.billing_province_code,
source.billing_zip,
source.shipping_address,
source.shipping_city,
source.shipping_country,
source.shipping_country_code,
source.shipping_province,
source.shipping_province_code,
source.shipping_zip,
payment_gateway_names
  )
