# logsBucket: 'gs://pilgrim-bi-logs/cloud_build_logs/'
options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Copy DAGs to Composer bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    env:
      - 'COMPOSER_NAME=composer-pilgrim-bi-staging'
      - 'COMPOSER_LOCATION=asia-south2'
    script: |
      #!/bin/bash
      echo "gcloud composer environments update $COMPOSER_NAME  --location $COMPOSER_LOCATION --update-pypi-packages-from-file requirements.txt;" && \
      echo 'y' | gcloud composer environments update $COMPOSER_NAME  --location $COMPOSER_LOCATION --update-pypi-packages-from-file requirements.txt || \
      gsutil cp -r dags/* gs://asia-south2-composer-pilgri-b5eb683d-bucket/dags/;
