# logsBucket: 'gs://pilgrim-bi-logs/cloud_build_logs/'
options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Copy DAGs to Composer bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'dags/*', 'gs://asia-south2-composer-pilgri-b5eb683d-bucket/dags-cb-test/']
