services:
  airflow:
    build: .
    container_name: airflow
    environment:
      AIRFLOW__WEBSERVER__RBAC: False
    ports: 
      - 8080:8080
    env_file:
      - local.env
    volumes:
      - ./.dev/airflow/logs:/logs
      - ./.dev/airflow/db:/db
      - ./.dev/.bash_history:/root/.bash_history
      - ./.dev/.python_history:/root/.python_history
      - ./dags:/dags
      - 'd:/Customer_Support/Project Goonj/Flipkart_Scraping:/Goonj'
      # - empty:/dags/.dev
volumes:
  empty:
  