

CREATE or replace TABLE `shopify-pubsub-project.Data_Warehouse_Easyecom_Staging.Tax_report`
PARTITION BY DATE_TRUNC(Order_Date,day)
CLUSTER BY Order_Status
OPTIONS(
 description = "Tax Report table is partitioned on order date at day level",
 require_partition_filter = False
 )
 AS
select
  Company_Name,
  Seller_GST_Num,
  MP_Name,
  Reference_Code,
  Suborder_No,
  Order_Type,
  EE_Invoice_No,
  MP_Ref_No,
  Order_Status,
  Invoice_Status,
  Credit_Note_ID,
  CR_Voucher_Num,
  SAFE_CAST(Return_Date AS DATETIME) AS Return_Date,
  SAFE_CAST(Import_Date AS DATETIME) AS Import_Date,
  SAFE_CAST(Order_Date AS DATETIME) AS Order_Date,
  SAFE_CAST(Invoice_Date AS DATETIME) AS Invoice_Date,
  Parent_Courier_Partner,
  Courier,
  AWB_No,
  Component_SKU,
  Product_Config,
  Parent_SKU,
  SAFE_CAST(Parent_Quantity AS FLOAT64) AS Parent_Quantity,
  SAFE_CAST(Item_Quantity AS FLOAT64) AS Item_Quantity,
  SAFE_CAST(Parent_SKU_Weight AS FLOAT64) AS Parent_SKU_Weight,
  SAFE_CAST(Component_SKU_Weight AS FLOAT64) AS Component_SKU_Weight,
  Component_SKU_Description,
  Component_SKU_Name,
  Component_SKU_HSN,
  Component_SKU_Category,
  Component_SKU_Brand,
  SAFE_CAST(Component_SKU_Cost AS FLOAT64) AS Component_SKU_Cost,
  SAFE_CAST(Component_SKU_MRP AS FLOAT64) AS Component_SKU_MRP,
  Payment_Mode,
  Buyer_GST_Num,
  Customer_Name,
  Mobile_No,
  Address_Line_1,
  Address_Line_2,
  Customer_Email,
  City,
  Zip_Code,
  State,
  Tax_Type,
  SAFE_CAST(Tax_Rate AS FLOAT64) AS Tax_Rate,
  SAFE_CAST(Sr_No AS FLOAT64) AS Sr_No,
  SAFE_CAST(Collectible_Amount AS FLOAT64) AS Collectible_Amount,
  SAFE_CAST(Order_Invoice_Amount AS FLOAT64) AS Order_Invoice_Amount,
  SAFE_CAST(TCS_Rate AS FLOAT64) AS TCS_Rate,
  SAFE_CAST(TCS AS FLOAT64) AS TCS,
  SAFE_CAST(Selling_Price AS FLOAT64) AS Selling_Price,
  SAFE_CAST(Wallet_Discount AS FLOAT64) AS Wallet_Discount,
  SAFE_CAST(Item_Price_Excluding_Tax_ AS FLOAT64) AS Item_Price_Excluding_Tax_,
  SAFE_CAST(COD_Excluding_Tax_ AS FLOAT64) AS COD_Excluding_Tax_,
  SAFE_CAST(Shipping_Charge_Excluding_Tax_ AS FLOAT64) AS Shipping_Charge_Excluding_Tax_,
  SAFE_CAST(Shipping_Discount_Excluding_Tax_ AS FLOAT64) AS Shipping_Discount_Excluding_Tax_,
  SAFE_CAST(Promotion_Discount_Excluding_Tax_ AS FLOAT64) AS Promotion_Discount_Excluding_Tax_,
  SAFE_CAST(Miscellaneous_Excluding_Tax_ AS FLOAT64) AS Miscellaneous_Excluding_Tax_,
  SAFE_CAST(Gift_Wrap_Charges_Excluding_Tax_ AS FLOAT64) AS Gift_Wrap_Charges_Excluding_Tax_,
  SAFE_CAST(Prepaid_Discount_Excluding_Tax_ AS FLOAT64) AS Prepaid_Discount_Excluding_Tax_,
  SAFE_CAST(Promocode_Discount_Excluding_Tax_ AS FLOAT64) AS Promocode_Discount_Excluding_Tax_,
  SAFE_CAST(Taxable_Value AS FLOAT64) AS Taxable_Value,
  SAFE_CAST(Tax AS FLOAT64) AS Tax,
  SAFE_CAST(IGST AS FLOAT64) AS IGST,
  SAFE_CAST(CGST AS FLOAT64) AS CGST,
  SAFE_CAST(SGST AS FLOAT64) AS SGST,
  SAFE_CAST(CESS AS FLOAT64) AS CESS,
  SAFE_CAST(UTGST AS FLOAT64) AS UTGST,
  SAFE_CAST(TDS AS FLOAT64) AS TDS,
  IRN_Number,
  Acknowledgement_Num,
  SAFE_CAST(Acknowledgement_Date AS DATETIME) AS Acknowledgement_Date,
  Eway_Bill_Number,
  SAFE_CAST(Eway_Bill_Date AS DATETIME) AS Eway_Bill_Date, 
  CRN_Number,
  CreditNote_Acknowledgement_Num,
  SAFE_CAST(CreditNote_Acknowledgement_Date AS DATETIME) AS CreditNote_Acknowledgement_Date,
  Debit_Note_Number,
  Sales_Channel,
  SAFE_CAST(Manifest_Date AS DATETIME) AS Manifest_Date,
  ERP_Customer_ID,
  EE_Client_ID,
  Invoice_ERP_Transaction_ID,
  Billing_Customer_Name,
  Billing_Mobile_No,
  Billing_Customer_Email,
  Billing_Address_Line_1,
  Billing_Address_Line_2,
  Billing_City,
  Billing_Zip_Code,
  Billing_State,
  Billing_Country,
  A_c_SKu,
  External_Order_Code,
  SAFE_CAST(A_c_Unit AS FLOAT64) AS A_c_Unit,
  SAFE_CAST(GRN_Cost_per_unit AS FLOAT64) AS GRN_Cost_per_unit,
  SAFE_CAST(Additional_cost_per_unit AS FLOAT64) AS Additional_cost_per_unit,
  SAFE_CAST(Cost_of_Goods_Purchased AS FLOAT64) AS Cost_of_Goods_Purchased,
  SAFE_CAST(Delivery_Appointment_Date AS DATETIME) AS Delivery_Appointment_Date,
  report_id,
  report_type,
  start_date,
  end_date,
  created_on,
  inventory_type,
  -- ee_extracted_at

  FROM `shopify-pubsub-project.easycom.tax_reports`
