MERGE INTO `shopify-pubsub-project.Data_Warehouse_Easyecom_Staging.Tax_report` AS TARGET
USING
(
select
  Company_Name,
  Seller_GST_Num,
  MP_Name,
  Reference_Code,
  Suborder_No,
  Order_Type,
  EE_Invoice_No,
  MP_Ref_No,
  Order_Status,
  Invoice_Status,
  Credit_Note_ID,
  CR_Voucher_Num,
  SAFE_CAST(Return_Date AS DATETIME) AS Return_Date,
  SAFE_CAST(Import_Date AS DATETIME) AS Import_Date,
  SAFE_CAST(Order_Date AS DATETIME) AS Order_Date,
  SAFE_CAST(Invoice_Date AS DATETIME) AS Invoice_Date,
  Parent_Courier_Partner,
  Courier,
  AWB_No,
  Component_SKU,
  Product_Config,
  Parent_SKU,
  SAFE_CAST(Parent_Quantity AS FLOAT64) AS Parent_Quantity,
  SAFE_CAST(Item_Quantity AS FLOAT64) AS Item_Quantity,
  SAFE_CAST(Parent_SKU_Weight AS FLOAT64) AS Parent_SKU_Weight,
  SAFE_CAST(Component_SKU_Weight AS FLOAT64) AS Component_SKU_Weight,
  Component_SKU_Description,
  Component_SKU_Name,
  Component_SKU_HSN,
  Component_SKU_Category,
  Component_SKU_Brand,
  SAFE_CAST(Component_SKU_Cost AS FLOAT64) AS Component_SKU_Cost,
  SAFE_CAST(Component_SKU_MRP AS FLOAT64) AS Component_SKU_MRP,
  Payment_Mode,
  Buyer_GST_Num,
  Customer_Name,
  Mobile_No,
  Address_Line_1,
  Address_Line_2,
  Customer_Email,
  City,
  Zip_Code,
  State,
  Tax_Type,
  SAFE_CAST(Tax_Rate AS FLOAT64) AS Tax_Rate,
  SAFE_CAST(Sr_No AS FLOAT64) AS Sr_No,
  SAFE_CAST(Collectible_Amount AS FLOAT64) AS Collectible_Amount,
  SAFE_CAST(Order_Invoice_Amount AS FLOAT64) AS Order_Invoice_Amount,
  SAFE_CAST(TCS_Rate AS FLOAT64) AS TCS_Rate,
  SAFE_CAST(TCS AS FLOAT64) AS TCS,
  SAFE_CAST(Selling_Price AS FLOAT64) AS Selling_Price,
  SAFE_CAST(Wallet_Discount AS FLOAT64) AS Wallet_Discount,
  SAFE_CAST(Item_Price_Excluding_Tax_ AS FLOAT64) AS Item_Price_Excluding_Tax_,
  SAFE_CAST(COD_Excluding_Tax_ AS FLOAT64) AS COD_Excluding_Tax_,
  SAFE_CAST(Shipping_Charge_Excluding_Tax_ AS FLOAT64) AS Shipping_Charge_Excluding_Tax_,
  SAFE_CAST(Shipping_Discount_Excluding_Tax_ AS FLOAT64) AS Shipping_Discount_Excluding_Tax_,
  SAFE_CAST(Promotion_Discount_Excluding_Tax_ AS FLOAT64) AS Promotion_Discount_Excluding_Tax_,
  SAFE_CAST(Miscellaneous_Excluding_Tax_ AS FLOAT64) AS Miscellaneous_Excluding_Tax_,
  SAFE_CAST(Gift_Wrap_Charges_Excluding_Tax_ AS FLOAT64) AS Gift_Wrap_Charges_Excluding_Tax_,
  SAFE_CAST(Prepaid_Discount_Excluding_Tax_ AS FLOAT64) AS Prepaid_Discount_Excluding_Tax_,
  SAFE_CAST(Promocode_Discount_Excluding_Tax_ AS FLOAT64) AS Promocode_Discount_Excluding_Tax_,
  SAFE_CAST(Taxable_Value AS FLOAT64) AS Taxable_Value,
  SAFE_CAST(Tax AS FLOAT64) AS Tax,
  SAFE_CAST(IGST AS FLOAT64) AS IGST,
  SAFE_CAST(CGST AS FLOAT64) AS CGST,
  SAFE_CAST(SGST AS FLOAT64) AS SGST,
  SAFE_CAST(CESS AS FLOAT64) AS CESS,
  SAFE_CAST(UTGST AS FLOAT64) AS UTGST,
  SAFE_CAST(TDS AS FLOAT64) AS TDS,
  IRN_Number,
  Acknowledgement_Num,
  SAFE_CAST(Acknowledgement_Date AS DATETIME) AS Acknowledgement_Date,
  Eway_Bill_Number,
  SAFE_CAST(Eway_Bill_Date AS DATETIME) AS Eway_Bill_Date, 
  CRN_Number,
  CreditNote_Acknowledgement_Num,
  SAFE_CAST(CreditNote_Acknowledgement_Date AS DATETIME) AS CreditNote_Acknowledgement_Date,
  Debit_Note_Number,
  Sales_Channel,
  SAFE_CAST(Manifest_Date AS DATETIME) AS Manifest_Date,
  ERP_Customer_ID,
  EE_Client_ID,
  Invoice_ERP_Transaction_ID,
  Billing_Customer_Name,
  Billing_Mobile_No,
  Billing_Customer_Email,
  Billing_Address_Line_1,
  Billing_Address_Line_2,
  Billing_City,
  Billing_Zip_Code,
  Billing_State,
  Billing_Country,
  A_c_SKu,
  External_Order_Code,
  SAFE_CAST(A_c_Unit AS FLOAT64) AS A_c_Unit,
  SAFE_CAST(GRN_Cost_per_unit AS FLOAT64) AS GRN_Cost_per_unit,
  SAFE_CAST(Additional_cost_per_unit AS FLOAT64) AS Additional_cost_per_unit,
  SAFE_CAST(Cost_of_Goods_Purchased AS FLOAT64) AS Cost_of_Goods_Purchased,
  SAFE_CAST(Delivery_Appointment_Date AS DATETIME) AS Delivery_Appointment_Date,
  report_id,
  report_type,
  start_date,
  end_date,
  created_on,
  inventory_type,
  -- ee_extracted_at,
FROM
(
SELECT
*,
ROW_NUMBER() OVER(PARTITTION BY  ORDER BY ) AS row_num
FROM `shopify-pubsub-project.easycom.tax_reports`
WHERE DATE(_airbyte_extracted_at) >= DATE_SUB(CURRENT_DATE("Asia/Kolkata"), INTERVAL 10 DAY)
)
WHERE row_num = 1
) AS SOURCE
ON TARGET. = SOURCE.
WHEN MATCHED AND TARGET. > SOURCE.
THEN UPDATE SET
TARGET.Company_Name = SOURCE.Company_Name,
TARGET.Seller_GST_Num = SOURCE.Seller_GST_Num,
TARGET.MP_Name = SOURCE.MP_Name,
TARGET.Reference_Code = SOURCE.Reference_Code,
TARGET.Suborder_No = SOURCE.Suborder_No,
TARGET.Order_Type = SOURCE.Order_Type,
TARGET.EE_Invoice_No = SOURCE.EE_Invoice_No,
TARGET.MP_Ref_No = SOURCE.MP_Ref_No,
TARGET.Order_Status = SOURCE.Order_Status,
TARGET.Invoice_Status = SOURCE.Invoice_Status,
TARGET.Credit_Note_ID = SOURCE.Credit_Note_ID,
TARGET.CR_Voucher_Num = SOURCE.CR_Voucher_Num,
TARGET.Return_Date = SOURCE.Return_Date,
TARGET.Import_Date = SOURCE.Import_Date,
TARGET.Order_Date = SOURCE.Order_Date,
TARGET.Invoice_Date = SOURCE.Invoice_Date,
TARGET.Parent_Courier_Partner = SOURCE.Parent_Courier_Partner,
TARGET.Courier = SOURCE.Courier,
TARGET.AWB_No = SOURCE.AWB_No,
TARGET.Component_SKU = SOURCE.Component_SKU,
TARGET.Product_Config = SOURCE.Product_Config,
TARGET.Parent_SKU = SOURCE.Parent_SKU,
TARGET.Parent_Quantity = SOURCE.Parent_Quantity,
TARGET.Item_Quantity = SOURCE.Item_Quantity,
TARGET.Parent_SKU_Weight = SOURCE.Parent_SKU_Weight,
TARGET.Component_SKU_Weight = SOURCE.Component_SKU_Weight,
TARGET.Component_SKU_Description = SOURCE.Component_SKU_Description,
TARGET.Component_SKU_Name = SOURCE.Component_SKU_Name,
TARGET.Component_SKU_HSN = SOURCE.Component_SKU_HSN,
TARGET.Component_SKU_Category = SOURCE.Component_SKU_Category,
TARGET.Component_SKU_Brand = SOURCE.Component_SKU_Brand,
TARGET.Component_SKU_Cost = SOURCE.Component_SKU_Cost,
TARGET.Component_SKU_MRP = SOURCE.Component_SKU_MRP,
TARGET.Payment_Mode = SOURCE.Payment_Mode,
TARGET.Buyer_GST_Num = SOURCE.Buyer_GST_Num,
TARGET.Customer_Name = SOURCE.Customer_Name,
TARGET.Mobile_No = SOURCE.Mobile_No,
TARGET.Address_Line_1 = SOURCE.Address_Line_1,
TARGET.Address_Line_2 = SOURCE.Address_Line_2,
TARGET.Customer_Email = SOURCE.Customer_Email,
TARGET.City = SOURCE.City,
TARGET.Zip_Code = SOURCE.Zip_Code,
TARGET.State = SOURCE.State,
TARGET.Tax_Type = SOURCE.Tax_Type,
TARGET.Tax_Rate = SOURCE.Tax_Rate,
TARGET.Sr_No = SOURCE.Sr_No,
TARGET.Collectible_Amount = SOURCE.Collectible_Amount,
TARGET.Order_Invoice_Amount = SOURCE.Order_Invoice_Amount,
TARGET.TCS_Rate = SOURCE.TCS_Rate,
TARGET.TCS = SOURCE.TCS,
TARGET.Selling_Price = SOURCE.Selling_Price,
TARGET.Wallet_Discount = SOURCE.Wallet_Discount,
TARGET.Item_Price_Excluding_Tax_ = SOURCE.Item_Price_Excluding_Tax_,
TARGET.COD_Excluding_Tax_ = SOURCE.COD_Excluding_Tax_,
TARGET.Shipping_Charge_Excluding_Tax_ = SOURCE.Shipping_Charge_Excluding_Tax_,
TARGET.Shipping_Discount_Excluding_Tax_ = SOURCE.Shipping_Discount_Excluding_Tax_,
TARGET.Promotion_Discount_Excluding_Tax_ = SOURCE.Promotion_Discount_Excluding_Tax_,
TARGET.Miscellaneous_Excluding_Tax_ = SOURCE.Miscellaneous_Excluding_Tax_,
TARGET.Gift_Wrap_Charges_Excluding_Tax_ = SOURCE.Gift_Wrap_Charges_Excluding_Tax_,
TARGET.Prepaid_Discount_Excluding_Tax_ = SOURCE.Prepaid_Discount_Excluding_Tax_,
TARGET.Promocode_Discount_Excluding_Tax_ = SOURCE.Promocode_Discount_Excluding_Tax_,
TARGET.Taxable_Value = SOURCE.Taxable_Value,
TARGET.Tax = SOURCE.Tax,
TARGET.IGST = SOURCE.IGST,
TARGET.CGST = SOURCE.CGST,
TARGET.SGST = SOURCE.SGST,
TARGET.CESS = SOURCE.CESS,
TARGET.UTGST = SOURCE.UTGST,
TARGET.TDS = SOURCE.TDS,
TARGET.IRN_Number = SOURCE.IRN_Number,
TARGET.Acknowledgement_Num = SOURCE.Acknowledgement_Num,
TARGET.Acknowledgement_Date = SOURCE.Acknowledgement_Date,
TARGET.Eway_Bill_Number = SOURCE.Eway_Bill_Number,
TARGET.Eway_Bill_Date = SOURCE.Eway_Bill_Date,
TARGET.CRN_Number = SOURCE.CRN_Number,
TARGET.CreditNote_Acknowledgement_Num = SOURCE.CreditNote_Acknowledgement_Num,
TARGET.CreditNote_Acknowledgement_Date = SOURCE.CreditNote_Acknowledgement_Date,
TARGET.Debit_Note_Number = SOURCE.Debit_Note_Number,
TARGET.Sales_Channel = SOURCE.Sales_Channel,
TARGET.Manifest_Date = SOURCE.Manifest_Date,
TARGET.ERP_Customer_ID = SOURCE.ERP_Customer_ID,
TARGET.EE_Client_ID = SOURCE.EE_Client_ID,
TARGET.Invoice_ERP_Transaction_ID = SOURCE.Invoice_ERP_Transaction_ID,
TARGET.Billing_Customer_Name = SOURCE.Billing_Customer_Name,
TARGET.Billing_Mobile_No = SOURCE.Billing_Mobile_No,
TARGET.Billing_Customer_Email = SOURCE.Billing_Customer_Email,
TARGET.Billing_Address_Line_1 = SOURCE.Billing_Address_Line_1,
TARGET.Billing_Address_Line_2 = SOURCE.Billing_Address_Line_2,
TARGET.Billing_City = SOURCE.Billing_City,
TARGET.Billing_Zip_Code = SOURCE.Billing_Zip_Code,
TARGET.Billing_State = SOURCE.Billing_State,
TARGET.Billing_Country = SOURCE.Billing_Country,
TARGET.A_c_SKu = SOURCE.A_c_SKu,
TARGET.External_Order_Code = SOURCE.External_Order_Code,
TARGET.A_c_Unit = SOURCE.A_c_Unit,
TARGET.GRN_Cost_per_unit = SOURCE.GRN_Cost_per_unit,
TARGET.Additional_cost_per_unit = SOURCE.Additional_cost_per_unit,
TARGET.Cost_of_Goods_Purchased = SOURCE.Cost_of_Goods_Purchased,
TARGET.Delivery_Appointment_Date = SOURCE.Delivery_Appointment_Date,
TARGET.report_id = SOURCE.report_id,
TARGET.report_type = SOURCE.report_type,
TARGET.start_date = SOURCE.start_date,
TARGET.end_date = SOURCE.end_date,
TARGET.created_on = SOURCE.created_on,
TARGET.inventory_type = SOURCE.inventory_type,
TARGET.-- ee_extracted_at = SOURCE.-- ee_extracted_at,
WHEN NOT MATCHED
THEN INSERT
(
  Company_Name,
  Seller_GST_Num,
  MP_Name,
  Reference_Code,
  Suborder_No,
  Order_Type,
  EE_Invoice_No,
  MP_Ref_No,
  Order_Status,
  Invoice_Status,
  Credit_Note_ID,
  CR_Voucher_Num,
  Return_Date,
  Import_Date,
  Order_Date,
  Invoice_Date,
  Parent_Courier_Partner,
  Courier,
  AWB_No,
  Component_SKU,
  Product_Config,
  Parent_SKU,
  Parent_Quantity,
  Item_Quantity,
  Parent_SKU_Weight,
  Component_SKU_Weight,
  Component_SKU_Description,
  Component_SKU_Name,
  Component_SKU_HSN,
  Component_SKU_Category,
  Component_SKU_Brand,
  Component_SKU_Cost,
  Component_SKU_MRP,
  Payment_Mode,
  Buyer_GST_Num,
  Customer_Name,
  Mobile_No,
  Address_Line_1,
  Address_Line_2,
  Customer_Email,
  City,
  Zip_Code,
  State,
  Tax_Type,
  Tax_Rate,
  Sr_No,
  Collectible_Amount,
  Order_Invoice_Amount,
  TCS_Rate,
  TCS,
  Selling_Price,
  Wallet_Discount,
  Item_Price_Excluding_Tax_,
  COD_Excluding_Tax_,
  Shipping_Charge_Excluding_Tax_,
  Shipping_Discount_Excluding_Tax_,
  Promotion_Discount_Excluding_Tax_,
  Miscellaneous_Excluding_Tax_,
  Gift_Wrap_Charges_Excluding_Tax_,
  Prepaid_Discount_Excluding_Tax_,
  Promocode_Discount_Excluding_Tax_,
  Taxable_Value,
  Tax,
  IGST,
  CGST,
  SGST,
  CESS,
  UTGST,
  TDS,
  IRN_Number,
  Acknowledgement_Num,
  Acknowledgement_Date,
  Eway_Bill_Number,
  Eway_Bill_Date, 
  CRN_Number,
  CreditNote_Acknowledgement_Num,
  CreditNote_Acknowledgement_Date,
  Debit_Note_Number,
  Sales_Channel,
  Manifest_Date,
  ERP_Customer_ID,
  EE_Client_ID,
  Invoice_ERP_Transaction_ID,
  Billing_Customer_Name,
  Billing_Mobile_No,
  Billing_Customer_Email,
  Billing_Address_Line_1,
  Billing_Address_Line_2,
  Billing_City,
  Billing_Zip_Code,
  Billing_State,
  Billing_Country,
  A_c_SKu,
  External_Order_Code,
  A_c_Unit,
  GRN_Cost_per_unit,
  Additional_cost_per_unit,
  Cost_of_Goods_Purchased,
  Delivery_Appointment_Date,
  report_id,
  report_type,
  start_date,
  end_date,
  created_on,
  inventory_type,
  -- ee_extracted_at
)
VALUES
(
SOURCE.Company_Name,
SOURCE.Seller_GST_Num,
SOURCE.MP_Name,
SOURCE.Reference_Code,
SOURCE.Suborder_No,
SOURCE.Order_Type,
SOURCE.EE_Invoice_No,
SOURCE.MP_Ref_No,
SOURCE.Order_Status,
SOURCE.Invoice_Status,
SOURCE.Credit_Note_ID,
SOURCE.CR_Voucher_Num,
SOURCE.Return_Date,
SOURCE.Import_Date,
SOURCE.Order_Date,
SOURCE.Invoice_Date,
SOURCE.Parent_Courier_Partner,
SOURCE.Courier,
SOURCE.AWB_No,
SOURCE.Component_SKU,
SOURCE.Product_Config,
SOURCE.Parent_SKU,
SOURCE.Parent_Quantity,
SOURCE.Item_Quantity,
SOURCE.Parent_SKU_Weight,
SOURCE.Component_SKU_Weight,
SOURCE.Component_SKU_Description,
SOURCE.Component_SKU_Name,
SOURCE.Component_SKU_HSN,
SOURCE.Component_SKU_Category,
SOURCE.Component_SKU_Brand,
SOURCE.Component_SKU_Cost,
SOURCE.Component_SKU_MRP,
SOURCE.Payment_Mode,
SOURCE.Buyer_GST_Num,
SOURCE.Customer_Name,
SOURCE.Mobile_No,
SOURCE.Address_Line_1,
SOURCE.Address_Line_2,
SOURCE.Customer_Email,
SOURCE.City,
SOURCE.Zip_Code,
SOURCE.State,
SOURCE.Tax_Type,
SOURCE.Tax_Rate,
SOURCE.Sr_No,
SOURCE.Collectible_Amount,
SOURCE.Order_Invoice_Amount,
SOURCE.TCS_Rate,
SOURCE.TCS,
SOURCE.Selling_Price,
SOURCE.Wallet_Discount,
SOURCE.Item_Price_Excluding_Tax_,
SOURCE.COD_Excluding_Tax_,
SOURCE.Shipping_Charge_Excluding_Tax_,
SOURCE.Shipping_Discount_Excluding_Tax_,
SOURCE.Promotion_Discount_Excluding_Tax_,
SOURCE.Miscellaneous_Excluding_Tax_,
SOURCE.Gift_Wrap_Charges_Excluding_Tax_,
SOURCE.Prepaid_Discount_Excluding_Tax_,
SOURCE.Promocode_Discount_Excluding_Tax_,
SOURCE.Taxable_Value,
SOURCE.Tax,
SOURCE.IGST,
SOURCE.CGST,
SOURCE.SGST,
SOURCE.CESS,
SOURCE.UTGST,
SOURCE.TDS,
SOURCE.IRN_Number,
SOURCE.Acknowledgement_Num,
SOURCE.Acknowledgement_Date,
SOURCE.Eway_Bill_Number,
SOURCE.Eway_Bill_Date,
SOURCE.CRN_Number,
SOURCE.CreditNote_Acknowledgement_Num,
SOURCE.CreditNote_Acknowledgement_Date,
SOURCE.Debit_Note_Number,
SOURCE.Sales_Channel,
SOURCE.Manifest_Date,
SOURCE.ERP_Customer_ID,
SOURCE.EE_Client_ID,
SOURCE.Invoice_ERP_Transaction_ID,
SOURCE.Billing_Customer_Name,
SOURCE.Billing_Mobile_No,
SOURCE.Billing_Customer_Email,
SOURCE.Billing_Address_Line_1,
SOURCE.Billing_Address_Line_2,
SOURCE.Billing_City,
SOURCE.Billing_Zip_Code,
SOURCE.Billing_State,
SOURCE.Billing_Country,
SOURCE.A_c_SKu,
SOURCE.External_Order_Code,
SOURCE.A_c_Unit,
SOURCE.GRN_Cost_per_unit,
SOURCE.Additional_cost_per_unit,
SOURCE.Cost_of_Goods_Purchased,
SOURCE.Delivery_Appointment_Date,
SOURCE.report_id,
SOURCE.report_type,
SOURCE.start_date,
SOURCE.end_date,
SOURCE.created_on,
SOURCE.inventory_type,
SOURCE.-- ee_extracted_at
)