MERGE INTO `shopify-pubsub-project.Data_Warehouse_GoogleAds_Staging.ad_group_ad_legacy` AS TARGET
USING
(
SELECT
_airbyte_extracted_at,
ad_group_ad_ad_added_by_google_ads,
ad_group_ad_ad_legacy_responsive_display_ad_allow_flexible_color,
ad_group_ad_ad_responsive_display_ad_allow_flexible_color,
segments_date,
_airbyte_generation_id,
ad_group_ad_ad_id,
ad_group_ad_ad_image_ad_pixel_height,
ad_group_ad_ad_image_ad_pixel_width,
ad_group_id,
campaign_id,
customer_id,
metrics_active_view_impressions,
metrics_active_view_measurable_cost_micros,
metrics_active_view_measurable_impressions,
metrics_clicks,
metrics_cost_micros,
metrics_engagements,
metrics_gmail_forwards,
metrics_gmail_saves,
metrics_gmail_secondary_clicks,
metrics_impressions,
metrics_interactions,
metrics_video_views,
metrics_view_through_conversions,
segments_year,
metrics_active_view_cpm,
metrics_active_view_ctr,
metrics_active_view_measurability,
metrics_active_view_viewability,
metrics_all_conversions,
metrics_all_conversions_from_interactions_rate,
metrics_all_conversions_value,
metrics_average_cost,
metrics_average_cpc,
metrics_average_cpe,
metrics_average_cpm,
metrics_average_cpv,
metrics_average_page_views,
metrics_average_time_on_site,
metrics_bounce_rate,
metrics_conversions,
metrics_conversions_from_interactions_rate,
metrics_conversions_value,
metrics_cost_per_all_conversions,
metrics_cost_per_conversion,
metrics_cost_per_current_model_attributed_conversion,
metrics_cross_device_conversions,
metrics_ctr,
metrics_current_model_attributed_conversions,
metrics_current_model_attributed_conversions_value,
metrics_engagement_rate,
metrics_interaction_rate,
metrics_percent_new_visitors,
metrics_top_impression_percentage,
metrics_value_per_all_conversions,
metrics_value_per_conversion,
metrics_value_per_current_model_attributed_conversion,
metrics_video_quartile_p100_rate,
metrics_video_quartile_p25_rate,
metrics_video_quartile_p50_rate,
metrics_video_quartile_p75_rate,
metrics_video_view_rate,
ad_group_ad_ad_device_preference,
ad_group_ad_ad_legacy_responsive_display_ad_format_setting,
ad_group_ad_ad_system_managed_resource_source,
ad_group_ad_ad_final_urls,
segments_ad_network_type,
JSON_EXTRACT_SCALAR(ad_group_ad_ad_final_urls, '$[0]') AS ad_final_url,
REGEXP_EXTRACT(JSON_EXTRACT_SCALAR(ad_group_ad_ad_responsive_display_ad_marketing_images, '$[0]'),r'customersd+assetsd+') AS extracted_marketing_images,
REGEXP_EXTRACT(JSON_EXTRACT_SCALAR(ad_group_ad_ad_responsive_display_ad_marketing_images, '$[0]'),r'customersd+assetsd+') AS extracted_sq_logo_images,
FROM
(
select *,
row_number() over(partition by ad_group_ad_ad_id,segments_date,segments_ad_network_type order by _airbyte_extracted_at desc) as rn
from shopify-pubsub-project.pilgrim_bi_google_ads.ad_group_ad_legacy
)
where rn = 1 and DATE(_airbyte_extracted_at) >= DATE_SUB(CURRENT_DATE("Asia/Kolkata"), INTERVAL 10 DAY)
) AS SOURCE
ON TARGET.ad_group_ad_ad_id = SOURCE.ad_group_ad_ad_id
and TARGET.segments_date = SOURCE.segments_date
and TARGET.segments_ad_network_type = SOURCE.segments_ad_network_type
WHEN
  MATCHED AND SOURCE._airbyte_extracted_at > TARGET._airbyte_extracted_at
THEN
  UPDATE SET
  TARGET._airbyte_extracted_at = SOURCE._airbyte_extracted_at,
  TARGET.ad_group_ad_ad_added_by_google_ads = SOURCE.ad_group_ad_ad_added_by_google_ads,
  TARGET.ad_group_ad_ad_legacy_responsive_display_ad_allow_flexible_color = SOURCE.ad_group_ad_ad_legacy_responsive_display_ad_allow_flexible_color,
  TARGET.ad_group_ad_ad_responsive_display_ad_allow_flexible_color = SOURCE.ad_group_ad_ad_responsive_display_ad_allow_flexible_color,
  TARGET.segments_date = SOURCE.segments_date,
  TARGET._airbyte_generation_id = SOURCE._airbyte_generation_id,
  TARGET.ad_group_ad_ad_id = SOURCE.ad_group_ad_ad_id,
  TARGET.ad_group_ad_ad_image_ad_pixel_height = SOURCE.ad_group_ad_ad_image_ad_pixel_height,
  TARGET.ad_group_ad_ad_image_ad_pixel_width = SOURCE.ad_group_ad_ad_image_ad_pixel_width,
  TARGET.ad_group_id = SOURCE.ad_group_id,
  TARGET.campaign_id = SOURCE.campaign_id,
  TARGET.customer_id = SOURCE.customer_id,
  TARGET.metrics_active_view_impressions = SOURCE.metrics_active_view_impressions,
  TARGET.metrics_active_view_measurable_cost_micros = SOURCE.metrics_active_view_measurable_cost_micros,
  TARGET.metrics_active_view_measurable_impressions = SOURCE.metrics_active_view_measurable_impressions,
  TARGET.metrics_clicks = SOURCE.metrics_clicks,
  TARGET.metrics_cost_micros = SOURCE.metrics_cost_micros,
  TARGET.metrics_engagements = SOURCE.metrics_engagements,
  TARGET.metrics_gmail_forwards = SOURCE.metrics_gmail_forwards,
  TARGET.metrics_gmail_saves = SOURCE.metrics_gmail_saves,
  TARGET.metrics_gmail_secondary_clicks = SOURCE.metrics_gmail_secondary_clicks,
  TARGET.metrics_impressions = SOURCE.metrics_impressions,
  TARGET.metrics_interactions = SOURCE.metrics_interactions,
  TARGET.metrics_video_views = SOURCE.metrics_video_views,
  TARGET.metrics_view_through_conversions = SOURCE.metrics_view_through_conversions,
  TARGET.segments_year = SOURCE.segments_year,
  TARGET.metrics_active_view_cpm = SOURCE.metrics_active_view_cpm,
  TARGET.metrics_active_view_ctr = SOURCE.metrics_active_view_ctr,
  TARGET.metrics_active_view_measurability = SOURCE.metrics_active_view_measurability,
  TARGET.metrics_active_view_viewability = SOURCE.metrics_active_view_viewability,
  TARGET.metrics_all_conversions = SOURCE.metrics_all_conversions,
  TARGET.metrics_all_conversions_from_interactions_rate = SOURCE.metrics_all_conversions_from_interactions_rate,
  TARGET.metrics_all_conversions_value = SOURCE.metrics_all_conversions_value,
  TARGET.metrics_average_cost = SOURCE.metrics_average_cost,
  TARGET.metrics_average_cpc = SOURCE.metrics_average_cpc,
  TARGET.metrics_average_cpe = SOURCE.metrics_average_cpe,
  TARGET.metrics_average_cpm = SOURCE.metrics_average_cpm,
  TARGET.metrics_average_cpv = SOURCE.metrics_average_cpv,
  TARGET.metrics_average_page_views = SOURCE.metrics_average_page_views,
  TARGET.metrics_average_time_on_site = SOURCE.metrics_average_time_on_site,
  TARGET.metrics_bounce_rate = SOURCE.metrics_bounce_rate,
  TARGET.metrics_conversions = SOURCE.metrics_conversions,
  TARGET.metrics_conversions_from_interactions_rate = SOURCE.metrics_conversions_from_interactions_rate,
  TARGET.metrics_conversions_value = SOURCE.metrics_conversions_value,
  TARGET.metrics_cost_per_all_conversions = SOURCE.metrics_cost_per_all_conversions,
  TARGET.metrics_cost_per_conversion = SOURCE.metrics_cost_per_conversion,
  TARGET.metrics_cost_per_current_model_attributed_conversion = SOURCE.metrics_cost_per_current_model_attributed_conversion,
  TARGET.metrics_cross_device_conversions = SOURCE.metrics_cross_device_conversions,
  TARGET.metrics_ctr = SOURCE.metrics_ctr,
  TARGET.metrics_current_model_attributed_conversions = SOURCE.metrics_current_model_attributed_conversions,
  TARGET.metrics_current_model_attributed_conversions_value = SOURCE.metrics_current_model_attributed_conversions_value,
  TARGET.metrics_engagement_rate = SOURCE.metrics_engagement_rate,
  TARGET.metrics_interaction_rate = SOURCE.metrics_interaction_rate,
  TARGET.metrics_percent_new_visitors = SOURCE.metrics_percent_new_visitors,
  TARGET.metrics_top_impression_percentage = SOURCE.metrics_top_impression_percentage,
  TARGET.metrics_value_per_all_conversions = SOURCE.metrics_value_per_all_conversions,
  TARGET.metrics_value_per_conversion = SOURCE.metrics_value_per_conversion,
  TARGET.metrics_value_per_current_model_attributed_conversion = SOURCE.metrics_value_per_current_model_attributed_conversion,
  TARGET.metrics_video_quartile_p100_rate = SOURCE.metrics_video_quartile_p100_rate,
  TARGET.metrics_video_quartile_p25_rate = SOURCE.metrics_video_quartile_p25_rate,
  TARGET.metrics_video_quartile_p50_rate = SOURCE.metrics_video_quartile_p50_rate,
  TARGET.metrics_video_quartile_p75_rate = SOURCE.metrics_video_quartile_p75_rate,
  TARGET.metrics_video_view_rate = SOURCE.metrics_video_view_rate,
  TARGET.ad_group_ad_ad_device_preference = SOURCE.ad_group_ad_ad_device_preference,
  TARGET.ad_group_ad_ad_legacy_responsive_display_ad_format_setting = SOURCE.ad_group_ad_ad_legacy_responsive_display_ad_format_setting,
  TARGET.ad_group_ad_ad_system_managed_resource_source = SOURCE.ad_group_ad_ad_system_managed_resource_source,
  TARGET.ad_group_ad_ad_final_urls = SOURCE.ad_group_ad_ad_final_urls,
  TARGET.ad_final_url = SOURCE.ad_final_url,
  TARGET.extracted_marketing_images = SOURCE.extracted_marketing_images,
  TARGET.extracted_sq_logo_images = SOURCE.extracted_sq_logo_images
WHEN NOT MATCHED
THEN INSERT
(
  _airbyte_extracted_at,
  ad_group_ad_ad_added_by_google_ads,
  ad_group_ad_ad_legacy_responsive_display_ad_allow_flexible_color,
  ad_group_ad_ad_responsive_display_ad_allow_flexible_color,
  segments_date,
  _airbyte_generation_id,
  ad_group_ad_ad_id,
  ad_group_ad_ad_image_ad_pixel_height,
  ad_group_ad_ad_image_ad_pixel_width,
  ad_group_id,
  campaign_id,
  customer_id,
  metrics_active_view_impressions,
  metrics_active_view_measurable_cost_micros,
  metrics_active_view_measurable_impressions,
  metrics_clicks,
  metrics_cost_micros,
  metrics_engagements,
  metrics_gmail_forwards,
  metrics_gmail_saves,
  metrics_gmail_secondary_clicks,
  metrics_impressions,
  metrics_interactions,
  metrics_video_views,
  metrics_view_through_conversions,
  segments_year,
  metrics_active_view_cpm,
  metrics_active_view_ctr,
  metrics_active_view_measurability,
  metrics_active_view_viewability,
  metrics_all_conversions,
  metrics_all_conversions_from_interactions_rate,
  metrics_all_conversions_value,
  metrics_average_cost,
  metrics_average_cpc,
  metrics_average_cpe,
  metrics_average_cpm,
  metrics_average_cpv,
  metrics_average_page_views,
  metrics_average_time_on_site,
  metrics_bounce_rate,
  metrics_conversions,
  metrics_conversions_from_interactions_rate,
  metrics_conversions_value,
  metrics_cost_per_all_conversions,
  metrics_cost_per_conversion,
  metrics_cost_per_current_model_attributed_conversion,
  metrics_cross_device_conversions,
  metrics_ctr,
  metrics_current_model_attributed_conversions,
  metrics_current_model_attributed_conversions_value,
  metrics_engagement_rate,
  metrics_interaction_rate,
  metrics_percent_new_visitors,
  metrics_top_impression_percentage,
  metrics_value_per_all_conversions,
  metrics_value_per_conversion,
  metrics_value_per_current_model_attributed_conversion,
  metrics_video_quartile_p100_rate,
  metrics_video_quartile_p25_rate,
  metrics_video_quartile_p50_rate,
  metrics_video_quartile_p75_rate,
  metrics_video_view_rate,
  ad_group_ad_ad_device_preference,
  ad_group_ad_ad_legacy_responsive_display_ad_format_setting,
  ad_group_ad_ad_system_managed_resource_source,
  ad_group_ad_ad_final_urls,
  ad_final_url,
  extracted_marketing_images,
  extracted_sq_logo_images
)
VALUES
(
  SOURCE._airbyte_extracted_at,
  SOURCE.ad_group_ad_ad_added_by_google_ads,
  SOURCE.ad_group_ad_ad_legacy_responsive_display_ad_allow_flexible_color,
  SOURCE.ad_group_ad_ad_responsive_display_ad_allow_flexible_color,
  SOURCE.segments_date,
  SOURCE._airbyte_generation_id,
  SOURCE.ad_group_ad_ad_id,
  SOURCE.ad_group_ad_ad_image_ad_pixel_height,
  SOURCE.ad_group_ad_ad_image_ad_pixel_width,
  SOURCE.ad_group_id,
  SOURCE.campaign_id,
  SOURCE.customer_id,
  SOURCE.metrics_active_view_impressions,
  SOURCE.metrics_active_view_measurable_cost_micros,
  SOURCE.metrics_active_view_measurable_impressions,
  SOURCE.metrics_clicks,
  SOURCE.metrics_cost_micros,
  SOURCE.metrics_engagements,
  SOURCE.metrics_gmail_forwards,
  SOURCE.metrics_gmail_saves,
  SOURCE.metrics_gmail_secondary_clicks,
  SOURCE.metrics_impressions,
  SOURCE.metrics_interactions,
  SOURCE.metrics_video_views,
  SOURCE.metrics_view_through_conversions,
  SOURCE.segments_year,
  SOURCE.metrics_active_view_cpm,
  SOURCE.metrics_active_view_ctr,
  SOURCE.metrics_active_view_measurability,
  SOURCE.metrics_active_view_viewability,
  SOURCE.metrics_all_conversions,
  SOURCE.metrics_all_conversions_from_interactions_rate,
  SOURCE.metrics_all_conversions_value,
  SOURCE.metrics_average_cost,
  SOURCE.metrics_average_cpc,
  SOURCE.metrics_average_cpe,
  SOURCE.metrics_average_cpm,
  SOURCE.metrics_average_cpv,
  SOURCE.metrics_average_page_views,
  SOURCE.metrics_average_time_on_site,
  SOURCE.metrics_bounce_rate,
  SOURCE.metrics_conversions,
  SOURCE.metrics_conversions_from_interactions_rate,
  SOURCE.metrics_conversions_value,
  SOURCE.metrics_cost_per_all_conversions,
  SOURCE.metrics_cost_per_conversion,
  SOURCE.metrics_cost_per_current_model_attributed_conversion,
  SOURCE.metrics_cross_device_conversions,
  SOURCE.metrics_ctr,
  SOURCE.metrics_current_model_attributed_conversions,
  SOURCE.metrics_current_model_attributed_conversions_value,
  SOURCE.metrics_engagement_rate,
  SOURCE.metrics_interaction_rate,
  SOURCE.metrics_percent_new_visitors,
  SOURCE.metrics_top_impression_percentage,
  SOURCE.metrics_value_per_all_conversions,
  SOURCE.metrics_value_per_conversion,
  SOURCE.metrics_value_per_current_model_attributed_conversion,
  SOURCE.metrics_video_quartile_p100_rate,
  SOURCE.metrics_video_quartile_p25_rate,
  SOURCE.metrics_video_quartile_p50_rate,
  SOURCE.metrics_video_quartile_p75_rate,
  SOURCE.metrics_video_view_rate,
  SOURCE.ad_group_ad_ad_device_preference,
  SOURCE.ad_group_ad_ad_legacy_responsive_display_ad_format_setting,
  SOURCE.ad_group_ad_ad_system_managed_resource_source,
  SOURCE.ad_group_ad_ad_final_urls,
  SOURCE.ad_final_url,
  SOURCE.extracted_marketing_images,
  SOURCE.extracted_sq_logo_images
)