
MERGE INTO `shopify-pubsub-project.Data_Warehouse_Shopify_Staging.Orders` AS target
USING (
WITH source_orders AS (
  SELECT
    _airbyte_extracted_at,
    note AS Order_note,
    cancel_reason AS Order_cancelled_reason,
    cancelled_at AS Order_cancelled_at,
    landing_site AS landing_weburl,
    referring_site AS referring_weburl,
    cart_token AS Order_cart_token,
    browser_ip AS browser_ip_id,
    CAST(checkout_id AS STRING) AS Order_checkout_id,
    checkout_token AS Order_checkout_token,
    closed_at AS Order_closed_at,
    fulfillment_status AS Order_fulfillment_status,
    currency AS Order_currency,
    shop_url AS Order_shop_url,
    confirmed AS Order_confirmed,
    estimated_taxes AS Order_estimated_taxes,
    test AS isTestOrder,
    taxes_included AS Order_taxes_included,
    financial_status AS Order_financial_status,
    source_name AS Order_source_name,
    CAST(app_id AS STRING) AS Order_app_id,
    CAST(total_line_items_price AS FLOAT64) AS total_line_items_price,
    CAST(total_tax AS FLOAT64) AS total_tax,
    CAST(total_price AS FLOAT64) AS Order_total_price,
    CAST(total_discounts AS FLOAT64) AS Order_total_discounts,
    tags AS Order_tags,
    updated_at AS Order_updated_at,
    created_at AS Order_created_at,
    CAST(processed_at AS TIMESTAMP) AS Order_processed_at,
    name AS Order_name,
    CAST(id AS STRING) AS Order_id,
    token AS Order_token,
    CAST(order_number AS STRING) AS Order_number,

    JSON_EXTRACT_SCALAR(customer, '$.id') AS customer_id,

    JSON_EXTRACT_SCALAR(tax_lines, '$[0].channel_liable') AS tax_channel_liable,
    CAST(JSON_EXTRACT_SCALAR(tax_lines, '$[0].price') AS FLOAT64) AS tax_price,
    CAST(JSON_EXTRACT_SCALAR(tax_lines, '$[0].rate') AS FLOAT64) AS tax_rate,
    JSON_EXTRACT_SCALAR(tax_lines, '$[0].title') AS tax_title,

    JSON_EXTRACT_SCALAR(client_details, '$.accept_language') AS browser_language,
    JSON_EXTRACT_SCALAR(client_details, '$.browser_height') AS browser_height,
    JSON_EXTRACT_SCALAR(client_details, '$.browser_ip') AS browser_ip,
    JSON_EXTRACT_SCALAR(client_details, '$.browser_width') AS browser_width,
    JSON_EXTRACT_SCALAR(client_details, '$.session_hash') AS session_hash,
    JSON_EXTRACT_SCALAR(client_details, '$.user_agent') AS browser_agent,

    CAST(JSON_EXTRACT_SCALAR(discount_codes, '$[0].amount') AS FLOAT64) AS discount_amount,
    JSON_EXTRACT_SCALAR(discount_codes, '$[0].code') AS discount_code,
    JSON_EXTRACT_SCALAR(discount_codes, '$[0].type') AS discount_type,

  

    JSON_EXTRACT_SCALAR(billing_address, '$.address1') AS billing_address,
    JSON_EXTRACT_SCALAR(billing_address, '$.city') AS billing_city,
    JSON_EXTRACT_SCALAR(billing_address, '$.country') AS billing_country,
    JSON_EXTRACT_SCALAR(billing_address, '$.country_code') AS billing_country_code,
    JSON_EXTRACT_SCALAR(billing_address, '$.province') AS billing_province,
    JSON_EXTRACT_SCALAR(billing_address, '$.province_code') AS billing_province_code,
    JSON_EXTRACT_SCALAR(billing_address, '$.zip') AS billing_zip,

    JSON_EXTRACT_SCALAR(shipping_address, '$.address1') AS shipping_address,
    JSON_EXTRACT_SCALAR(shipping_address, '$.city') AS shipping_city,
    JSON_EXTRACT_SCALAR(shipping_address, '$.country') AS shipping_country,
    JSON_EXTRACT_SCALAR(shipping_address, '$.country_code') AS shipping_country_code,
    JSON_EXTRACT_SCALAR(shipping_address, '$.province') AS shipping_province,
    JSON_EXTRACT_SCALAR(shipping_address, '$.province_code') AS shipping_province_code,
    JSON_EXTRACT_SCALAR(shipping_address, '$.zip') AS shipping_zip,
    REGEXP_EXTRACT(landing_site, r"utm_source=([^&]+)") AS utm_source,
    REGEXP_EXTRACT(landing_site, r"utm_medium=([^&]+)") AS utm_medium,
    REGEXP_EXTRACT(landing_site, r"utm_campaign=([^&]+)") AS utm_campaign,
    REGEXP_EXTRACT(landing_site, r"utm_content=([^&]+)") AS utm_content,
    REGEXP_EXTRACT(landing_site, r"utm_term=([^&]+)") AS utm_term,
    REGEXP_EXTRACT(landing_site, r"utm_id=([^&]+)") AS utm_id,
    REGEXP_EXTRACT(landing_site, r"campaign_id=([^&]+)") AS campaign_id,
    REGEXP_EXTRACT(landing_site, r"ad_id=([^&]+)") AS ad_id,
    admin_graphql_api_id,

    ARRAY_TO_STRING(
    ARRAY(
      SELECT JSON_EXTRACT_SCALAR(element, '$.title') 
      FROM UNNEST(JSON_EXTRACT_ARRAY(discount_applications)) AS element
    ), ',') AS discount_application,

    payment_gateway_names

  FROM `shopify-pubsub-project.pilgrim_bi_airbyte.orders`

)

SELECT 
  _airbyte_extracted_at, Order_note, Order_cancelled_reason, Order_cancelled_at, landing_weburl,
  referring_weburl, Order_cart_token, browser_ip_id, Order_checkout_id, Order_checkout_token, 
  Order_closed_at, Order_fulfillment_status, Order_currency, Order_shop_url, Order_confirmed, 
  Order_estimated_taxes, isTestOrder, Order_taxes_included, Order_financial_status, 
  Order_source_name, Order_app_id, total_line_items_price, total_tax, Order_total_price, 
  Order_total_discounts, Order_tags, Order_updated_at, Order_created_at, Order_processed_at, 
  Order_name, Order_id, Order_token, Order_number, customer_id, tax_channel_liable, 
  tax_price, tax_rate, tax_title, browser_language, browser_height, browser_ip, 
  browser_width, session_hash, browser_agent, discount_amount, discount_type, 
  billing_address, billing_city, billing_country, billing_country_code, billing_province, 
  billing_province_code, billing_zip, shipping_address, shipping_city, shipping_country, 
  shipping_country_code, shipping_province, shipping_province_code, shipping_zip, 
  admin_graphql_api_id,utm_source,utm_medium,utm_campaign,utm_content,utm_term,utm_id,campaign_id,ad_id,
  discount_application,
  discount_code,
  CONCAT(coalesce(discount_application,''), ' - ', coalesce(discount_code,'')) as discount_final,
  STRING_AGG(payment_gateway_name, ', ') AS payment_gateway_names,
  

FROM source_orders
LEFT JOIN UNNEST(JSON_VALUE_ARRAY(payment_gateway_names)) AS payment_gateway_name
GROUP BY ALL
 ) AS source
ON target.Order_id = source.Order_id
WHEN MATCHED AND source._airbyte_extracted_at > target._airbyte_extracted_at THEN UPDATE SET

target._airbyte_extracted_at = source._airbyte_extracted_at,
target.Order_note = source.Order_note,
target.Order_cancelled_reason = source.Order_cancelled_reason,
target.Order_cancelled_at = source.Order_cancelled_at,
target.landing_weburl = source.landing_weburl,
target.referring_weburl = source.referring_weburl,
target.Order_cart_token = source.Order_cart_token,
target.browser_ip_id = source.browser_ip_id,
target.Order_checkout_id = source.Order_checkout_id,
target.Order_checkout_token = source.Order_checkout_token,
target.Order_closed_at = source.Order_closed_at,
target.Order_fulfillment_status = source.Order_fulfillment_status,
target.Order_currency = source.Order_currency,
target.Order_shop_url = source.Order_shop_url,
target.Order_confirmed = source.Order_confirmed,
target.Order_estimated_taxes = source.Order_estimated_taxes,
target.isTestOrder = source.isTestOrder,
target.Order_taxes_included = source.Order_taxes_included,
target.Order_financial_status = source.Order_financial_status,
target.Order_source_name = source.Order_source_name,
target.Order_app_id = source.Order_app_id,
target.total_line_items_price = source.total_line_items_price,
target.total_tax = source.total_tax,
target.Order_total_price = source.Order_total_price,
target.Order_total_discounts = source.Order_total_discounts,
target.Order_tags = source.Order_tags,
target.Order_updated_at = source.Order_updated_at,
target.Order_created_at = source.Order_created_at,
target.Order_processed_at = source.Order_processed_at,
target.Order_name = source.Order_name,
target.Order_id = source.Order_id,
target.Order_token = source.Order_token,
target.Order_number = source.Order_number,
target.customer_id = source.customer_id,
target.tax_channel_liable = source.tax_channel_liable,
target.tax_price = source.tax_price,
target.tax_rate = source.tax_rate,
target.tax_title = source.tax_title,
target.browser_language = source.browser_language,
target.browser_height = source.browser_height,
target.browser_ip = source.browser_ip,
target.browser_width = source.browser_width,
target.session_hash = source.session_hash,
target.browser_agent = source.browser_agent,
target.discount_amount = source.discount_amount,
target.discount_type = source.discount_type,
target.billing_address = source.billing_address,
target.billing_city = source.billing_city,
target.billing_country = source.billing_country,
target.billing_country_code = source.billing_country_code,
target.billing_province = source.billing_province,
target.billing_province_code = source.billing_province_code,
target.billing_zip = source.billing_zip,
target.shipping_address = source.shipping_address,
target.shipping_city = source.shipping_city,
target.shipping_country = source.shipping_country,
target.shipping_country_code = source.shipping_country_code,
target.shipping_province = source.shipping_province,
target.shipping_province_code = source.shipping_province_code,
target.shipping_zip = source.shipping_zip,
target.admin_graphql_api_id = source.admin_graphql_api_id,
target.utm_source = source.utm_source,
target.utm_medium = source.utm_medium,
target.utm_campaign = source.utm_campaign,
target.utm_content = source.utm_content,
target.utm_term = source.utm_term,
target.utm_id = source.utm_id,
target.campaign_id = source.campaign_id,
target.ad_id = source.ad_id,
target.payment_gateway_names = source.payment_gateway_names,
target.discount_final = source.discount_final


WHEN NOT MATCHED THEN INSERT (
_airbyte_extracted_at,
Order_note,
Order_cancelled_reason,
Order_cancelled_at,
landing_weburl,
referring_weburl,
Order_cart_token,
browser_ip_id,
Order_checkout_id,
Order_checkout_token,
Order_closed_at,
Order_fulfillment_status,
Order_currency,
Order_shop_url,
Order_confirmed,
Order_estimated_taxes,
isTestOrder,
Order_taxes_included,
Order_financial_status,
Order_source_name,
Order_app_id,
total_line_items_price,
total_tax,
Order_total_price,
Order_total_discounts,
Order_tags,
Order_updated_at,
Order_created_at,
Order_processed_at,
Order_name,
Order_id,
Order_token,
Order_number,
customer_id,
tax_channel_liable,
tax_price,
tax_rate,
tax_title,
browser_language,
browser_height,
browser_ip,
browser_width,
session_hash,
browser_agent,
discount_amount,
discount_type,
billing_address,
billing_city,
billing_country,
billing_country_code,
billing_province,
billing_province_code,
billing_zip,
shipping_address,
shipping_city,
shipping_country,
shipping_country_code,
shipping_province,
shipping_province_code,
shipping_zip,
admin_graphql_api_id,
utm_source,
utm_medium,
utm_campaign,
utm_content,
utm_term,
utm_id,
campaign_id,
ad_id,
payment_gateway_names,
discount_final
)
  VALUES (
source._airbyte_extracted_at,
source.Order_note,
source.Order_cancelled_reason,
source.Order_cancelled_at,
source.landing_weburl,
source.referring_weburl,
source.Order_cart_token,
source.browser_ip_id,
source.Order_checkout_id,
source.Order_checkout_token,
source.Order_closed_at,
source.Order_fulfillment_status,
source.Order_currency,
source.Order_shop_url,
source.Order_confirmed,
source.Order_estimated_taxes,
source.isTestOrder,
source.Order_taxes_included,
source.Order_financial_status,
source.Order_source_name,
source.Order_app_id,
source.total_line_items_price,
source.total_tax,
source.Order_total_price,
source.Order_total_discounts,
source.Order_tags,
source.Order_updated_at,
source.Order_created_at,
source.Order_processed_at,
source.Order_name,
source.Order_id,
source.Order_token,
source.Order_number,
source.customer_id,
source.tax_channel_liable,
source.tax_price,
source.tax_rate,
source.tax_title,
source.browser_language,
source.browser_height,
source.browser_ip,
source.browser_width,
source.session_hash,
source.browser_agent,
source.discount_amount,
source.discount_type,
source.billing_address,
source.billing_city,
source.billing_country,
source.billing_country_code,
source.billing_province,
source.billing_province_code,
source.billing_zip,
source.shipping_address,
source.shipping_city,
source.shipping_country,
source.shipping_country_code,
source.shipping_province,
source.shipping_province_code,
source.shipping_zip,
source.admin_graphql_api_id,
source.utm_source,
source.utm_medium,
source.utm_campaign,
source.utm_content,
source.utm_term,
source.utm_id,
source.campaign_id,
source.ad_id,
source.payment_gateway_names,
source.discount_final
  )
