MERGE INTO `shopify-pubsub-project.Data_Warehouse_GoogleAds_Staging.campaign_budget` AS TARGET
USING
(
  SELECT
    _airbyte_extracted_at,
    campaign_budget_aligned_bidding_strategy_id,
    campaign_budget_amount_micros,
    campaign_budget_delivery_method,
    campaign_budget_explicitly_shared,
    campaign_budget_has_recommended_budget,
    campaign_budget_id,
    campaign_budget_name,
    campaign_budget_period,
    campaign_budget_recommended_budget_amount_micros,
    campaign_budget_recommended_budget_estimated_change_weekly_clicks,
    campaign_budget_recommended_budget_estimated_change_weekly_cost_micros,
    campaign_budget_recommended_budget_estimated_change_weekly_interactions,
    campaign_budget_recommended_budget_estimated_change_weekly_views,
    campaign_budget_reference_count,
    campaign_budget_resource_name,
    campaign_budget_status,
    campaign_budget_total_amount_micros,
    campaign_budget_type,
    campaign_id,
    customer_id,
    metrics_all_conversions,
    metrics_all_conversions_from_interactions_rate,
    metrics_all_conversions_value,
    metrics_average_cost,
    metrics_average_cpc,
    metrics_average_cpe,
    metrics_average_cpm,
    metrics_average_cpv,
    metrics_clicks,
    metrics_conversions,
    metrics_conversions_from_interactions_rate,
    metrics_conversions_value,
    metrics_cost_micros,
    metrics_cost_per_all_conversions,
    metrics_cost_per_conversion,
    metrics_cross_device_conversions,
    metrics_ctr,
    metrics_engagement_rate,
    metrics_engagements,
    metrics_impressions,
    metrics_interaction_rate,
    metrics_interactions,
    metrics_value_per_all_conversions,
    metrics_value_per_conversion,
    metrics_video_view_rate,
    metrics_video_views,
    metrics_view_through_conversions,
    segments_budget_campaign_association_status_campaign,
    segments_budget_campaign_association_status_status,
    ARRAY_TO_STRING
    (
      ARRAY
      (
        SELECT
          REGEXP_EXTRACT(JSON_EXTRACT_SCALAR(event, '$'), r'InteractionEventType\.(\w+)')
        FROM
          UNNEST(JSON_EXTRACT_ARRAY(metrics_interaction_event_types)) AS event
      ),
      ', '
    ) AS InteractionEventType
  FROM (
    SELECT
      *,
      ROW_NUMBER() OVER (PARTITION BY campaign_id ORDER BY _airbyte_extracted_at DESC) AS row_num
    FROM
      `shopify-pubsub-project.pilgrim_bi_google_ads.campaign_budget`
    WHERE
      DATE(_airbyte_extracted_at) >= DATE_SUB(CURRENT_DATE("Asia/Kolkata"), INTERVAL 10 DAY)
  )
  WHERE row_num = 1 -- Keep only the most recent row per label_id
) AS SOURCE
ON TARGET.campaign_id = SOURCE.campaign_id
WHEN MATCHED AND SOURCE._airbyte_extracted_at > TARGET._airbyte_extracted_at
THEN
  UPDATE SET
  TARGET._airbyte_extracted_at = SOURCE._airbyte_extracted_at,
  TARGET.campaign_budget_aligned_bidding_strategy_id = SOURCE.campaign_budget_aligned_bidding_strategy_id,
  TARGET.campaign_budget_amount_micros = SOURCE.campaign_budget_amount_micros,
  TARGET.campaign_budget_delivery_method = SOURCE.campaign_budget_delivery_method,
  TARGET.campaign_budget_explicitly_shared = SOURCE.campaign_budget_explicitly_shared,
  TARGET.campaign_budget_has_recommended_budget = SOURCE.campaign_budget_has_recommended_budget,
  TARGET.campaign_budget_id = SOURCE.campaign_budget_id,
  TARGET.campaign_budget_name = SOURCE.campaign_budget_name,
  TARGET.campaign_budget_period = SOURCE.campaign_budget_period,
  TARGET.campaign_budget_recommended_budget_amount_micros = SOURCE.campaign_budget_recommended_budget_amount_micros,
  TARGET.campaign_budget_recommended_budget_estimated_change_weekly_clicks = SOURCE.campaign_budget_recommended_budget_estimated_change_weekly_clicks,
  TARGET.campaign_budget_recommended_budget_estimated_change_weekly_cost_micros = SOURCE.campaign_budget_recommended_budget_estimated_change_weekly_cost_micros,
  TARGET.campaign_budget_recommended_budget_estimated_change_weekly_interactions = SOURCE.campaign_budget_recommended_budget_estimated_change_weekly_interactions,
  TARGET.campaign_budget_recommended_budget_estimated_change_weekly_views = SOURCE.campaign_budget_recommended_budget_estimated_change_weekly_views,
  TARGET.campaign_budget_reference_count = SOURCE.campaign_budget_reference_count,
  TARGET.campaign_budget_resource_name = SOURCE.campaign_budget_resource_name,
  TARGET.campaign_budget_status = SOURCE.campaign_budget_status,
  TARGET.campaign_budget_total_amount_micros = SOURCE.campaign_budget_total_amount_micros,
  TARGET.campaign_budget_type = SOURCE.campaign_budget_type,
  TARGET.campaign_id = SOURCE.campaign_id,
  TARGET.customer_id = SOURCE.customer_id,
  TARGET.metrics_all_conversions = SOURCE.metrics_all_conversions,
  TARGET.metrics_all_conversions_from_interactions_rate = SOURCE.metrics_all_conversions_from_interactions_rate,
  TARGET.metrics_all_conversions_value = SOURCE.metrics_all_conversions_value,
  TARGET.metrics_average_cost = SOURCE.metrics_average_cost,
  TARGET.metrics_average_cpc = SOURCE.metrics_average_cpc,
  TARGET.metrics_average_cpe = SOURCE.metrics_average_cpe,
  TARGET.metrics_average_cpm = SOURCE.metrics_average_cpm,
  TARGET.metrics_average_cpv = SOURCE.metrics_average_cpv,
  TARGET.metrics_clicks = SOURCE.metrics_clicks,
  TARGET.metrics_conversions = SOURCE.metrics_conversions,
  TARGET.metrics_conversions_from_interactions_rate = SOURCE.metrics_conversions_from_interactions_rate,
  TARGET.metrics_conversions_value = SOURCE.metrics_conversions_value,
  TARGET.metrics_cost_micros = SOURCE.metrics_cost_micros,
  TARGET.metrics_cost_per_all_conversions = SOURCE.metrics_cost_per_all_conversions,
  TARGET.metrics_cost_per_conversion = SOURCE.metrics_cost_per_conversion,
  TARGET.metrics_cross_device_conversions = SOURCE.metrics_cross_device_conversions,
  TARGET.metrics_ctr = SOURCE.metrics_ctr,
  TARGET.metrics_engagement_rate = SOURCE.metrics_engagement_rate,
  TARGET.metrics_engagements = SOURCE.metrics_engagements,
  TARGET.metrics_impressions = SOURCE.metrics_impressions,
  TARGET.metrics_interaction_rate = SOURCE.metrics_interaction_rate,
  TARGET.metrics_interactions = SOURCE.metrics_interactions,
  TARGET.metrics_value_per_all_conversions = SOURCE.metrics_value_per_all_conversions,
  TARGET.metrics_value_per_conversion = SOURCE.metrics_value_per_conversion,
  TARGET.metrics_video_view_rate = SOURCE.metrics_video_view_rate,
  TARGET.metrics_video_views = SOURCE.metrics_video_views,
  TARGET.metrics_view_through_conversions = SOURCE.metrics_view_through_conversions,
  TARGET.segments_budget_campaign_association_status_campaign = SOURCE.segments_budget_campaign_association_status_campaign,
  TARGET.segments_budget_campaign_association_status_status = SOURCE.segments_budget_campaign_association_status_status,
  TARGET.InteractionEventType = SOURCE.InteractionEventType
WHEN NOT MATCHED
THEN
INSERT
(
  _airbyte_extracted_at,
  campaign_budget_aligned_bidding_strategy_id,
  campaign_budget_amount_micros,
  campaign_budget_delivery_method,
  campaign_budget_explicitly_shared,
  campaign_budget_has_recommended_budget,
  campaign_budget_id,
  campaign_budget_name,
  campaign_budget_period,
  campaign_budget_recommended_budget_amount_micros,
  campaign_budget_recommended_budget_estimated_change_weekly_clicks,
  campaign_budget_recommended_budget_estimated_change_weekly_cost_micros,
  campaign_budget_recommended_budget_estimated_change_weekly_interactions,
  campaign_budget_recommended_budget_estimated_change_weekly_views,
  campaign_budget_reference_count,
  campaign_budget_resource_name,
  campaign_budget_status,
  campaign_budget_total_amount_micros,
  campaign_budget_type,
  campaign_id,
  customer_id,
  metrics_all_conversions,
  metrics_all_conversions_from_interactions_rate,
  metrics_all_conversions_value,
  metrics_average_cost,
  metrics_average_cpc,
  metrics_average_cpe,
  metrics_average_cpm,
  metrics_average_cpv,
  metrics_clicks,
  metrics_conversions,
  metrics_conversions_from_interactions_rate,
  metrics_conversions_value,
  metrics_cost_micros,
  metrics_cost_per_all_conversions,
  metrics_cost_per_conversion,
  metrics_cross_device_conversions,
  metrics_ctr,
  metrics_engagement_rate,
  metrics_engagements,
  metrics_impressions,
  metrics_interaction_rate,
  metrics_interactions,
  metrics_value_per_all_conversions,
  metrics_value_per_conversion,
  metrics_video_view_rate,
  metrics_video_views,
  metrics_view_through_conversions,
  segments_budget_campaign_association_status_campaign,
  segments_budget_campaign_association_status_status,
  InteractionEventType
)
VALUES
(
  SOURCE._airbyte_extracted_at,
  SOURCE.campaign_budget_aligned_bidding_strategy_id,
  SOURCE.campaign_budget_amount_micros,
  SOURCE.campaign_budget_delivery_method,
  SOURCE.campaign_budget_explicitly_shared,
  SOURCE.campaign_budget_has_recommended_budget,
  SOURCE.campaign_budget_id,
  SOURCE.campaign_budget_name,
  SOURCE.campaign_budget_period,
  SOURCE.campaign_budget_recommended_budget_amount_micros,
  SOURCE.campaign_budget_recommended_budget_estimated_change_weekly_clicks,
  SOURCE.campaign_budget_recommended_budget_estimated_change_weekly_cost_micros,
  SOURCE.campaign_budget_recommended_budget_estimated_change_weekly_interactions,
  SOURCE.campaign_budget_recommended_budget_estimated_change_weekly_views,
  SOURCE.campaign_budget_reference_count,
  SOURCE.campaign_budget_resource_name,
  SOURCE.campaign_budget_status,
  SOURCE.campaign_budget_total_amount_micros,
  SOURCE.campaign_budget_type,
  SOURCE.campaign_id,
  SOURCE.customer_id,
  SOURCE.metrics_all_conversions,
  SOURCE.metrics_all_conversions_from_interactions_rate,
  SOURCE.metrics_all_conversions_value,
  SOURCE.metrics_average_cost,
  SOURCE.metrics_average_cpc,
  SOURCE.metrics_average_cpe,
  SOURCE.metrics_average_cpm,
  SOURCE.metrics_average_cpv,
  SOURCE.metrics_clicks,
  SOURCE.metrics_conversions,
  SOURCE.metrics_conversions_from_interactions_rate,
  SOURCE.metrics_conversions_value,
  SOURCE.metrics_cost_micros,
  SOURCE.metrics_cost_per_all_conversions,
  SOURCE.metrics_cost_per_conversion,
  SOURCE.metrics_cross_device_conversions,
  SOURCE.metrics_ctr,
  SOURCE.metrics_engagement_rate,
  SOURCE.metrics_engagements,
  SOURCE.metrics_impressions,
  SOURCE.metrics_interaction_rate,
  SOURCE.metrics_interactions,
  SOURCE.metrics_value_per_all_conversions,
  SOURCE.metrics_value_per_conversion,
  SOURCE.metrics_video_view_rate,
  SOURCE.metrics_video_views,
  SOURCE.metrics_view_through_conversions,
  SOURCE.segments_budget_campaign_association_status_campaign,
  SOURCE.segments_budget_campaign_association_status_status,
  SOURCE.InteractionEventType
)
