merge into `shopify-pubsub-project.Data_Warehouse_Facebook_Ads_Staging.ad_creatives` as target
using
(
SELECT
_airbyte_extracted_at,
id,
body,
name,
title,
status,
actor_id,
adlabels,
link_url,
url_tags,
video_id,
image_url,
object_id,
account_id,
image_hash,
link_og_id,
object_url,
image_crops,
object_type,
template_url,
thumbnail_url,
product_set_id,
asset_feed_spec,
object_story_id,
applink_treatment,
object_story_spec,
template_url_spec,
instagram_actor_id,
instagram_story_id,
thumbnail_data_url,
call_to_action_type,
instagram_permalink_url,
effective_object_story_id,
source_instagram_media_id,
effective_instagram_story_id,
FROM
(
select
*,
row_number() over(partition by id order by _airbyte_extracted_at desc) as rn
from `shopify-pubsub-project.pilgrim_bi_airbyte_facebook.ad_creatives`
)
where rn = 1 and date(_airbyte_extracted_at) >= date_sub(current_date("Asia/Kolkata"), INTERVAL 10 day)
) as source
on target.id = source.id
when matched and target._airbyte_extracted_at < source._airbyte_extracted_at
then update set
target._airbyte_extracted_at = source._airbyte_extracted_at,
target.id = source.id,
target.body = source.body,
target.name = source.name,
target.title = source.title,
target.status = source.status,
target.actor_id = source.actor_id,
target.adlabels = source.adlabels,
target.link_url = source.link_url,
target.url_tags = source.url_tags,
target.video_id = source.video_id,
target.image_url = source.image_url,
target.object_id = source.object_id,
target.account_id = source.account_id,
target.image_hash = source.image_hash,
target.link_og_id = source.link_og_id,
target.object_url = source.object_url,
target.image_crops = source.image_crops,
target.object_type = source.object_type,
target.template_url = source.template_url,
target.thumbnail_url = source.thumbnail_url,
target.product_set_id = source.product_set_id,
target.asset_feed_spec = source.asset_feed_spec,
target.object_story_id = source.object_story_id,
target.applink_treatment = source.applink_treatment,
target.object_story_spec = source.object_story_spec,
target.template_url_spec = source.template_url_spec,
target.instagram_actor_id = source.instagram_actor_id,
target.instagram_story_id = source.instagram_story_id,
target.thumbnail_data_url = source.thumbnail_data_url,
target.call_to_action_type = source.call_to_action_type,
target.instagram_permalink_url = source.instagram_permalink_url,
target.effective_object_story_id = source.effective_object_story_id,
target.source_instagram_media_id = source.source_instagram_media_id,
target.effective_instagram_story_id = source.effective_instagram_story_id
when not matched
then insert
(
_airbyte_extracted_at,
id,
body,
name,
title,
status,
actor_id,
adlabels,
link_url,
url_tags,
video_id,
image_url,
object_id,
account_id,
image_hash,
link_og_id,
object_url,
image_crops,
object_type,
template_url,
thumbnail_url,
product_set_id,
asset_feed_spec,
object_story_id,
applink_treatment,
object_story_spec,
template_url_spec,
instagram_actor_id,
instagram_story_id,
thumbnail_data_url,
call_to_action_type,
instagram_permalink_url,
effective_object_story_id,
source_instagram_media_id,
effective_instagram_story_id
)
values
(
source._airbyte_extracted_at,
source.id,
source.body,
source.name,
source.title,
source.status,
source.actor_id,
source.adlabels,
source.link_url,
source.url_tags,
source.video_id,
source.image_url,
source.object_id,
source.account_id,
source.image_hash,
source.link_og_id,
source.object_url,
source.image_crops,
source.object_type,
source.template_url,
source.thumbnail_url,
source.product_set_id,
source.asset_feed_spec,
source.object_story_id,
source.applink_treatment,
source.object_story_spec,
source.template_url_spec,
source.instagram_actor_id,
source.instagram_story_id,
source.thumbnail_data_url,
source.call_to_action_type,
source.instagram_permalink_url,
source.effective_object_story_id,
source.source_instagram_media_id,
source.effective_instagram_story_id
)
