CREATE OR REPLACE TABLE `shopify-pubsub-project.Data_Warehouse_GoogleAds_Staging.campaign`
PARTITION BY DATE_TRUNC(_airbyte_extracted_at, DAY)
AS
SELECT
_airbyte_extracted_at,
campaign_dynamic_search_ads_setting_use_supplied_urls_only,
campaign_manual_cpc_enhanced_cpc_enabled,
campaign_network_settings_target_content_network,
campaign_network_settings_target_google_search,
campaign_network_settings_target_partner_search_network,
campaign_network_settings_target_search_network,
campaign_percent_cpc_enhanced_cpc_enabled,
campaign_real_time_bidding_setting_opt_in,
campaign_shopping_setting_enable_local,
segments_date,
campaign_budget_amount_micros,
campaign_commission_commission_rate_micros,
campaign_hotel_setting_hotel_center_id,
campaign_id,
campaign_maximize_conversions_target_cpa_micros,
campaign_percent_cpc_cpc_bid_ceiling_micros,
campaign_shopping_setting_campaign_priority,
campaign_shopping_setting_merchant_id,
campaign_target_cpa_cpc_bid_ceiling_micros,
campaign_target_cpa_cpc_bid_floor_micros,
campaign_target_cpa_target_cpa_micros,
campaign_target_cpm_target_frequency_goal_target_count,
campaign_target_impression_share_cpc_bid_ceiling_micros,
campaign_target_impression_share_location_fraction_micros,
campaign_target_roas_cpc_bid_ceiling_micros,
campaign_target_roas_cpc_bid_floor_micros,
campaign_target_spend_cpc_bid_ceiling_micros,
campaign_target_spend_target_spend_micros,
metrics_active_view_impressions,
metrics_active_view_measurable_cost_micros,
metrics_active_view_measurable_impressions,
metrics_clicks,
metrics_cost_micros,
metrics_impressions,
metrics_interactions,
metrics_video_views,
segments_hour,
campaign_maximize_conversion_value_target_roas,
campaign_optimization_score,
campaign_target_roas_target_roas,
metrics_active_view_cpm,
metrics_active_view_ctr,
metrics_active_view_measurability,
metrics_active_view_viewability,
metrics_average_cost,
metrics_average_cpc,
metrics_average_cpm,
metrics_conversions,
metrics_conversions_value,
metrics_cost_per_conversion,
metrics_ctr,
metrics_value_per_conversion,
metrics_video_quartile_p100_rate,
campaign_ad_serving_optimization_status,
campaign_advertising_channel_sub_type,
campaign_advertising_channel_type,
campaign_app_campaign_setting_app_id,
campaign_app_campaign_setting_app_store,
campaign_app_campaign_setting_bidding_strategy_goal_type,
campaign_base_campaign,
campaign_bidding_strategy_type,
campaign_campaign_budget,
campaign_end_date,
campaign_experiment_type,
campaign_geo_target_type_setting_negative_geo_target_type,
campaign_geo_target_type_setting_positive_geo_target_type,
campaign_local_campaign_setting_location_source_type,
campaign_name,
campaign_payment_mode,
campaign_resource_name,
campaign_serving_status,
campaign_start_date,
campaign_status,
campaign_target_impression_share_location,
campaign_tracking_url_template,
campaign_vanity_pharma_vanity_pharma_display_url_mode,
campaign_vanity_pharma_vanity_pharma_text,
campaign_video_brand_safety_suitability,
segments_ad_network_type,
-- -- Extract 'level' value
-- REGEXP_EXTRACT(JSON_EXTRACT_SCALAR(value, '$'), r'level:\s*(\w+)') AS campaign_frequency_cap_level,
-- -- Extract 'event_type' value
-- REGEXP_EXTRACT(JSON_EXTRACT_SCALAR(value, '$'), r'event_type:\s*(\w+)') AS campaign_frequency_cap_event_type,
-- -- Extract 'time_unit' value
-- REGEXP_EXTRACT(JSON_EXTRACT_SCALAR(value, '$'), r'time_unit:\s*(\w+)') AS campaign_frequency_cap_time_unit,
-- -- Extract 'time_length' value
-- REGEXP_EXTRACT(JSON_EXTRACT_SCALAR(value, '$'), r'time_length:\s*(\d+)') AS campaign_frequency_cap_time_length,
-- -- Extract 'cap' value
-- REGEXP_EXTRACT(JSON_EXTRACT_SCALAR(value, '$'), r'cap:\s*(\d+)') AS campaign_frequency_cap_value,
-- Extract campaign label from campaign_label
REGEXP_EXTRACT(JSON_EXTRACT_SCALAR(campaign_labels, '$[0]'),r'customers/\d+/labels/\d+') AS campaign_label,
-- Extract conversion_actions from JSON array campaign_selective_optimization_conversion_actions
JSON_EXTRACT_SCALAR(campaign_selective_optimization_conversion_actions, '$[0]') as campaign_selection_optimization_conv_action,
-- Extract value for dimension from JSON array campaign_targeting_setting_target_restrictions
REGEXP_EXTRACT(JSON_EXTRACT_SCALAR(campaign_targeting_setting_target_restrictions, '$[0]'),r'targeting_dimension:\s*(\w+)') AS campaign_targeting_dimension,
-- Extract value for bid_only from JSON array campaign_targeting_setting_target_restrictions
REGEXP_EXTRACT(JSON_EXTRACT_SCALAR(campaign_targeting_setting_target_restrictions, '$[0]'),r'bid_only:\s*(\w+)') AS campaign_targetting_bid_only,
FROM
  shopify-pubsub-project.pilgrim_bi_google_ads.campaign
