
MERGE INTO `shopify-pubsub-project.Data_Warehouse_Amazon_Seller_Staging.Orders` AS target  
USING (
SELECT 
distinct
_airbyte_extracted_at,
IsISPU,
IsPrime,
JSON_EXTRACT_SCALAR(BuyerInfo, '$.BuyerEmail') AS Buyer_Email,
OrderType,
seller_id,
IsSoldByAB,
JSON_EXTRACT_SCALAR(OrderTotal, '$.Amount') as Order_Amount,
OrderStatus as Order_status,
PurchaseDate as Purchase_date,
SalesChannel,
AmazonOrderId as Amazon_Order_id,
MarketplaceId as Marketplace_id,
PaymentMethod as Payment_type,
SellerOrderId,
IsPremiumOrder,
LastUpdateDate as Order_last_updated_date,
LatestShipDate,
IsBusinessOrder,
JSON_EXTRACT_SCALAR(ShippingAddress, '$.City') as Shipping_City,
JSON_EXTRACT_SCALAR(ShippingAddress,'$.StateOrRegion') as Shipping_State,
JSON_EXTRACT_SCALAR(ShippingAddress,'$.PostalCode') as Shipping_Pincode,

EarliestShipDate,
ShipServiceLevel,
HasRegulatedItems,
FulfillmentChannel,
IsAccessPointOrder,
IsReplacementOrder,
LatestDeliveryDate,
EarliestDeliveryDate,
NumberOfItemsShipped,
JSON_EXTRACT_STRING_ARRAY(PaymentMethodDetails) as Payment_method,
IsGlobalExpressEnabled,
NumberOfItemsUnshipped,
json_extract_scalar(AutomatedShippingSettings,'$.HasAutomatedShippingSettings') as Has_automated_shipping,
ShipmentServiceLevelCategory,
Concat(
JSON_EXTRACT_SCALAR(DefaultShipFromLocationAddress, '$.AddressLine1'), ", ",
JSON_EXTRACT_SCALAR(DefaultShipFromLocationAddress,'$.AddressLine2') 
)as Ship_From_Address,
JSON_EXTRACT_SCALAR(DefaultShipFromLocationAddress,'$.City') as Ship_From_City,
JSON_EXTRACT_SCALAR(DefaultShipFromLocationAddress,'$.Name') as Ship_From_Name,
JSON_EXTRACT_SCALAR(DefaultShipFromLocationAddress,'$.PostalCode') as Ship_From_Pincode,
JSON_EXTRACT_SCALAR(DefaultShipFromLocationAddress,'$.StateOrRegion') as Ship_From_State

from `shopify-pubsub-project.pilgrim_bi_airbyte_amazon_seller.Orders`


WHERE DATE(_airbyte_extracted_at) >= DATE_SUB(CURRENT_DATE("Asia/Kolkata"), INTERVAL 10 DAY)
) AS source

ON target.Amazon_Order_id = source.Amazon_Order_id

WHEN MATCHED AND source._airbyte_extracted_at > target._airbyte_extracted_at 
THEN UPDATE SET
  
target._airbyte_extracted_at = source._airbyte_extracted_at,
target.IsISPU= source.IsISPU,
target.IsPrime= source.IsPrime,
target.Buyer_Email= source.Buyer_Email,
target.OrderType= source.OrderType,
target.seller_id= source.seller_id,
target.IsSoldByAB= source.IsSoldByAB,
target.Order_Amount= source.Order_Amount,
target.Order_status= source.Order_status,
target.Purchase_date= source.Purchase_date,
target.SalesChannel= source.SalesChannel,
target.Amazon_Order_id= source.Amazon_Order_id,
target.Marketplace_id= source.Marketplace_id,
target.Payment_type= source.Payment_type,
target.SellerOrderId= source.SellerOrderId,
target.IsPremiumOrder= source.IsPremiumOrder,
target.Order_last_updated_date= source.Order_last_updated_date,
target.LatestShipDate= source.LatestShipDate,
target.IsBusinessOrder= source.IsBusinessOrder,
target.Shipping_City= source.Shipping_City,
target.Shipping_State= source.Shipping_State,
target.Shipping_Pincode= source.Shipping_Pincode,
target.EarliestShipDate= source.EarliestShipDate,
target.ShipServiceLevel= source.ShipServiceLevel,
target.HasRegulatedItems= source.HasRegulatedItems,
target.FulfillmentChannel= source.FulfillmentChannel,
target.IsAccessPointOrder= source.IsAccessPointOrder,
target.IsReplacementOrder= source.IsReplacementOrder,
target.LatestDeliveryDate= source.LatestDeliveryDate,
target.EarliestDeliveryDate= source.EarliestDeliveryDate,
target.NumberOfItemsShipped= source.NumberOfItemsShipped,
target.Payment_method= source.Payment_method,
target.IsGlobalExpressEnabled= source.IsGlobalExpressEnabled,
target.NumberOfItemsUnshipped= source.NumberOfItemsUnshipped,
target.Has_automated_shipping= source.Has_automated_shipping,
target.ShipmentServiceLevelCategory= source.ShipmentServiceLevelCategory,
target.Ship_From_Address= source.Ship_From_Address,
target.Ship_From_City= source.Ship_From_City,
target.Ship_From_Name= source.Ship_From_Name,
target.Ship_From_Pincode= source.Ship_From_Pincode,
target.Ship_From_State= source.Ship_From_State



WHEN NOT MATCHED THEN INSERT (
_airbyte_extracted_at,
IsISPU,
IsPrime,
Buyer_Email,
OrderType,
seller_id,
IsSoldByAB,
Order_Amount,
Order_status,
Purchase_date,
SalesChannel,
Amazon_Order_id,
Marketplace_id,
Payment_type,
SellerOrderId,
IsPremiumOrder,
Order_last_updated_date,
LatestShipDate,
IsBusinessOrder,
Shipping_City,
Shipping_State,
Shipping_Pincode,
EarliestShipDate,
ShipServiceLevel,
HasRegulatedItems,
FulfillmentChannel,
IsAccessPointOrder,
IsReplacementOrder,
LatestDeliveryDate,
EarliestDeliveryDate,
NumberOfItemsShipped,
Payment_method,
IsGlobalExpressEnabled,
NumberOfItemsUnshipped,
Has_automated_shipping,
ShipmentServiceLevelCategory,
Ship_From_Address,
Ship_From_City,
Ship_From_Name,
Ship_From_Pincode,
Ship_From_State
    
  )
  VALUES (
source._airbyte_extracted_at,
source.IsISPU,
source.IsPrime,
source.Buyer_Email,
source.OrderType,
source.seller_id,
source.IsSoldByAB,
source.Order_Amount,
source.Order_status,
source.Purchase_date,
source.SalesChannel,
source.Amazon_Order_id,
source.Marketplace_id,
source.Payment_type,
source.SellerOrderId,
source.IsPremiumOrder,
source.Order_last_updated_date,
source.LatestShipDate,
source.IsBusinessOrder,
source.Shipping_City,
source.Shipping_State,
source.Shipping_Pincode,
source.EarliestShipDate,
source.ShipServiceLevel,
source.HasRegulatedItems,
source.FulfillmentChannel,
source.IsAccessPointOrder,
source.IsReplacementOrder,
source.LatestDeliveryDate,
source.EarliestDeliveryDate,
source.NumberOfItemsShipped,
source.Payment_method,
source.IsGlobalExpressEnabled,
source.NumberOfItemsUnshipped,
source.Has_automated_shipping,
source.ShipmentServiceLevelCategory,
source.Ship_From_Address,
source.Ship_From_City,
source.Ship_From_Name,
source.Ship_From_Pincode,
source.Ship_From_State

  )
