MERGE INTO `shopify-pubsub-project.Data_Warehouse_GoogleAds_Staging.display_keyword_view` AS TARGET
USING
(
select
_airbyte_extracted_at,
ad_group_base_ad_group,
ad_group_criterion_criterion_id,
ad_group_criterion_effective_cpc_bid_micros,
ad_group_criterion_effective_cpc_bid_source,
ad_group_criterion_effective_cpm_bid_micros,
ad_group_criterion_effective_cpm_bid_source,
ad_group_criterion_effective_cpv_bid_micros,
ad_group_criterion_effective_cpv_bid_source,
ad_group_criterion_final_mobile_urls,
ad_group_criterion_final_urls,
ad_group_criterion_keyword_match_type,
ad_group_criterion_keyword_text,
ad_group_criterion_negative,
ad_group_criterion_status,
ad_group_criterion_tracking_url_template,
ad_group_criterion_url_custom_parameters,
ad_group_id,
ad_group_name,
ad_group_status,
campaign_base_campaign,
campaign_bidding_strategy,
campaign_bidding_strategy_type,
campaign_id,
campaign_name,
campaign_status,
customer_currency_code,
customer_descriptive_name,
customer_id,
customer_time_zone,
metrics_active_view_cpm,
metrics_active_view_ctr,
metrics_active_view_impressions,
metrics_active_view_measurability,
metrics_active_view_measurable_cost_micros,
metrics_active_view_measurable_impressions,
metrics_active_view_viewability,
metrics_all_conversions,
metrics_all_conversions_from_interactions_rate,
metrics_all_conversions_value,
metrics_average_cost,
metrics_average_cpc,
metrics_average_cpe,
metrics_average_cpm,
metrics_average_cpv,
metrics_clicks,
metrics_conversions,
metrics_conversions_from_interactions_rate,
metrics_conversions_value,
metrics_cost_micros,
metrics_cost_per_all_conversions,
metrics_cost_per_conversion,
metrics_cross_device_conversions,
metrics_ctr,
metrics_engagement_rate,
metrics_engagements,
metrics_gmail_forwards,
metrics_gmail_saves,
metrics_gmail_secondary_clicks,
metrics_impressions,
metrics_interaction_rate,
metrics_interactions,
metrics_value_per_all_conversions,
metrics_value_per_conversion,
metrics_video_quartile_p100_rate,
metrics_video_quartile_p25_rate,
metrics_video_quartile_p50_rate,
metrics_video_quartile_p75_rate,
metrics_video_view_rate,
metrics_video_views,
metrics_view_through_conversions,
segments_ad_network_type,
segments_date,
segments_day_of_week,
segments_device,
segments_month,
segments_quarter,
segments_week,
segments_year,
-- interaction_event_type,
-- target_setting_target_restriction,
JSON_extract_array(metrics_interaction_event_types,'$') as interaction_event_type,
JSON_EXTRACT_ARRAY(ad_group_targeting_setting_target_restrictions, '$') as target_setting_target_restriction,
from
(
SELECT
  *,
  -- JSON_extract_array(metrics_interaction_event_types,'$') as interaction_event_type,
  -- JSON_EXTRACT_ARRAY(ad_group_targeting_setting_target_restrictions, '$') as target_setting_target_restriction,
  ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY _airbyte_extracted_at DESC) AS row_num
FROM
  shopify-pubsub-project.pilgrim_bi_google_ads.display_keyword_view
where
DATE(_airbyte_extracted_at) >= DATE_SUB(CURRENT_DATE("Asia/Kolkata"), INTERVAL 10 DAY)
)
WHERE row_num = 1
)
AS SOURCE
on target.customer_id = source.customer_id
WHEN MATCHED AND source._airbyte_extracted_at > target._airbyte_extracted_at
then update set
target._airbyte_extracted_at = source._airbyte_extracted_at,
target.ad_group_base_ad_group = source.ad_group_base_ad_group,
target.ad_group_criterion_criterion_id = source.ad_group_criterion_criterion_id,
target.ad_group_criterion_effective_cpc_bid_micros = source.ad_group_criterion_effective_cpc_bid_micros,
target.ad_group_criterion_effective_cpc_bid_source = source.ad_group_criterion_effective_cpc_bid_source,
target.ad_group_criterion_effective_cpm_bid_micros = source.ad_group_criterion_effective_cpm_bid_micros,
target.ad_group_criterion_effective_cpm_bid_source = source.ad_group_criterion_effective_cpm_bid_source,
target.ad_group_criterion_effective_cpv_bid_micros = source.ad_group_criterion_effective_cpv_bid_micros,
target.ad_group_criterion_effective_cpv_bid_source = source.ad_group_criterion_effective_cpv_bid_source,
target.ad_group_criterion_final_mobile_urls = source.ad_group_criterion_final_mobile_urls,
target.ad_group_criterion_final_urls = source.ad_group_criterion_final_urls,
target.ad_group_criterion_keyword_match_type = source.ad_group_criterion_keyword_match_type,
target.ad_group_criterion_keyword_text = source.ad_group_criterion_keyword_text,
target.ad_group_criterion_negative = source.ad_group_criterion_negative,
target.ad_group_criterion_status = source.ad_group_criterion_status,
target.ad_group_criterion_tracking_url_template = source.ad_group_criterion_tracking_url_template,
target.ad_group_criterion_url_custom_parameters = source.ad_group_criterion_url_custom_parameters,
target.ad_group_id = source.ad_group_id,
target.ad_group_name = source.ad_group_name,
target.ad_group_status = source.ad_group_status,
target.campaign_base_campaign = source.campaign_base_campaign,
target.campaign_bidding_strategy = source.campaign_bidding_strategy,
target.campaign_bidding_strategy_type = source.campaign_bidding_strategy_type,
target.campaign_id = source.campaign_id,
target.campaign_name = source.campaign_name,
target.campaign_status = source.campaign_status,
target.customer_currency_code = source.customer_currency_code,
target.customer_descriptive_name = source.customer_descriptive_name,
target.customer_id = source.customer_id,
target.customer_time_zone = source.customer_time_zone,
target.metrics_active_view_cpm = source.metrics_active_view_cpm,
target.metrics_active_view_ctr = source.metrics_active_view_ctr,
target.metrics_active_view_impressions = source.metrics_active_view_impressions,
target.metrics_active_view_measurability = source.metrics_active_view_measurability,
target.metrics_active_view_measurable_cost_micros = source.metrics_active_view_measurable_cost_micros,
target.metrics_active_view_measurable_impressions = source.metrics_active_view_measurable_impressions,
target.metrics_active_view_viewability = source.metrics_active_view_viewability,
target.metrics_all_conversions = source.metrics_all_conversions,
target.metrics_all_conversions_from_interactions_rate = source.metrics_all_conversions_from_interactions_rate,
target.metrics_all_conversions_value = source.metrics_all_conversions_value,
target.metrics_average_cost = source.metrics_average_cost,
target.metrics_average_cpc = source.metrics_average_cpc,
target.metrics_average_cpe = source.metrics_average_cpe,
target.metrics_average_cpm = source.metrics_average_cpm,
target.metrics_average_cpv = source.metrics_average_cpv,
target.metrics_clicks = source.metrics_clicks,
target.metrics_conversions = source.metrics_conversions,
target.metrics_conversions_from_interactions_rate = source.metrics_conversions_from_interactions_rate,
target.metrics_conversions_value = source.metrics_conversions_value,
target.metrics_cost_micros = source.metrics_cost_micros,
target.metrics_cost_per_all_conversions = source.metrics_cost_per_all_conversions,
target.metrics_cost_per_conversion = source.metrics_cost_per_conversion,
target.metrics_cross_device_conversions = source.metrics_cross_device_conversions,
target.metrics_ctr = source.metrics_ctr,
target.metrics_engagement_rate = source.metrics_engagement_rate,
target.metrics_engagements = source.metrics_engagements,
target.metrics_gmail_forwards = source.metrics_gmail_forwards,
target.metrics_gmail_saves = source.metrics_gmail_saves,
target.metrics_gmail_secondary_clicks = source.metrics_gmail_secondary_clicks,
target.metrics_impressions = source.metrics_impressions,
target.metrics_interaction_rate = source.metrics_interaction_rate,
target.metrics_interactions = source.metrics_interactions,
target.metrics_value_per_all_conversions = source.metrics_value_per_all_conversions,
target.metrics_value_per_conversion = source.metrics_value_per_conversion,
target.metrics_video_quartile_p100_rate = source.metrics_video_quartile_p100_rate,
target.metrics_video_quartile_p25_rate = source.metrics_video_quartile_p25_rate,
target.metrics_video_quartile_p50_rate = source.metrics_video_quartile_p50_rate,
target.metrics_video_quartile_p75_rate = source.metrics_video_quartile_p75_rate,
target.metrics_video_view_rate = source.metrics_video_view_rate,
target.metrics_video_views = source.metrics_video_views,
target.metrics_view_through_conversions = source.metrics_view_through_conversions,
target.segments_ad_network_type = source.segments_ad_network_type,
target.segments_date = source.segments_date,
target.segments_day_of_week = source.segments_day_of_week,
target.segments_device = source.segments_device,
target.segments_month = source.segments_month,
target.segments_quarter = source.segments_quarter,
target.segments_week = source.segments_week,
target.segments_year = source.segments_year,
target.interaction_event_type = source.interaction_event_type,
target.target_setting_target_restriction = source.target_setting_target_restriction
when not matched
then insert
(
  _airbyte_extracted_at,
  ad_group_base_ad_group,
  ad_group_criterion_criterion_id,
  ad_group_criterion_effective_cpc_bid_micros,
  ad_group_criterion_effective_cpc_bid_source,
  ad_group_criterion_effective_cpm_bid_micros,
  ad_group_criterion_effective_cpm_bid_source,
  ad_group_criterion_effective_cpv_bid_micros,
  ad_group_criterion_effective_cpv_bid_source,
  ad_group_criterion_final_mobile_urls,
  ad_group_criterion_final_urls,
  ad_group_criterion_keyword_match_type,
  ad_group_criterion_keyword_text,
  ad_group_criterion_negative,
  ad_group_criterion_status,
  ad_group_criterion_tracking_url_template,
  ad_group_criterion_url_custom_parameters,
  ad_group_id,
  ad_group_name,
  ad_group_status,
  campaign_base_campaign,
  campaign_bidding_strategy,
  campaign_bidding_strategy_type,
  campaign_id,
  campaign_name,
  campaign_status,
  customer_currency_code,
  customer_descriptive_name,
  customer_id,
  customer_time_zone,
  metrics_active_view_cpm,
  metrics_active_view_ctr,
  metrics_active_view_impressions,
  metrics_active_view_measurability,
  metrics_active_view_measurable_cost_micros,
  metrics_active_view_measurable_impressions,
  metrics_active_view_viewability,
  metrics_all_conversions,
  metrics_all_conversions_from_interactions_rate,
  metrics_all_conversions_value,
  metrics_average_cost,
  metrics_average_cpc,
  metrics_average_cpe,
  metrics_average_cpm,
  metrics_average_cpv,
  metrics_clicks,
  metrics_conversions,
  metrics_conversions_from_interactions_rate,
  metrics_conversions_value,
  metrics_cost_micros,
  metrics_cost_per_all_conversions,
  metrics_cost_per_conversion,
  metrics_cross_device_conversions,
  metrics_ctr,
  metrics_engagement_rate,
  metrics_engagements,
  metrics_gmail_forwards,
  metrics_gmail_saves,
  metrics_gmail_secondary_clicks,
  metrics_impressions,
  metrics_interaction_rate,
  metrics_interactions,
  metrics_value_per_all_conversions,
  metrics_value_per_conversion,
  metrics_video_quartile_p100_rate,
  metrics_video_quartile_p25_rate,
  metrics_video_quartile_p50_rate,
  metrics_video_quartile_p75_rate,
  metrics_video_view_rate,
  metrics_video_views,
  metrics_view_through_conversions,
  segments_ad_network_type,
  segments_date,
  segments_day_of_week,
  segments_device,
  segments_month,
  segments_quarter,
  segments_week,
  segments_year,
  interaction_event_type,
  target_setting_target_restriction
)
values
(
source._airbyte_extracted_at,
source.ad_group_base_ad_group,
source.ad_group_criterion_criterion_id,
source.ad_group_criterion_effective_cpc_bid_micros,
source.ad_group_criterion_effective_cpc_bid_source,
source.ad_group_criterion_effective_cpm_bid_micros,
source.ad_group_criterion_effective_cpm_bid_source,
source.ad_group_criterion_effective_cpv_bid_micros,
source.ad_group_criterion_effective_cpv_bid_source,
source.ad_group_criterion_final_mobile_urls,
source.ad_group_criterion_final_urls,
source.ad_group_criterion_keyword_match_type,
source.ad_group_criterion_keyword_text,
source.ad_group_criterion_negative,
source.ad_group_criterion_status,
source.ad_group_criterion_tracking_url_template,
source.ad_group_criterion_url_custom_parameters,
source.ad_group_id,
source.ad_group_name,
source.ad_group_status,
source.campaign_base_campaign,
source.campaign_bidding_strategy,
source.campaign_bidding_strategy_type,
source.campaign_id,
source.campaign_name,
source.campaign_status,
source.customer_currency_code,
source.customer_descriptive_name,
source.customer_id,
source.customer_time_zone,
source.metrics_active_view_cpm,
source.metrics_active_view_ctr,
source.metrics_active_view_impressions,
source.metrics_active_view_measurability,
source.metrics_active_view_measurable_cost_micros,
source.metrics_active_view_measurable_impressions,
source.metrics_active_view_viewability,
source.metrics_all_conversions,
source.metrics_all_conversions_from_interactions_rate,
source.metrics_all_conversions_value,
source.metrics_average_cost,
source.metrics_average_cpc,
source.metrics_average_cpe,
source.metrics_average_cpm,
source.metrics_average_cpv,
source.metrics_clicks,
source.metrics_conversions,
source.metrics_conversions_from_interactions_rate,
source.metrics_conversions_value,
source.metrics_cost_micros,
source.metrics_cost_per_all_conversions,
source.metrics_cost_per_conversion,
source.metrics_cross_device_conversions,
source.metrics_ctr,
source.metrics_engagement_rate,
source.metrics_engagements,
source.metrics_gmail_forwards,
source.metrics_gmail_saves,
source.metrics_gmail_secondary_clicks,
source.metrics_impressions,
source.metrics_interaction_rate,
source.metrics_interactions,
source.metrics_value_per_all_conversions,
source.metrics_value_per_conversion,
source.metrics_video_quartile_p100_rate,
source.metrics_video_quartile_p25_rate,
source.metrics_video_quartile_p50_rate,
source.metrics_video_quartile_p75_rate,
source.metrics_video_view_rate,
source.metrics_video_views,
source.metrics_view_through_conversions,
source.segments_ad_network_type,
source.segments_date,
source.segments_day_of_week,
source.segments_device,
source.segments_month,
source.segments_quarter,
source.segments_week,
source.segments_year,
source.interaction_event_type,
source.target_setting_target_restriction
);
