CREATE OR REPLACE TABLE `shopify-pubsub-project.Data_Warehouse_Amazon_ads.brands_video_report_stream` 
PARTITION BY DATE_TRUNC(_airbyte_extracted_at, DAY)
AS 
SELECT 
_airbyte_extracted_at, 
recordId, 
profileId, 
recordType, 
reportDate, 
JSON_EXTRACT_SCALAR(metric, '$.adGroupId') AS adGroupId, 
JSON_EXTRACT_SCALAR(metric, '$.adGroupName') AS adGroupName,
JSON_EXTRACT_SCALAR(metric, '$.attributedBrandedSearches14d') AS attributedBrandedSearches14d,
JSON_EXTRACT_SCALAR(metric, '$.attributedConversions14d') AS attributedConversions14d,
JSON_EXTRACT_SCALAR(metric, '$.attributedConversions14dSameSKU') AS attributedConversions14dSameSKU,
JSON_EXTRACT_SCALAR(metric, '$.attributedDetailPageViewsClicks14d') AS attributedDetailPageViewsClicks14d,
JSON_EXTRACT_SCALAR(metric, '$.attributedOrderRateNewToBrand14d') AS attributedOrderRateNewToBrand14d,
JSON_EXTRACT_SCALAR(metric, '$.attributedOrdersNewToBrand14d') AS attributedOrdersNewToBrand14d,
JSON_EXTRACT_SCALAR(metric, '$.attributedOrdersNewToBrandPercentage14d') AS attributedOrdersNewToBrandPercentage14d,
JSON_EXTRACT_SCALAR(metric, '$.attributedSales14d') AS attributedSales14d,
JSON_EXTRACT_SCALAR(metric, '$.attributedSales14dSameSKU') AS attributedSales14dSameSKU,
JSON_EXTRACT_SCALAR(metric, '$.attributedSalesNewToBrand14d') AS attributedSalesNewToBrand14d,
JSON_EXTRACT_SCALAR(metric, '$.attributedSalesNewToBrandPercentage14d') AS attributedSalesNewToBrandPercentage14d,
JSON_EXTRACT_SCALAR(metric, '$.attributedUnitsOrderedNewToBrand14d') AS attributedUnitsOrderedNewToBrand14d,
JSON_EXTRACT_SCALAR(metric, '$.attributedUnitsOrderedNewToBrandPercentage14d') AS attributedUnitsOrderedNewToBrandPercentage14d,
JSON_EXTRACT_SCALAR(metric, '$.campaignBudget') AS campaignBudget,
JSON_EXTRACT_SCALAR(metric, '$.campaignBudgetType') AS campaignBudgetType,
JSON_EXTRACT_SCALAR(metric, '$.campaignId') AS campaignId,
JSON_EXTRACT_SCALAR(metric, '$.campaignName') AS campaignName,
JSON_EXTRACT_SCALAR(metric, '$.campaignStatus') AS campaignStatus,
JSON_EXTRACT_SCALAR(metric, '$.clicks') AS clicks,
JSON_EXTRACT_SCALAR(metric, '$.cost') AS cost,
JSON_EXTRACT_SCALAR(metric, '$.dpv14d') AS dpv14d,
JSON_EXTRACT_SCALAR(metric, '$.impressions') AS impressions,
JSON_EXTRACT_SCALAR(metric, '$.keywordBid') AS keywordBid,
JSON_EXTRACT_SCALAR(metric, '$.keywordId') AS keywordId,
JSON_EXTRACT_SCALAR(metric, '$.keywordStatus') AS keywordStatus,
JSON_EXTRACT_SCALAR(metric, '$.keywordText') AS keywordText,
JSON_EXTRACT_SCALAR(metric, '$.matchType') AS matchType,
JSON_EXTRACT_SCALAR(metric, '$.vctr') AS vctr,
JSON_EXTRACT_SCALAR(metric, '$.video5SecondViewRate') AS video5SecondViewRate,
JSON_EXTRACT_SCALAR(metric, '$.video5SecondViews') AS video5SecondViews,
JSON_EXTRACT_SCALAR(metric, '$.videoCompleteViews') AS videoCompleteViews,
JSON_EXTRACT_SCALAR(metric, '$.videoFirstQuartileViews') AS videoFirstQuartileViews,
JSON_EXTRACT_SCALAR(metric, '$.videoMidpointViews') AS videoMidpointViews,
JSON_EXTRACT_SCALAR(metric, '$.videoThirdQuartileViews') AS videoThirdQuartileViews,
JSON_EXTRACT_SCALAR(metric, '$.videoUnmutes') AS videoUnmutes,
JSON_EXTRACT_SCALAR(metric, '$.viewableImpressions') AS viewableImpressions,
JSON_EXTRACT_SCALAR(metric, '$.vtr') AS vtr 
FROM 
`shopify-pubsub-project.pilgrim_bi_airbyte_amazon_ads.sponsored_brands_video_report_stream`

