CREATE OR REPLACE TABLE `shopify-pubsub-project.Data_Warehouse_Easyecom_Staging.Orders`
PARTITION BY DATE_TRUNC(order_date,day)
CLUSTER BY order_status
OPTIONS(
 description = "Orders table is partitioned on Order date at day level and clustered by order status",
 require_partition_filter = FALSE
 )
 AS 
 select
 *
 from 
    (SELECT 
    distinct
    SAFE_CAST(invoice_id as STRING) as invoice_id,
    SAFE_CAST(order_id as STRING) as order_id,
    queue_message,
    queue_status,
    order_priority,
    block_split,
    reference_code,
    company_name,
    location_key,
    SAFE_CAST(warehouse_id as STRING) AS warehouse_id,
    seller_gst,
    SAFE_CAST(import_warehouse_id AS STRING) AS import_warehouse_id,
    import_warehouse_name,
    pickup_address,
    pickup_city,
    pickup_state,
    pickup_pin_code,
    pickup_country,
    invoice_currency_code,
    order_type,
    order_type_key,
    replacement_order,
    marketplace,
    marketplace_id,
    salesman_user_id,
    order_date,
    tat,
    available_after,
    invoice_date,
    import_date,
    last_update_date,
    manifest_date,
    manifest_no,
    invoice_number,
    marketplace_invoice_num,
    shipping_last_update_date,
    SAFE_CAST(batch_id as STRING) as batch_id,
    batch_created_at,
    message,
    courier_aggregator_name,
    courier,
    SAFE_CAST(carrier_id as STRING) as carrier_id,
    awb_number,
    package_weight,
    package_height,
    package_length,
    package_width,
    order_status,
    order_status_id,
    suborder_count,
    shipping_status,
    shipping_status_id,
    delivery_date,
    payment_mode,
    SAFE_CAST(payment_mode_id AS STRING) AS payment_mode_id ,
    payment_gateway_transaction_number,
    payment_gateway_name,
    SAFE_CAST(buyer_gst AS FLOAT64) AS buyer_gst,
    customer_name,
    contact_num,
    address_line_1,
    address_line_2,
    city,
    pin_code,
    state,
    state_code,
    country,
    email,
    latitude,
    longitude,
    billing_name,
    billing_address_1,
    billing_address_2,
    billing_city,
    billing_state,
    billing_state_code,
    billing_pin_code,
    billing_country,
    billing_mobile,
    order_quantity,
    meta,
    JSON_EXTRACT_SCALAR(documents,'$[0][easyecom_invoice]') AS easyecom_invoice,
    JSON_EXTRACT_SCALAR(documents,'$[0][label]') AS label,
    JSON_EXTRACT_SCALAR(documents,'$[0][marketplaceinvoice]') AS marketplaceinvoice,
    JSON_EXTRACT_SCALAR(documents,'$[0][marketplace_tax_invoice]') AS marketplace_tax_invoice,
    JSON_EXTRACT_SCALAR(documents,'$[0][marketplace_b2c_invoice]') AS marketplace_b2c_invoice,
    total_amount,
    total_tax,
    total_shipping_charge,
    total_discount,
    collectable_amount,
    tcs_rate,
    tcs_amount,
    customer_code,
    fulfillable_status,
    ee_extracted_at,
    row_number() over(partition by invoice_id order by last_update_date desc) as ranking
    FROM `shopify-pubsub-project.easycom.orders`
)
where ranking = 1
