MERGE INTO `shopify-pubsub-project.Data_Warehouse_GoogleAds_Staging.user_location_view` AS TARGET
USING
(
SELECT
_airbyte_extracted_at,
ad_group_base_ad_group,
ad_group_name,
ad_group_status,
campaign_base_campaign,
campaign_id,
campaign_name,
campaign_status,
customer_id,
metrics_all_conversions,
metrics_all_conversions_from_interactions_rate,
metrics_all_conversions_value,
metrics_average_cost,
metrics_average_cpc,
metrics_average_cpm,
metrics_average_cpv,
metrics_clicks,
metrics_conversions,
metrics_conversions_from_interactions_rate,
metrics_conversions_value,
metrics_cost_micros,
metrics_cost_per_all_conversions,
metrics_cost_per_conversion,
metrics_cross_device_conversions,
metrics_ctr,
metrics_impressions,
metrics_interaction_rate,
metrics_interactions,
metrics_value_per_all_conversions,
metrics_value_per_conversion,
metrics_video_view_rate,
metrics_video_views,
metrics_view_through_conversions,
segments_ad_network_type,
segments_date,
segments_day_of_week,
segments_month,
segments_quarter,
segments_week,
segments_year,
user_location_view_country_criterion_id,
user_location_view_resource_name,
user_location_view_targeting_location,
FROM
(
select *,
row_number() over(partition by segments_date,segments_ad_network_type,user_location_view_resource_name order by _airbyte_extracted_at desc) as rn
from shopify-pubsub-project.pilgrim_bi_google_ads.user_location_view
)
where rn = 1 and DATE(_airbyte_extracted_at) >= DATE_SUB(CURRENT_DATE("Asia/Kolkata"), INTERVAL 10 DAY)
) as SOURCE
ON target.segments_date = source.segments_date
and target.segments_ad_network_type = source.segments_ad_network_type
and target.user_location_view_resource_name = source.user_location_view_resource_name
when
  MATCHED AND SOURCE._airbyte_extracted_at > TARGET._airbyte_extracted_at
then
  update set
    target._airbyte_extracted_at = source._airbyte_extracted_at,
    target.ad_group_base_ad_group = source.ad_group_base_ad_group,
    target.ad_group_name = source.ad_group_name,
    target.ad_group_status = source.ad_group_status,
    target.campaign_base_campaign = source.campaign_base_campaign,
    target.campaign_id = source.campaign_id,
    target.campaign_name = source.campaign_name,
    target.campaign_status = source.campaign_status,
    target.customer_id = source.customer_id,
    target.metrics_all_conversions = source.metrics_all_conversions,
    target.metrics_all_conversions_from_interactions_rate = source.metrics_all_conversions_from_interactions_rate,
    target.metrics_all_conversions_value = source.metrics_all_conversions_value,
    target.metrics_average_cost = source.metrics_average_cost,
    target.metrics_average_cpc = source.metrics_average_cpc,
    target.metrics_average_cpm = source.metrics_average_cpm,
    target.metrics_average_cpv = source.metrics_average_cpv,
    target.metrics_clicks = source.metrics_clicks,
    target.metrics_conversions = source.metrics_conversions,
    target.metrics_conversions_from_interactions_rate = source.metrics_conversions_from_interactions_rate,
    target.metrics_conversions_value = source.metrics_conversions_value,
    target.metrics_cost_micros = source.metrics_cost_micros,
    target.metrics_cost_per_all_conversions = source.metrics_cost_per_all_conversions,
    target.metrics_cost_per_conversion = source.metrics_cost_per_conversion,
    target.metrics_cross_device_conversions = source.metrics_cross_device_conversions,
    target.metrics_ctr = source.metrics_ctr,
    target.metrics_impressions = source.metrics_impressions,
    target.metrics_interaction_rate = source.metrics_interaction_rate,
    target.metrics_interactions = source.metrics_interactions,
    target.metrics_value_per_all_conversions = source.metrics_value_per_all_conversions,
    target.metrics_value_per_conversion = source.metrics_value_per_conversion,
    target.metrics_video_view_rate = source.metrics_video_view_rate,
    target.metrics_video_views = source.metrics_video_views,
    target.metrics_view_through_conversions = source.metrics_view_through_conversions,
    target.segments_ad_network_type = source.segments_ad_network_type,
    target.segments_date = source.segments_date,
    target.segments_day_of_week = source.segments_day_of_week,
    target.segments_month = source.segments_month,
    target.segments_quarter = source.segments_quarter,
    target.segments_week = source.segments_week,
    target.segments_year = source.segments_year,
    target.user_location_view_country_criterion_id = source.user_location_view_country_criterion_id,
    target.user_location_view_resource_name = source.user_location_view_resource_name,
    target.user_location_view_targeting_location = source.user_location_view_targeting_location
  when not matched
  then insert
  (
  _airbyte_extracted_at,
  ad_group_base_ad_group,
  ad_group_name,
  ad_group_status,
  campaign_base_campaign,
  campaign_id,
  campaign_name,
  campaign_status,
  customer_id,
  metrics_all_conversions,
  metrics_all_conversions_from_interactions_rate,
  metrics_all_conversions_value,
  metrics_average_cost,
  metrics_average_cpc,
  metrics_average_cpm,
  metrics_average_cpv,
  metrics_clicks,
  metrics_conversions,
  metrics_conversions_from_interactions_rate,
  metrics_conversions_value,
  metrics_cost_micros,
  metrics_cost_per_all_conversions,
  metrics_cost_per_conversion,
  metrics_cross_device_conversions,
  metrics_ctr,
  metrics_impressions,
  metrics_interaction_rate,
  metrics_interactions,
  metrics_value_per_all_conversions,
  metrics_value_per_conversion,
  metrics_video_view_rate,
  metrics_video_views,
  metrics_view_through_conversions,
  segments_ad_network_type,
  segments_date,
  segments_day_of_week,
  segments_month,
  segments_quarter,
  segments_week,
  segments_year,
  user_location_view_country_criterion_id,
  user_location_view_resource_name,
  user_location_view_targeting_location
  )
  values
  (
  source._airbyte_extracted_at,
  source.ad_group_base_ad_group,
  source.ad_group_name,
  source.ad_group_status,
  source.campaign_base_campaign,
  source.campaign_id,
  source.campaign_name,
  source.campaign_status,
  source.customer_id,
  source.metrics_all_conversions,
  source.metrics_all_conversions_from_interactions_rate,
  source.metrics_all_conversions_value,
  source.metrics_average_cost,
  source.metrics_average_cpc,
  source.metrics_average_cpm,
  source.metrics_average_cpv,
  source.metrics_clicks,
  source.metrics_conversions,
  source.metrics_conversions_from_interactions_rate,
  source.metrics_conversions_value,
  source.metrics_cost_micros,
  source.metrics_cost_per_all_conversions,
  source.metrics_cost_per_conversion,
  source.metrics_cross_device_conversions,
  source.metrics_ctr,
  source.metrics_impressions,
  source.metrics_interaction_rate,
  source.metrics_interactions,
  source.metrics_value_per_all_conversions,
  source.metrics_value_per_conversion,
  source.metrics_video_view_rate,
  source.metrics_video_views,
  source.metrics_view_through_conversions,
  source.segments_ad_network_type,
  source.segments_date,
  source.segments_day_of_week,
  source.segments_month,
  source.segments_quarter,
  source.segments_week,
  source.segments_year,
  source.user_location_view_country_criterion_id,
  source.user_location_view_resource_name,
  source.user_location_view_targeting_location
  )
