CREATE OR REPLACE TABLE `shopify-pubsub-project.Data_Warehouse_GoogleAds_Staging.user_location_view`
PARTITION BY DATE_TRUNC(_airbyte_extracted_at, DAY)
AS
SELECT
_airbyte_extracted_at,
ad_group_base_ad_group,
ad_group_name,
ad_group_status,
campaign_base_campaign,
campaign_id,
campaign_name,
campaign_status,
customer_id,
metrics_all_conversions,
metrics_all_conversions_from_interactions_rate,
metrics_all_conversions_value,
metrics_average_cost,
metrics_average_cpc,
metrics_average_cpm,
metrics_average_cpv,
metrics_clicks,
metrics_conversions,
metrics_conversions_from_interactions_rate,
metrics_conversions_value,
metrics_cost_micros,
metrics_cost_per_all_conversions,
metrics_cost_per_conversion,
metrics_cross_device_conversions,
metrics_ctr,
metrics_impressions,
metrics_interaction_rate,
metrics_interactions,
metrics_value_per_all_conversions,
metrics_value_per_conversion,
metrics_video_view_rate,
metrics_video_views,
metrics_view_through_conversions,
segments_ad_network_type,
segments_date,
segments_day_of_week,
segments_month,
segments_quarter,
segments_week,
segments_year,
user_location_view_country_criterion_id,
user_location_view_resource_name,
user_location_view_targeting_location,
FROM
(
select *,
row_number() over(partition by segments_date,segments_ad_network_type,user_location_view_resource_name order by _airbyte_extracted_at desc) as rn
from shopify-pubsub-project.pilgrim_bi_google_ads.user_location_view
)
where rn = 1