
MERGE INTO `shopify-pubsub-project.Data_Warehouse_Easyecom_Staging.Orders` AS target

USING (
select * from 
(select
distinct
CAST(invoice_id as STRING) as invoice_id,
CAST(order_id as STRING) as order_id,
queue_message,
queue_status,
order_priority,
block_split,
reference_code,
company_name,
location_key,
warehouse_id,
seller_gst,
import_warehouse_id,
import_warehouse_name,
pickup_address,
pickup_city,
pickup_state,
pickup_pin_code,
pickup_country,
invoice_currency_code,
order_type,
order_type_key,
replacement_order,
marketplace,
marketplace_id,
salesman_user_id,
order_date,
tat,
available_after,
invoice_date,
import_date,
last_update_date,
manifest_date,
manifest_no,
invoice_number,
marketplace_invoice_num,
shipping_last_update_date,
CAST(batch_id as STRING) as batch_id,
batch_created_at,
message,
courier_aggregator_name,
courier,
CAST(carrier_id as STRING) as carrier_id,
awb_number,
package_weight,
package_height,
package_length,
package_width,
order_status,
order_status_id,
suborder_count,
shipping_status,
shipping_status_id,
shipping_history,
delivery_date,
payment_mode,
payment_mode_id,
payment_gateway_transaction_number,
payment_gateway_name,
buyer_gst,
customer_name,
contact_num,
address_line_1,
address_line_2,
city,
pin_code,
state,
state_code,
country,
email,
latitude,
longitude,
billing_name,
billing_address_1,
billing_address_2,
billing_city,
billing_state,
billing_state_code,
billing_pin_code,
billing_country,
billing_mobile,
order_quantity,
meta,
documents,
total_amount,
total_tax,
total_shipping_charge,
total_discount,
collectable_amount,
tcs_rate,
tcs_amount,
customer_code,
fulfillable_status,
FROM `shopify-pubsub-project.easycom.orders`

)
  WHERE date(order_date) >= DATE_SUB(CURRENT_DATE("Asia/Kolkata"), INTERVAL 15 DAY)
 

 ) AS source
ON target.order_id = source.order_id
WHEN MATCHED AND source.order_date > target.order_date THEN UPDATE SET
 
target.invoice_id = source.invoice_id,
target.order_id = source.order_id,
target.queue_message = source.queue_message,
target.queue_status = source.queue_status,
target.order_priority = source.order_priority,
target.block_split = source.block_split,
target.reference_code = source.reference_code,
target.company_name = source.company_name,
target.location_key = source.location_key,
target.warehouse_id = source.warehouse_id,
target.seller_gst = source.seller_gst,
target.import_warehouse_id = source.import_warehouse_id,
target.import_warehouse_name = source.import_warehouse_name,
target.pickup_address = source.pickup_address,
target.pickup_city = source.pickup_city,
target.pickup_state = source.pickup_state,
target.pickup_pin_code = source.pickup_pin_code,
target.pickup_country = source.pickup_country,
target.invoice_currency_code = source.invoice_currency_code,
target.order_type = source.order_type,
target.order_type_key = source.order_type_key,
target.replacement_order = source.replacement_order,
target.marketplace = source.marketplace,
target.marketplace_id = source.marketplace_id,
target.salesman_user_id = source.salesman_user_id,
target.order_date = source.order_date,
target.tat = source.tat,
target.available_after = source.available_after,
target.invoice_date = source.invoice_date,
target.import_date = source.import_date,
target.last_update_date = source.last_update_date,
target.manifest_date = source.manifest_date,
target.manifest_no = source.manifest_no,
target.invoice_number = source.invoice_number,
target.marketplace_invoice_num = source.marketplace_invoice_num,
target.shipping_last_update_date = source.shipping_last_update_date,
target.batch_id = source.batch_id,
target.batch_created_at = source.batch_created_at,
target.message = source.message,
target.courier_aggregator_name = source.courier_aggregator_name,
target.courier = source.courier,
target.carrier_id = source.carrier_id,
target.awb_number = source.awb_number,
target.package_weight = source.package_weight,
target.package_height = source.package_height,
target.package_length = source.package_length,
target.package_width = source.package_width,
target.order_status = source.order_status,
target.order_status_id = source.order_status_id,
target.suborder_count = source.suborder_count,
target.shipping_status = source.shipping_status,
target.shipping_status_id = source.shipping_status_id,
target.shipping_history = source.shipping_history,
target.delivery_date = source.delivery_date,
target.payment_mode = source.payment_mode,
target.payment_mode_id = source.payment_mode_id,
target.payment_gateway_transaction_number = source.payment_gateway_transaction_number,
target.payment_gateway_name = source.payment_gateway_name,
target.buyer_gst = source.buyer_gst,
target.customer_name = source.customer_name,
target.contact_num = source.contact_num,
target.address_line_1 = source.address_line_1,
target.address_line_2 = source.address_line_2,
target.city = source.city,
target.pin_code = source.pin_code,
target.state = source.state,
target.state_code = source.state_code,
target.country = source.country,
target.email = source.email,
target.latitude = source.latitude,
target.longitude = source.longitude,
target.billing_name = source.billing_name,
target.billing_address_1 = source.billing_address_1,
target.billing_address_2 = source.billing_address_2,
target.billing_city = source.billing_city,
target.billing_state = source.billing_state,
target.billing_state_code = source.billing_state_code,
target.billing_pin_code = source.billing_pin_code,
target.billing_country = source.billing_country,
target.billing_mobile = source.billing_mobile,
target.order_quantity = source.order_quantity,
target.meta = source.meta,
target.documents = source.documents,
target.total_amount = source.total_amount,
target.total_tax = source.total_tax,
target.total_shipping_charge = source.total_shipping_charge,
target.total_discount = source.total_discount,
target.collectable_amount = source.collectable_amount,
target.tcs_rate = source.tcs_rate,
target.tcs_amount = source.tcs_amount,
target.customer_code = source.customer_code,
target.fulfillable_status = source.fulfillable_status

WHEN NOT MATCHED THEN INSERT (
invoice_id,
order_id,
queue_message,
queue_status,
order_priority,
block_split,
reference_code,
company_name,
location_key,
warehouse_id,
seller_gst,
import_warehouse_id,
import_warehouse_name,
pickup_address,
pickup_city,
pickup_state,
pickup_pin_code,
pickup_country,
invoice_currency_code,
order_type,
order_type_key,
replacement_order,
marketplace,
marketplace_id,
salesman_user_id,
order_date,
tat,
available_after,
invoice_date,
import_date,
last_update_date,
manifest_date,
manifest_no,
invoice_number,
marketplace_invoice_num,
shipping_last_update_date,
batch_id,
batch_created_at,
message,
courier_aggregator_name,
courier,
carrier_id,
awb_number,
package_weight,
package_height,
package_length,
package_width,
order_status,
order_status_id,
suborder_count,
shipping_status,
shipping_status_id,
shipping_history,
delivery_date,
payment_mode,
payment_mode_id,
payment_gateway_transaction_number,
payment_gateway_name,
buyer_gst,
customer_name,
contact_num,
address_line_1,
address_line_2,
city,
pin_code,
state,
state_code,
country,
email,
latitude,
longitude,
billing_name,
billing_address_1,
billing_address_2,
billing_city,
billing_state,
billing_state_code,
billing_pin_code,
billing_country,
billing_mobile,
order_quantity,
meta,
documents,
total_amount,
total_tax,
total_shipping_charge,
total_discount,
collectable_amount,
tcs_rate,
tcs_amount,
customer_code,
fulfillable_status

)
  VALUES (
source.invoice_id,
source.order_id,
source.queue_message,
source.queue_status,
source.order_priority,
source.block_split,
source.reference_code,
source.company_name,
source.location_key,
source.warehouse_id,
source.seller_gst,
source.import_warehouse_id,
source.import_warehouse_name,
source.pickup_address,
source.pickup_city,
source.pickup_state,
source.pickup_pin_code,
source.pickup_country,
source.invoice_currency_code,
source.order_type,
source.order_type_key,
source.replacement_order,
source.marketplace,
source.marketplace_id,
source.salesman_user_id,
source.order_date,
source.tat,
source.available_after,
source.invoice_date,
source.import_date,
source.last_update_date,
source.manifest_date,
source.manifest_no,
source.invoice_number,
source.marketplace_invoice_num,
source.shipping_last_update_date,
source.batch_id,
source.batch_created_at,
source.message,
source.courier_aggregator_name,
source.courier,
source.carrier_id,
source.awb_number,
source.package_weight,
source.package_height,
source.package_length,
source.package_width,
source.order_status,
source.order_status_id,
source.suborder_count,
source.shipping_status,
source.shipping_status_id,
source.shipping_history,
source.delivery_date,
source.payment_mode,
source.payment_mode_id,
source.payment_gateway_transaction_number,
source.payment_gateway_name,
source.buyer_gst,
source.customer_name,
source.contact_num,
source.address_line_1,
source.address_line_2,
source.city,
source.pin_code,
source.state,
source.state_code,
source.country,
source.email,
source.latitude,
source.longitude,
source.billing_name,
source.billing_address_1,
source.billing_address_2,
source.billing_city,
source.billing_state,
source.billing_state_code,
source.billing_pin_code,
source.billing_country,
source.billing_mobile,
source.order_quantity,
source.meta,
source.documents,
source.total_amount,
source.total_tax,
source.total_shipping_charge,
source.total_discount,
source.collectable_amount,
source.tcs_rate,
source.tcs_amount,
source.customer_code,
source.fulfillable_status
)
