
MERGE INTO `shopify-pubsub-project.Data_Warehouse_Easyecom_Staging.Orders` AS target

USING (

select
 *
 from 
    (SELECT 
    distinct
    SAFE_CAST(invoice_id as STRING) as invoice_id,
    SAFE_CAST(order_id as STRING) as order_id,
    queue_message,
    queue_status,
    order_priority,
    block_split,
    reference_code,
    company_name,
    location_key,
    SAFE_CAST(warehouse_id as STRING) AS warehouse_id,
    seller_gst,
    SAFE_CAST(import_warehouse_id AS STRING) AS import_warehouse_id,
    import_warehouse_name,
    pickup_address,
    pickup_city,
    pickup_state,
    pickup_pin_code,
    pickup_country,
    invoice_currency_code,
    order_type,
    order_type_key,
    replacement_order,
    marketplace,
    marketplace_id,
    salesman_user_id,
    order_date,
    tat,
    available_after,
    invoice_date,
    import_date,
    last_update_date,
    manifest_date,
    manifest_no,
    invoice_number,
    marketplace_invoice_num,
    shipping_last_update_date,
    SAFE_CAST(batch_id as STRING) as batch_id,
    batch_created_at,
    message,
    courier_aggregator_name,
    courier,
    SAFE_CAST(carrier_id as STRING) as carrier_id,
    awb_number,
    package_weight,
    package_height,
    package_length,
    package_width,
    order_status,
    order_status_id,
    suborder_count,
    shipping_status,
    shipping_status_id,
    delivery_date,
    payment_mode,
    SAFE_CAST(payment_mode_id AS STRING) AS payment_mode_id ,
    payment_gateway_transaction_number,
    payment_gateway_name,
    SAFE_CAST(buyer_gst AS FLOAT64) AS buyer_gst,
    customer_name,
    contact_num,
    address_line_1,
    address_line_2,
    city,
    pin_code,
    state,
    state_code,
    country,
    email,
    latitude,
    longitude,
    billing_name,
    billing_address_1,
    billing_address_2,
    billing_city,
    billing_state,
    billing_state_code,
    billing_pin_code,
    billing_country,
    billing_mobile,
    order_quantity,
    meta,
    JSON_EXTRACT_SCALAR(documents,'$[0][easyecom_invoice]') AS easyecom_invoice,
    JSON_EXTRACT_SCALAR(documents,'$[0][label]') AS label,
    JSON_EXTRACT_SCALAR(documents,'$[0][marketplaceinvoice]') AS marketplaceinvoice,
    JSON_EXTRACT_SCALAR(documents,'$[0][marketplace_tax_invoice]') AS marketplace_tax_invoice,
    JSON_EXTRACT_SCALAR(documents,'$[0][marketplace_b2c_invoice]') AS marketplace_b2c_invoice,
    total_amount,
    total_tax,
    total_shipping_charge,
    total_discount,
    collectable_amount,
    tcs_rate,
    tcs_amount,
    customer_code,
    fulfillable_status,
    ee_extracted_at,
    row_number() over(partition by invoice_id order by last_update_date desc) as ranking
    FROM `shopify-pubsub-project.easycom.orders`)

where ranking = 1 and date(order_date) >= DATE_SUB(CURRENT_DATE("Asia/Kolkata"), INTERVAL 30 DAY)

 ) AS source
ON target.invoice_id = source.invoice_id
and target.order_id = source.order_id

WHEN MATCHED THEN UPDATE SET 
target.invoice_id = source.invoice_id,
target.order_id = source.order_id,
target.queue_message = source.queue_message,
target.queue_status = source.queue_status,
target.order_priority = source.order_priority,
target.block_split = source.block_split,
target.reference_code = source.reference_code,
target.company_name = source.company_name,
target.location_key = source.location_key,
target.warehouse_id = source.warehouse_id,
target.seller_gst = source.seller_gst,
target.import_warehouse_id = source.import_warehouse_id,
target.import_warehouse_name = source.import_warehouse_name,
target.pickup_address = source.pickup_address,
target.pickup_city = source.pickup_city,
target.pickup_state = source.pickup_state,
target.pickup_pin_code = source.pickup_pin_code,
target.pickup_country = source.pickup_country,
target.invoice_currency_code = source.invoice_currency_code,
target.order_type = source.order_type,
target.order_type_key = source.order_type_key,
target.replacement_order = source.replacement_order,
target.marketplace = source.marketplace,
target.marketplace_id = source.marketplace_id,
target.salesman_user_id = source.salesman_user_id,
target.order_date = source.order_date,
target.tat = source.tat,
target.available_after = source.available_after,
target.invoice_date = source.invoice_date,
target.import_date = source.import_date,
target.last_update_date = source.last_update_date,
target.manifest_date = source.manifest_date,
target.manifest_no = source.manifest_no,
target.invoice_number = source.invoice_number,
target.marketplace_invoice_num = source.marketplace_invoice_num,
target.shipping_last_update_date = source.shipping_last_update_date,
target.batch_id = source.batch_id,
target.batch_created_at = source.batch_created_at,
target.message = source.message,
target.courier_aggregator_name = source.courier_aggregator_name,
target.courier = source.courier,
target.carrier_id = source.carrier_id,
target.awb_number = source.awb_number,
target.package_weight = source.package_weight,
target.package_height = source.package_height,
target.package_length = source.package_length,
target.package_width = source.package_width,
target.order_status = source.order_status,
target.order_status_id = source.order_status_id,
target.suborder_count = source.suborder_count,
target.shipping_status = source.shipping_status,
target.shipping_status_id = source.shipping_status_id,
target.delivery_date = source.delivery_date,
target.payment_mode = source.payment_mode,
target.payment_gateway_transaction_number = source.payment_gateway_transaction_number,
target.payment_gateway_name = source.payment_gateway_name,
target.buyer_gst = source.buyer_gst,
target.customer_name = source.customer_name,
target.contact_num = source.contact_num,
target.address_line_1 = source.address_line_1,
target.address_line_2 = source.address_line_2,
target.city = source.city,
target.pin_code = source.pin_code,
target.state = source.state,
target.state_code = source.state_code,
target.country = source.country,
target.email = source.email,
target.latitude = source.latitude,
target.longitude = source.longitude,
target.billing_name = source.billing_name,
target.billing_address_1 = source.billing_address_1,
target.billing_address_2 = source.billing_address_2,
target.billing_city = source.billing_city,
target.billing_state = source.billing_state,
target.billing_state_code = source.billing_state_code,
target.billing_pin_code = source.billing_pin_code,
target.billing_country = source.billing_country,
target.billing_mobile = source.billing_mobile,
target.order_quantity = source.order_quantity,
target.meta = source.meta,
target.easyecom_invoice = source.easyecom_invoice,
target.label = source.label,
target.marketplaceinvoice = source.marketplaceinvoice,
target.marketplace_tax_invoice = source.marketplace_tax_invoice,
target.marketplace_b2c_invoice = source.marketplace_b2c_invoice,
target.total_amount = source.total_amount,
target.total_tax = source.total_tax,
target.total_shipping_charge = source.total_shipping_charge,
target.total_discount = source.total_discount,
target.collectable_amount = source.collectable_amount,
target.tcs_rate = source.tcs_rate,
target.tcs_amount = source.tcs_amount,
target.customer_code = source.customer_code,
target.fulfillable_status = source.fulfillable_status,
target.ee_extracted_at = source.ee_extracted_at,
target.ranking = source.ranking

WHEN NOT MATCHED THEN INSERT (
invoice_id,
order_id,
queue_message,
queue_status,
order_priority,
block_split,
reference_code,
company_name,
location_key,
warehouse_id,
seller_gst,
import_warehouse_id,
import_warehouse_name,
pickup_address,
pickup_city,
pickup_state,
pickup_pin_code,
pickup_country,
invoice_currency_code,
order_type,
order_type_key,
replacement_order,
marketplace,
marketplace_id,
salesman_user_id,
order_date,
tat,
available_after,
invoice_date,
import_date,
last_update_date,
manifest_date,
manifest_no,
invoice_number,
marketplace_invoice_num,
shipping_last_update_date,
batch_id,
batch_created_at,
message,
courier_aggregator_name,
courier,
carrier_id,
awb_number,
package_weight,
package_height,
package_length,
package_width,
order_status,
order_status_id,
suborder_count,
shipping_status,
shipping_status_id,
delivery_date,
payment_mode,
payment_gateway_transaction_number,
payment_gateway_name,
buyer_gst,
customer_name,
contact_num,
address_line_1,
address_line_2,
city,
pin_code,
state,
state_code,
country,
email,
latitude,
longitude,
billing_name,
billing_address_1,
billing_address_2,
billing_city,
billing_state,
billing_state_code,
billing_pin_code,
billing_country,
billing_mobile,
order_quantity,
meta,
easyecom_invoice,
label,
marketplaceinvoice,
marketplace_tax_invoice,
marketplace_b2c_invoice,
total_amount,
total_tax,
total_shipping_charge,
total_discount,
collectable_amount,
tcs_rate,
tcs_amount,
customer_code,
fulfillable_status,
ee_extracted_at,
ranking

)
  VALUES (

Source.invoice_id,
Source.order_id,
Source.queue_message,
Source.queue_status,
Source.order_priority,
Source.block_split,
Source.reference_code,
Source.company_name,
Source.location_key,
Source.warehouse_id,
Source.seller_gst,
Source.import_warehouse_id,
Source.import_warehouse_name,
Source.pickup_address,
Source.pickup_city,
Source.pickup_state,
Source.pickup_pin_code,
Source.pickup_country,
Source.invoice_currency_code,
Source.order_type,
Source.order_type_key,
Source.replacement_order,
Source.marketplace,
Source.marketplace_id,
Source.salesman_user_id,
Source.order_date,
Source.tat,
Source.available_after,
Source.invoice_date,
Source.import_date,
Source.last_update_date,
Source.manifest_date,
Source.manifest_no,
Source.invoice_number,
Source.marketplace_invoice_num,
Source.shipping_last_update_date,
Source.batch_id,
Source.batch_created_at,
Source.message,
Source.courier_aggregator_name,
Source.courier,
Source.carrier_id,
Source.awb_number,
Source.package_weight,
Source.package_height,
Source.package_length,
Source.package_width,
Source.order_status,
Source.order_status_id,
Source.suborder_count,
Source.shipping_status,
Source.shipping_status_id,
Source.delivery_date,
Source.payment_mode,
Source.payment_gateway_transaction_number,
Source.payment_gateway_name,
Source.buyer_gst,
Source.customer_name,
Source.contact_num,
Source.address_line_1,
Source.address_line_2,
Source.city,
Source.pin_code,
Source.state,
Source.state_code,
Source.country,
Source.email,
Source.latitude,
Source.longitude,
Source.billing_name,
Source.billing_address_1,
Source.billing_address_2,
Source.billing_city,
Source.billing_state,
Source.billing_state_code,
Source.billing_pin_code,
Source.billing_country,
Source.billing_mobile,
Source.order_quantity,
Source.meta,
Source.easyecom_invoice,
Source.label,
Source.marketplaceinvoice,
Source.marketplace_tax_invoice,
Source.marketplace_b2c_invoice,
Source.total_amount,
Source.total_tax,
Source.total_shipping_charge,
Source.total_discount,
Source.collectable_amount,
Source.tcs_rate,
Source.tcs_amount,
Source.customer_code,
Source.fulfillable_status,
Source.ee_extracted_at,
Source.ranking

)

