
MERGE INTO `shopify-pubsub-project.Data_Warehouse_Easyecom_Staging.All_Return_Orders` AS TARGET
USING
(
SELECT
  CAST(invoice_id AS STRING) AS invoice_id,
  CAST(order_id AS STRING) AS order_id,
  reference_code,
  company_name,
  CAST(ware_house_id AS STRING) AS ware_house_id,
  seller_gst,
  forward_shipment_pickup_address,
  forward_shipment_pickup_city,
  forward_shipment_pickup_state,
  forward_shipment_pickup_pin_code,
  forward_shipment_pickup_country,
  order_type,
  order_type_key,
  replacement_order,
  marketplace,
  CAST(marketplace_id AS STRING) AS marketplace_id,
  CAST(salesman_user_id AS STRING) AS salesman_user_id,
  order_date,
  invoice_date,
  import_date,
  last_update_date,
  manifest_date,
  return_date,
  manifest_no,
  invoice_number,
  marketplace_credit_note_num,
  marketplace_invoice_num,
  CAST(batch_id AS STRING) AS batch_id,
  batch_created_at,
  payment_mode,
  CAST(payment_mode_id AS STRING) AS payment_mode_id,
  buyer_gst,
  forward_shipment_customer_name,
  forward_shipment_customer_contact_num,
  forward_shipment_customer_address_line_1,
  forward_shipment_customer_address_line_2,
  forward_shipment_customer_city,
  forward_shipment_customer_pin_code,
  forward_shipment_customer_state,
  forward_shipment_customer_country,
  forward_shipment_customer_email,
  forward_shipment_billing_name,
  forward_shipment_billing_address_1,
  forward_shipment_billing_address_2,
  forward_shipment_billing_city,
  forward_shipment_billing_state,
  forward_shipment_billing_pin_code,
  forward_shipment_billing_country,
  forward_shipment_billing_mobile,
  order_quantity,
  total_invoice_amount,
  total_invoice_tax,
  invoice_collectable_amount,
  CAST(credit_note_id AS STRING) AS credit_note_id,
  credit_note_date,
  credit_note_number,
  ee_extracted_at
FROM
(
SELECT
*,
ROW_NUMBER() OVER(PARTITION BY order_date ORDER BY order_date DESC) as row_num
FROM `shopify-pubsub-project.easycom.all_return_orders`
WHERE DATE(order_date) >= DATE_SUB(CURRENT_DATE("Asia/Kolkata"), INTERVAL 10 DAY)
)
WHERE row_num = 1 -- Keep only the most recent row per customer_id and segments_date
) AS SOURCE
ON SOURCE.order_id = TARGET.order_id
WHEN MATCHED AND TARGET.order_date < SOURCE.order_date
THEN UPDATE SET
TARGET.invoice_id = SOURCE.invoice_id,
TARGET.order_id = SOURCE.order_id,
TARGET.reference_code = SOURCE.reference_code,
TARGET.company_name = SOURCE.company_name,
TARGET.ware_house_id = SOURCE.ware_house_id,
TARGET.seller_gst = SOURCE.seller_gst,
TARGET.forward_shipment_pickup_address = SOURCE.forward_shipment_pickup_address,
TARGET.forward_shipment_pickup_city = SOURCE.forward_shipment_pickup_city,
TARGET.forward_shipment_pickup_state = SOURCE.forward_shipment_pickup_state,
TARGET.forward_shipment_pickup_pin_code = SOURCE.forward_shipment_pickup_pin_code,
TARGET.forward_shipment_pickup_country = SOURCE.forward_shipment_pickup_country,
TARGET.order_type = SOURCE.order_type,
TARGET.order_type_key = SOURCE.order_type_key,
TARGET.replacement_order = SOURCE.replacement_order,
TARGET.marketplace = SOURCE.marketplace,
TARGET.marketplace_id = SOURCE.marketplace_id,
TARGET.salesman_user_id = SOURCE.salesman_user_id,
TARGET.order_date = SOURCE.order_date,
TARGET.invoice_date = SOURCE.invoice_date,
TARGET.import_date = SOURCE.import_date,
TARGET.last_update_date = SOURCE.last_update_date,
TARGET.manifest_date = SOURCE.manifest_date,
TARGET.return_date = SOURCE.return_date,
TARGET.manifest_no = SOURCE.manifest_no,
TARGET.invoice_number = SOURCE.invoice_number,
TARGET.marketplace_credit_note_num = SOURCE.marketplace_credit_note_num,
TARGET.marketplace_invoice_num = SOURCE.marketplace_invoice_num,
TARGET.batch_id = SOURCE.batch_id,
TARGET.batch_created_at = SOURCE.batch_created_at,
TARGET.payment_mode = SOURCE.payment_mode,
TARGET.payment_mode_id = SOURCE.payment_mode_id,
TARGET.buyer_gst = SOURCE.buyer_gst,
TARGET.forward_shipment_customer_name = SOURCE.forward_shipment_customer_name,
TARGET.forward_shipment_customer_contact_num = SOURCE.forward_shipment_customer_contact_num,
TARGET.forward_shipment_customer_address_line_1 = SOURCE.forward_shipment_customer_address_line_1,
TARGET.forward_shipment_customer_address_line_2 = SOURCE.forward_shipment_customer_address_line_2,
TARGET.forward_shipment_customer_city = SOURCE.forward_shipment_customer_city,
TARGET.forward_shipment_customer_pin_code = SOURCE.forward_shipment_customer_pin_code,
TARGET.forward_shipment_customer_state = SOURCE.forward_shipment_customer_state,
TARGET.forward_shipment_customer_country = SOURCE.forward_shipment_customer_country,
TARGET.forward_shipment_customer_email = SOURCE.forward_shipment_customer_email,
TARGET.forward_shipment_billing_name = SOURCE.forward_shipment_billing_name,
TARGET.forward_shipment_billing_address_1 = SOURCE.forward_shipment_billing_address_1,
TARGET.forward_shipment_billing_address_2 = SOURCE.forward_shipment_billing_address_2,
TARGET.forward_shipment_billing_city = SOURCE.forward_shipment_billing_city,
TARGET.forward_shipment_billing_state = SOURCE.forward_shipment_billing_state,
TARGET.forward_shipment_billing_pin_code = SOURCE.forward_shipment_billing_pin_code,
TARGET.forward_shipment_billing_country = SOURCE.forward_shipment_billing_country,
TARGET.forward_shipment_billing_mobile = SOURCE.forward_shipment_billing_mobile,
TARGET.order_quantity = SOURCE.order_quantity,
TARGET.total_invoice_amount = SOURCE.total_invoice_amount,
TARGET.total_invoice_tax = SOURCE.total_invoice_tax,
TARGET.invoice_collectable_amount = SOURCE.invoice_collectable_amount,
TARGET.credit_note_id = SOURCE.credit_note_id,
TARGET.credit_note_date = SOURCE.credit_note_date,
TARGET.credit_note_number = SOURCE.credit_note_number
WHEN NOT MATCHED
THEN INSERT
(
  invoice_id,
  order_id,
  reference_code,
  company_name,
  ware_house_id,
  seller_gst,
  forward_shipment_pickup_address,
  forward_shipment_pickup_city,
  forward_shipment_pickup_state,
  forward_shipment_pickup_pin_code,
  forward_shipment_pickup_country,
  order_type,
  order_type_key,
  replacement_order,
  marketplace,
  marketplace_id,
  salesman_user_id,
  order_date,
  invoice_date,
  import_date,
  last_update_date,
  manifest_date,
  return_date,
  manifest_no,
  invoice_number,
  marketplace_credit_note_num,
  marketplace_invoice_num,
  batch_id,
  batch_created_at,
  payment_mode,
  payment_mode_id,
  buyer_gst,
  forward_shipment_customer_name,
  forward_shipment_customer_contact_num,
  forward_shipment_customer_address_line_1,
  forward_shipment_customer_address_line_2,
  forward_shipment_customer_city,
  forward_shipment_customer_pin_code,
  forward_shipment_customer_state,
  forward_shipment_customer_country,
  forward_shipment_customer_email,
  forward_shipment_billing_name,
  forward_shipment_billing_address_1,
  forward_shipment_billing_address_2,
  forward_shipment_billing_city,
  forward_shipment_billing_state,
  forward_shipment_billing_pin_code,
  forward_shipment_billing_country,
  forward_shipment_billing_mobile,
  order_quantity,
  total_invoice_amount,
  total_invoice_tax,
  invoice_collectable_amount,
  credit_note_id,
  credit_note_date,
  credit_note_number
)
VALUES
(
SOURCE.invoice_id,
SOURCE.order_id,
SOURCE.reference_code,
SOURCE.company_name,
SOURCE.ware_house_id,
SOURCE.seller_gst,
SOURCE.forward_shipment_pickup_address,
SOURCE.forward_shipment_pickup_city,
SOURCE.forward_shipment_pickup_state,
SOURCE.forward_shipment_pickup_pin_code,
SOURCE.forward_shipment_pickup_country,
SOURCE.order_type,
SOURCE.order_type_key,
SOURCE.replacement_order,
SOURCE.marketplace,
SOURCE.marketplace_id,
SOURCE.salesman_user_id,
SOURCE.order_date,
SOURCE.invoice_date,
SOURCE.import_date,
SOURCE.last_update_date,
SOURCE.manifest_date,
SOURCE.return_date,
SOURCE.manifest_no,
SOURCE.invoice_number,
SOURCE.marketplace_credit_note_num,
SOURCE.marketplace_invoice_num,
SOURCE.batch_id,
SOURCE.batch_created_at,
SOURCE.payment_mode,
SOURCE.payment_mode_id,
SOURCE.buyer_gst,
SOURCE.forward_shipment_customer_name,
SOURCE.forward_shipment_customer_contact_num,
SOURCE.forward_shipment_customer_address_line_1,
SOURCE.forward_shipment_customer_address_line_2,
SOURCE.forward_shipment_customer_city,
SOURCE.forward_shipment_customer_pin_code,
SOURCE.forward_shipment_customer_state,
SOURCE.forward_shipment_customer_country,
SOURCE.forward_shipment_customer_email,
SOURCE.forward_shipment_billing_name,
SOURCE.forward_shipment_billing_address_1,
SOURCE.forward_shipment_billing_address_2,
SOURCE.forward_shipment_billing_city,
SOURCE.forward_shipment_billing_state,
SOURCE.forward_shipment_billing_pin_code,
SOURCE.forward_shipment_billing_country,
SOURCE.forward_shipment_billing_mobile,
SOURCE.order_quantity,
SOURCE.total_invoice_amount,
SOURCE.total_invoice_tax,
SOURCE.invoice_collectable_amount,
SOURCE.credit_note_id,
SOURCE.credit_note_date,
SOURCE.credit_note_number
)
