MERGE INTO `shopify-pubsub-project.Shopify_staging.Abandoned_checkout_lineitem` AS target
USING (
select 
*
from ( select 
  _airbyte_extracted_at,
    aband_source_name,
    aband_referring_site,
    aband_completed_at,
    aband_phone,
    aband_landing_site,
    aband_created_at,
    aband_updated_at,
    customer_email,
    aband_cart_token,
    abandoned_checkout_url,
    abandoned_checkout_id,
    abandoned_checkout_name,
    abandoned_checkout_token,
    customer_id,
    disocunt_code,
    discount_type,
    item_application_type,
    item_discount_created_at,
    item_discount_description,
    item_discount_class,
    item_discount_id,
    item_presentment_title,
    product_id,
    item_SKU_code,
    tax_line_title,
    product_title,
    item_variant_id,
    item_variant_title,
    sum(item_discount_amount) as item_discount_amount,
    sum(item_compare_at_price) as item_compare_at_price,
    sum(item_line_price) as item_line_price,
    sum(item_price) as item_price,
    sum(item_quantity) as item_quantity,
    sum(tax_line_price) as tax_line_price,
    avg(tax_line_rate) as tax_line_rate,
    sum(item_variant_price) as item_variant_price,
    sum(discount_amount) as discount_amount,
    sum(aband_total_line_items_price) as aband_total_line_items_price,
    sum(aband_total_discounts) as aband_total_discounts,
    sum(aband_total_price) as aband_total_price,
    sum(aband_total_tax) as aband_total_tax,
 from (
select
*
from (
    select
    distinct
    _airbyte_extracted_at,
    aband_source_name,
    aband_referring_site,
    aband_completed_at,
    aband_phone,
    aband_landing_site,
    aband_created_at,
    aband_updated_at,
    customer_email,
    aband_cart_token,
    abandoned_checkout_url,
    abandoned_checkout_id,
    abandoned_checkout_name,
    abandoned_checkout_token,
    customer_id,
    disocunt_code,
    discount_type,
    item_application_type,
    item_discount_created_at,
    item_discount_description,
    item_discount_class,
    item_discount_id,
    item_presentment_title,
    product_id,
    item_SKU_code,
    tax_line_title,
    product_title,
    item_variant_id,
    item_variant_title,
    item_discount_amount,
    item_compare_at_price,
    item_line_price,
    item_price,
    item_quantity,
    tax_line_price,
    tax_line_rate,
    item_variant_price,
    discount_amount,
    aband_total_line_items_price,
    aband_total_discounts,
    aband_total_price,
    aband_total_tax,
    row_number() over(partition by abandoned_checkout_id,item_variant_id order by item_discount_created_at desc) as ranking

from
(select 

    _airbyte_extracted_at,
    aband_source_name,
    aband_referring_site,
    aband_completed_at,
    aband_phone,
    aband_landing_site,
    aband_created_at,
    aband_updated_at,
    customer_email,
    aband_cart_token,
    abandoned_checkout_url,
    abandoned_checkout_id,
    abandoned_checkout_name,
    abandoned_checkout_token,
    customer_id,
    disocunt_code,
    discount_type,
    CAST(JSON_EXTRACT_SCALAR(Full_FLAT,'$.applied_discounts[0].application_type') AS STRING) as item_application_type,
    CAST(JSON_EXTRACT_SCALAR(Full_FLAT,'$.applied_discounts[0].created_at') AS TIMESTAMP) as item_discount_created_at,
    CAST(JSON_EXTRACT_SCALAR(Full_FLAT,'$.applied_discounts[0].description') AS STRING) as item_discount_description,
    CAST(JSON_EXTRACT_SCALAR(Full_FLAT,'$.applied_discounts[0].discount_class') AS STRING) as item_discount_class,
    CAST(JSON_EXTRACT_SCALAR(Full_FLAT,'$.applied_discounts[0].id') AS STRING) as item_discount_id,

    JSON_EXTRACT_SCALAR(Full_FLAT,'$.presentment_title') as item_presentment_title,
    JSON_EXTRACT_SCALAR(Full_FLAT,'$.product_id') as product_id,
    JSON_EXTRACT_SCALAR(Full_FLAT,'$.sku') as item_SKU_code,
    JSON_EXTRACT_SCALAR(Full_FLAT,'$.tax_lines[0].title') as tax_line_title,
    JSON_EXTRACT_SCALAR(Full_FLAT,'$.title') as product_title,
    CAST(JSON_EXTRACT_SCALAR(Full_FLAT,'$.variant_id') AS STRING) as item_variant_id,
    CAST(JSON_EXTRACT_SCALAR(Full_FLAT,'$.variant_title') AS STRING) as item_variant_title,

    CAST(JSON_EXTRACT_SCALAR(Full_FLAT,'$.applied_discounts[0].amount') AS FLOAT64) as item_discount_amount,
    CAST(JSON_EXTRACT_SCALAR(Full_FLAT,'$.compare_at_price') AS FLOAT64) as item_compare_at_price,
    CAST(JSON_EXTRACT_SCALAR(Full_FLAT,'$.line_price') AS FLOAT64) as item_line_price,
    CAST(JSON_EXTRACT_SCALAR(Full_FLAT,'$.price') AS FLOAT64) as item_price,
    CAST(JSON_EXTRACT_SCALAR(Full_FLAT,'$.quantity') AS FLOAT64) as item_quantity,
    CAST(JSON_EXTRACT_SCALAR(Full_FLAT,'$.tax_lines[0].price') AS FLOAT64) as tax_line_price,
    CAST(JSON_EXTRACT_SCALAR(Full_FLAT,'$.tax_lines[0].rate') AS FLOAT64 ) as tax_line_rate,
    CAST(JSON_EXTRACT_SCALAR(Full_FLAT,'$.variant_price') AS FLOAT64) as item_variant_price,   
    discount_amount as discount_amount,
    aband_total_line_items_price as aband_total_line_items_price,
    aband_total_discounts as aband_total_discounts,
    aband_total_price as aband_total_price,
    aband_total_tax as aband_total_tax,


from (
select
    _airbyte_extracted_at,
    aband_source_name,
    aband_referring_site,
    aband_total_line_items_price,
    aband_total_discounts,
    aband_total_price,
    aband_total_tax,
    aband_completed_at,
    aband_phone,
    aband_landing_site,
    aband_created_at,
    aband_updated_at,
    customer_email,
    aband_cart_token,
    abandoned_checkout_url,
    abandoned_checkout_id,
    abandoned_checkout_name,
    abandoned_checkout_token,
    customer_id,
    discount_amount,
    disocunt_code,
    discount_type,
    FULL_FLAT,
FROM (
SELECT 
  _airbyte_emitted_at as _airbyte_extracted_at,
  source_name as aband_source_name,
  referring_site as aband_referring_site,
  total_line_items_price as aband_total_line_items_price,
  total_discounts as aband_total_discounts,
  total_price as aband_total_price,
  total_tax as aband_total_tax,
  completed_at as aband_completed_at,
  phone as aband_phone,
  landing_site as aband_landing_site,
  created_at as aband_created_at,
  updated_at as aband_updated_at,
  email as customer_email,
  cart_token as aband_cart_token,
  abandoned_checkout_url as abandoned_checkout_url,
  CAST(id AS STRING) as abandoned_checkout_id,
  name as abandoned_checkout_name,
  token as abandoned_checkout_token,
  CAST(JSON_EXTRACT_SCALAR(customer, '$.id') AS STRING) AS customer_id,
  CAST(JSON_EXTRACT_SCALAR(discount_codes, '$[0].amount') AS FLOAT64) AS discount_amount,
  CAST(JSON_EXTRACT_SCALAR(discount_codes, '$[0].code') AS STRING) AS disocunt_code,
  CAST(JSON_EXTRACT_SCALAR(discount_codes, '$[0].type') AS STRING) AS discount_type,
  JSON_EXTRACT_ARRAY(line_items) as line_item_flat,

FROM  `shopify-pubsub-project.airbyte711.abandoned_checkouts`

), UNNEST (line_item_flat) AS FULL_FLAT
))
)where ranking = 1 )
group by ALL)

  WHERE date(_airbyte_extracted_at) >= DATE_SUB(CURRENT_DATE("Asia/Kolkata"), INTERVAL 30 DAY)
 
 ) AS source
ON target.abandoned_checkout_id = source.abandoned_checkout_id
WHEN MATCHED AND source._airbyte_extracted_at > target._airbyte_extracted_at THEN UPDATE SET

  target._airbyte_extracted_at = source._airbyte_extracted_at,
  target.aband_source_name = source.aband_source_name,
  target.aband_referring_site = source.aband_referring_site,
  target.aband_total_line_items_price = source.aband_total_line_items_price,
  target.aband_total_discounts = source.aband_total_discounts,
  target.aband_total_price = source.aband_total_price,
  target.aband_total_tax = source.aband_total_tax,
  target.aband_completed_at = source.aband_completed_at,
  target.aband_phone = source.aband_phone,
  target.aband_landing_site = source.aband_landing_site,
  target.aband_created_at = source.aband_created_at,
  target.aband_updated_at = source.aband_updated_at,
  target.customer_email = source.customer_email,
  target.aband_cart_token = source.aband_cart_token,
  target.abandoned_checkout_url = source.abandoned_checkout_url,
  target.abandoned_checkout_id = source.abandoned_checkout_id,
  target.abandoned_checkout_name = source.abandoned_checkout_name,
  target.abandoned_checkout_token = source.abandoned_checkout_token,
  target.customer_id = source.customer_id,
  target.discount_amount = source.discount_amount,
  target.disocunt_code = source.disocunt_code,
  target.discount_type = source.discount_type,
  target.item_discount_amount = source.item_discount_amount,
  target.item_application_type = source.item_application_type,
  target.item_discount_created_at = source.item_discount_created_at,
  target.item_discount_description = source.item_discount_description,
  target.item_discount_class = source.item_discount_class,
  target.item_discount_id = source.item_discount_id,
  target.item_compare_at_price = source.item_compare_at_price,
  target.item_line_price = source.item_line_price,
  target.item_presentment_title = source.item_presentment_title,
  target.item_price = source.item_price,
  target.product_id = source.product_id,
  target.item_SKU_code = source.item_SKU_code,
  target.item_quantity = source.item_quantity,
  target.tax_line_price = source.tax_line_price,
  target.tax_line_rate = source.tax_line_rate,
  target.tax_line_title = source.tax_line_title,
  target.product_title = source.product_title,
  target.item_variant_id = source.item_variant_id,
  target.item_variant_price = source.item_variant_price,
  target.item_variant_title = source.item_variant_title

WHEN NOT MATCHED THEN INSERT (

  _airbyte_extracted_at,
  aband_source_name,
  aband_referring_site,
  aband_total_line_items_price,
  aband_total_discounts,
  aband_total_price,
  aband_total_tax,
  aband_completed_at,
  aband_phone,
  aband_landing_site,
  aband_created_at,
  aband_updated_at,
  customer_email,
  aband_cart_token,
  abandoned_checkout_url,
  abandoned_checkout_id,
  abandoned_checkout_name,
  abandoned_checkout_token,
  customer_id,
  discount_amount,
  disocunt_code,
  discount_type,
  item_discount_amount,
  item_application_type,
  item_discount_created_at,
  item_discount_description,
  item_discount_class,
  item_discount_id,
  item_compare_at_price,
  item_line_price,
  item_presentment_title,
  item_price,
  product_id,
  item_SKU_code,
  item_quantity,
  tax_line_price,
  tax_line_rate,
  tax_line_title,
  product_title,
  item_variant_id,
  item_variant_price,
  item_variant_title
 )

  VALUES (
  source._airbyte_extracted_at,
  source.aband_source_name,
  source.aband_referring_site,
  source.aband_total_line_items_price,
  source.aband_total_discounts,
  source.aband_total_price,
  source.aband_total_tax,
  source.aband_completed_at,
  source.aband_phone,
  source.aband_landing_site,
  source.aband_created_at,
  source.aband_updated_at,
  source.customer_email,
  source.aband_cart_token,
  source.abandoned_checkout_url,
  source.abandoned_checkout_id,
  source.abandoned_checkout_name,
  source.abandoned_checkout_token,
  source.customer_id,
  source.discount_amount,
  source.disocunt_code,
  source.discount_type,
  source.item_discount_amount,
  source.item_application_type,
  source.item_discount_created_at,
  source.item_discount_description,
  source.item_discount_class,
  source.item_discount_id,
  source.item_compare_at_price,
  source.item_line_price,
  source.item_presentment_title,
  source.item_price,
  source.product_id,
  source.item_SKU_code,
  source.item_quantity,
  source.tax_line_price,
  source.tax_line_rate,
  source.tax_line_title,
  source.product_title,
  source.item_variant_id,
  source.item_variant_price,
  source.item_variant_title
  )
