{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7dd1ebe0-bee6-446f-b620-e16a7a4a34c9",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\OMKAR\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\google\\cloud\\bigquery\\table.py:1727: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Folder structure and required files created successfully!\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import subprocess\n",
    "from google.cloud import bigquery\n",
    "import pandas as pd\n",
    "\n",
    "# Function to install a package\n",
    "def install_package(package_name):\n",
    "    try:\n",
    "        subprocess.check_call([\"pip\", \"install\", package_name])\n",
    "    except subprocess.CalledProcessError as e:\n",
    "        print(f\"Error installing package {package_name}: {e}\")\n",
    "        raise\n",
    "\n",
    "# Ensure the required library is installed\n",
    "required_package = \"db-dtypes\"\n",
    "try:\n",
    "    import db_dtypes  # Attempt to import the package to check if it exists\n",
    "except ImportError:\n",
    "    print(f\"{required_package} not found. Installing...\")\n",
    "    install_package(required_package)\n",
    "\n",
    "# Set path to the JSON key file for authentication\n",
    "key_file_path = \"JSON_KEY.json\"  # Replace with the actual path to your JSON key file\n",
    "os.environ[\"GOOGLE_APPLICATION_CREDENTIALS\"] = key_file_path\n",
    "\n",
    "# 1. Create a directory named 'dags' inside a folder 'BI'\n",
    "base_path = \"BI\"\n",
    "dags_path = os.path.join(base_path, \"dags\")\n",
    "os.makedirs(dags_path, exist_ok=True)\n",
    "\n",
    "# 2. Create another folder inside 'dags' named 'fb_ads_warehouse'\n",
    "fb_ads_path = os.path.join(dags_path, \"fb_ads_warehouse\")\n",
    "os.makedirs(fb_ads_path, exist_ok=True)\n",
    "\n",
    "# 3. Inside 'fb_ads_warehouse', create two folders 'dag' and 'sql'\n",
    "dag_folder = os.path.join(fb_ads_path, \"dag\")\n",
    "sql_folder = os.path.join(fb_ads_path, \"sql\")\n",
    "os.makedirs(dag_folder, exist_ok=True)\n",
    "os.makedirs(sql_folder, exist_ok=True)\n",
    "\n",
    "# 4. Inside the 'sql' folder, create three folders: 'data_model_master', 'datawarehouse_sanity_check', and 'fb_ads_to_bq'\n",
    "big_query_folder = \"fb_ads_to_bq\"    # Give the name of the folder that will contain the create and append sql codes\n",
    "folders = [\"data_model_master\", \"datawarehouse_sanity_check\", big_query_folder]\n",
    "for folder in folders:\n",
    "    os.makedirs(os.path.join(sql_folder, folder), exist_ok=True)\n",
    "\n",
    "# 4.1 Create specific files as per the requirements\n",
    "# Create an empty \"dummy_dag.py\" inside the 'dag' folder\n",
    "dummy_dag_path = os.path.join(dag_folder, \"dummy_dag.py\")\n",
    "with open(dummy_dag_path, \"w\") as f:\n",
    "    pass\n",
    "\n",
    "# Create an empty \"dummy_sanity_check.sql\" inside 'datawarehouse_sanity_check'\n",
    "sanity_check_path = os.path.join(sql_folder, \"datawarehouse_sanity_check\", \"dummy_sanity_check.sql\")\n",
    "with open(sanity_check_path, \"w\") as f:\n",
    "    pass\n",
    "\n",
    "# Create two empty SQL files inside 'data_model_master': \"dummy_master_append.sql\" and \"dummy_master_create.sql\"\n",
    "data_model_master_path = os.path.join(sql_folder, \"data_model_master\")\n",
    "for file_name in [\"dummy_master_append.sql\", \"dummy_master_create.sql\"]:\n",
    "    file_path = os.path.join(data_model_master_path, file_name)\n",
    "    with open(file_path, \"w\") as f:\n",
    "        pass\n",
    "\n",
    "# 5. Use BigQuery to get the table names\n",
    "project_id = \"shopify-pubsub-project\"  # Replace with your Google Cloud Project ID\n",
    "dataset_id = \"Data_Warehouse_Facebook_Ads_Staging\"  # Replace with your dataset ID\n",
    "big_query_folder_path = os.path.join(sql_folder, big_query_folder)\n",
    "\n",
    "try:\n",
    "    # Initialize BigQuery client\n",
    "    client = bigquery.Client()\n",
    "\n",
    "    # Query to list table names in the dataset\n",
    "    query = f\"\"\"\n",
    "    SELECT table_name \n",
    "    FROM `{project_id}.{dataset_id}.INFORMATION_SCHEMA.TABLES`\n",
    "    \"\"\"\n",
    "    df = client.query(query).to_dataframe()\n",
    "\n",
    "    # Get table names from the dataframe\n",
    "    table_names = df[\"table_name\"].tolist()\n",
    "\n",
    "    # 6. Create folders for each table name and add specific SQL files\n",
    "    for table_name in table_names:\n",
    "        table_folder_path = os.path.join(big_query_folder_path, table_name)\n",
    "        os.makedirs(table_folder_path, exist_ok=True)\n",
    "\n",
    "        # Create specific SQL files inside each folder\n",
    "        create_file_path = os.path.join(table_folder_path, f\"{table_name}_create.sql\")\n",
    "        append_file_path = os.path.join(table_folder_path, f\"{table_name}_append.sql\")\n",
    "        for file_path in [create_file_path, append_file_path]:\n",
    "            with open(file_path, \"w\") as f:\n",
    "                pass\n",
    "\n",
    "    print(\"Folder structure and required files created successfully!\")\n",
    "\n",
    "except Exception as e:\n",
    "    print(f\"An error occurred: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4d49c7ea-7fc8-4854-b98c-485027140c75",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
