create or replace table `shopify-pubsub-project.Data_Warehouse_Facebook_Ads_Staging.ads_insights_normal`
partition by date_trunc(_airbyte_extracted_at, day)
as
  select
    created_time,
    date_start,
    date_stop,
    updated_time,
    clicks,
    impressions,
    inline_link_clicks,
    inline_post_engagement,
    reach,
    unique_clicks,
    unique_inline_link_clicks,
    canvas_avg_view_percent,
    canvas_avg_view_time,
    cost_per_estimated_ad_recallers,
    cost_per_inline_link_click,
    cost_per_inline_post_engagement,
    cost_per_unique_click,
    cost_per_unique_inline_link_click,
    cpc,
    cpm,
    cpp,
    ctr,
    estimated_ad_recallers,
    frequency,
    full_view_impressions,
    full_view_reach,
    inline_link_click_ctr,
    instant_experience_clicks_to_open,
    instant_experience_clicks_to_start,
    qualifying_question_qualify_answer_rate,
    social_spend,
    spend,
    unique_ctr,
    unique_inline_link_click_ctr,
    unique_link_clicks_ctr,
    account_currency,
    account_id,
    account_name,
    ad_id,
    ad_name,
    adset_id,
    adset_name,
    buying_type,
    campaign_id,
    campaign_name,
    conversion_rate_ranking,
    engagement_rate_ranking,
    objective,
    optimization_goal,
    quality_ranking,
    _airbyte_extracted_at
  from
  (
    select
    *,
    row_number() over(partition by ad_id,date_start order by _airbyte_extracted_at desc) as row_num
    from
    shopify-pubsub-project.pilgrim_bi_airbyte_facebook.ads_insights
  )
  where row_num = 1