merge into `shopify-pubsub-project.Data_Warehouse_Facebook_Ads_Staging.ads_insights_normal` as target
using
(
  select
    created_time,
    date_start,
    date_stop,
    updated_time,
    clicks,
    impressions,
    inline_link_clicks,
    inline_post_engagement,
    reach,
    unique_clicks,
    unique_inline_link_clicks,
    canvas_avg_view_percent,
    canvas_avg_view_time,
    cost_per_estimated_ad_recallers,
    cost_per_inline_link_click,
    cost_per_inline_post_engagement,
    cost_per_unique_click,
    cost_per_unique_inline_link_click,
    cpc,
    cpm,
    cpp,
    ctr,
    estimated_ad_recallers,
    frequency,
    full_view_impressions,
    full_view_reach,
    inline_link_click_ctr,
    instant_experience_clicks_to_open,
    instant_experience_clicks_to_start,
    qualifying_question_qualify_answer_rate,
    social_spend,
    spend,
    unique_ctr,
    unique_inline_link_click_ctr,
    unique_link_clicks_ctr,
    account_currency,
    account_id,
    account_name,
    ad_id,
    ad_name,
    adset_id,
    adset_name,
    buying_type,
    campaign_id,
    campaign_name,
    conversion_rate_ranking,
    engagement_rate_ranking,
    objective,
    optimization_goal,
    quality_ranking,
    _airbyte_extracted_at
  from
  (
    select
    *,
    row_number() over(partition by ad_id,date_start order by _airbyte_extracted_at desc) as row_num
    from
    shopify-pubsub-project.pilgrim_bi_airbyte_facebook.ads_insights
  )
  where row_num = 1 and date(_airbyte_extracted_at) >= date_sub(current_date("Asia/Kolkata"), interval 10 day)
) as source
on target.ad_id = source.ad_id
and target.date_start = source.date_start
when matched and target._airbyte_extracted_at < source._airbyte_extracted_at
then update set
  target.created_time = source.created_time,
  target.date_start = source.date_start,
  target.date_stop = source.date_stop,
  target.updated_time = source.updated_time,
  target.clicks = source.clicks,
  target.impressions = source.impressions,
  target.inline_link_clicks = source.inline_link_clicks,
  target.inline_post_engagement = source.inline_post_engagement,
  target.reach = source.reach,
  target.unique_clicks = source.unique_clicks,
  target.unique_inline_link_clicks = source.unique_inline_link_clicks,
  target.canvas_avg_view_percent = source.canvas_avg_view_percent,
  target.canvas_avg_view_time = source.canvas_avg_view_time,
  target.cost_per_estimated_ad_recallers = source.cost_per_estimated_ad_recallers,
  target.cost_per_inline_link_click = source.cost_per_inline_link_click,
  target.cost_per_inline_post_engagement = source.cost_per_inline_post_engagement,
  target.cost_per_unique_click = source.cost_per_unique_click,
  target.cost_per_unique_inline_link_click = source.cost_per_unique_inline_link_click,
  target.cpc = source.cpc,
  target.cpm = source.cpm,
  target.cpp = source.cpp,
  target.ctr = source.ctr,
  target.estimated_ad_recallers = source.estimated_ad_recallers,
  target.frequency = source.frequency,
  target.full_view_impressions = source.full_view_impressions,
  target.full_view_reach = source.full_view_reach,
  target.inline_link_click_ctr = source.inline_link_click_ctr,
  target.instant_experience_clicks_to_open = source.instant_experience_clicks_to_open,
  target.instant_experience_clicks_to_start = source.instant_experience_clicks_to_start,
  target.qualifying_question_qualify_answer_rate = source.qualifying_question_qualify_answer_rate,
  target.social_spend = source.social_spend,
  target.spend = source.spend,
  target.unique_ctr = source.unique_ctr,
  target.unique_inline_link_click_ctr = source.unique_inline_link_click_ctr,
  target.unique_link_clicks_ctr = source.unique_link_clicks_ctr,
  target.account_currency = source.account_currency,
  target.account_id = source.account_id,
  target.account_name = source.account_name,
  target.ad_id = source.ad_id,
  target.ad_name = source.ad_name,
  target.adset_id = source.adset_id,
  target.adset_name = source.adset_name,
  target.buying_type = source.buying_type,
  target.campaign_id = source.campaign_id,
  target.campaign_name = source.campaign_name,
  target.conversion_rate_ranking = source.conversion_rate_ranking,
  target.engagement_rate_ranking = source.engagement_rate_ranking,
  target.objective = source.objective,
  target.optimization_goal = source.optimization_goal,
  target.quality_ranking = source.quality_ranking,
  target._airbyte_extracted_at = source._airbyte_extracted_at
when not matched
then insert
(
  created_time,
  date_start,
  date_stop,
  updated_time,
  clicks,
  impressions,
  inline_link_clicks,
  inline_post_engagement,
  reach,
  unique_clicks,
  unique_inline_link_clicks,
  canvas_avg_view_percent,
  canvas_avg_view_time,
  cost_per_estimated_ad_recallers,
  cost_per_inline_link_click,
  cost_per_inline_post_engagement,
  cost_per_unique_click,
  cost_per_unique_inline_link_click,
  cpc,
  cpm,
  cpp,
  ctr,
  estimated_ad_recallers,
  frequency,
  full_view_impressions,
  full_view_reach,
  inline_link_click_ctr,
  instant_experience_clicks_to_open,
  instant_experience_clicks_to_start,
  qualifying_question_qualify_answer_rate,
  social_spend,
  spend,
  unique_ctr,
  unique_inline_link_click_ctr,
  unique_link_clicks_ctr,
  account_currency,
  account_id,
  account_name,
  ad_id,
  ad_name,
  adset_id,
  adset_name,
  buying_type,
  campaign_id,
  campaign_name,
  conversion_rate_ranking,
  engagement_rate_ranking,
  objective,
  optimization_goal,
  quality_ranking,
  _airbyte_extracted_at
)
values
(
  source.created_time,
  source.date_start,
  source.date_stop,
  source.updated_time,
  source.clicks,
  source.impressions,
  source.inline_link_clicks,
  source.inline_post_engagement,
  source.reach,
  source.unique_clicks,
  source.unique_inline_link_clicks,
  source.canvas_avg_view_percent,
  source.canvas_avg_view_time,
  source.cost_per_estimated_ad_recallers,
  source.cost_per_inline_link_click,
  source.cost_per_inline_post_engagement,
  source.cost_per_unique_click,
  source.cost_per_unique_inline_link_click,
  source.cpc,
  source.cpm,
  source.cpp,
  source.ctr,
  source.estimated_ad_recallers,
  source.frequency,
  source.full_view_impressions,
  source.full_view_reach,
  source.inline_link_click_ctr,
  source.instant_experience_clicks_to_open,
  source.instant_experience_clicks_to_start,
  source.qualifying_question_qualify_answer_rate,
  source.social_spend,
  source.spend,
  source.unique_ctr,
  source.unique_inline_link_click_ctr,
  source.unique_link_clicks_ctr,
  source.account_currency,
  source.account_id,
  source.account_name,
  source.ad_id,
  source.ad_name,
  source.adset_id,
  source.adset_name,
  source.buying_type,
  source.campaign_id,
  source.campaign_name,
  source.conversion_rate_ranking,
  source.engagement_rate_ranking,
  source.objective,
  source.optimization_goal,
  source.quality_ranking,
  source._airbyte_extracted_at
)