MERGE INTO `` AS TARGET
USING
(
SELECT
  warehouseLocation,
  poNo,
  CAST(poDate AS DATETIME) AS poDate,
  CAST(Mrp AS FLOAT64) AS Mrp,
  poRef,
  grnNo,
  CAST(grnDetailsDate AS DATETIME) AS grnDetailsDate,
  vendorName,
  vendorInvoiceNo,
  CAST(vendorInvoiceDate AS DATETIME) AS vendorInvoiceDate,
  productName,
  companyProductId,
  sku,
  ean,
  CAST(unitPrice AS FLOAT64) AS unitPrice,
  CAST(taxableAmount AS FLOAT64) AS taxableAmount,
  poStatus,
  CAST(poQty AS FLOAT64) AS poQty,
  CAST(receivedQty AS FLOAT64) AS receivedQty,
  CAST(receivedValue AS FLOAT64) AS receivedValue,
  userName,
  batchCode,
  CAST(exipryDate AS DATETIME) AS exipryDate,
  report_id,
  report_type,
  start_date,
  end_date,
  created_on,
  inventory_type,
  ee_extracted_at
FROM
(
SELECT
*,
ROW_NUMBER() OVER(PARTITON BY ORDER BY _airbyte_extracted_at) as row_num
FROM `shopify-pubsub-project.easycom.grn_details_report`
WHERE DATE(_airbyte_extracted_at) >= DATE_SUB(CURRENT_DATE("Asia/Kolkata"), INTERVAL 10 DAY)
)
WHERE row_num = 1 -- Keep only the most recent row per customer_id and segments_date
) AS SOURCE
ON SOURCE. = TARGET.
WHEN MATCHED AND TARGET.ee_extracted_at < SOURCE.ee_extracted_at
THEN UPDATE SET
TARGET.warehouseLocation = SOURCE.warehouseLocation,
TARGET.poNo = SOURCE.poNo,
TARGET.CAST(poDate AS DATETIME) AS poDate = SOURCE.CAST(poDate AS DATETIME) AS poDate,
TARGET.CAST(Mrp AS FLOAT64) AS Mrp = SOURCE.CAST(Mrp AS FLOAT64) AS Mrp,
TARGET.poRef = SOURCE.poRef,
TARGET.grnNo = SOURCE.grnNo,
TARGET.CAST(grnDetailsDate AS DATETIME) AS grnDetailsDate = SOURCE.CAST(grnDetailsDate AS DATETIME) AS grnDetailsDate,
TARGET.vendorName = SOURCE.vendorName,
TARGET.vendorInvoiceNo = SOURCE.vendorInvoiceNo,
TARGET.CAST(vendorInvoiceDate AS DATETIME) AS vendorInvoiceDate = SOURCE.CAST(vendorInvoiceDate AS DATETIME) AS vendorInvoiceDate,
TARGET.productName = SOURCE.productName,
TARGET.companyProductId = SOURCE.companyProductId,
TARGET.sku = SOURCE.sku,
TARGET.ean = SOURCE.ean,
TARGET.CAST(unitPrice AS FLOAT64) AS unitPrice = SOURCE.CAST(unitPrice AS FLOAT64) AS unitPrice,
TARGET.CAST(taxableAmount AS FLOAT64) AS taxableAmount = SOURCE.CAST(taxableAmount AS FLOAT64) AS taxableAmount,
TARGET.poStatus = SOURCE.poStatus,
TARGET.CAST(poQty AS FLOAT64) AS poQty = SOURCE.CAST(poQty AS FLOAT64) AS poQty,
TARGET.CAST(receivedQty AS FLOAT64) AS receivedQty = SOURCE.CAST(receivedQty AS FLOAT64) AS receivedQty,
TARGET.CAST(receivedValue AS FLOAT64) AS receivedValue = SOURCE.CAST(receivedValue AS FLOAT64) AS receivedValue,
TARGET.userName = SOURCE.userName,
TARGET.batchCode = SOURCE.batchCode,
TARGET.CAST(exipryDate AS DATETIME) AS exipryDate = SOURCE.CAST(exipryDate AS DATETIME) AS exipryDate,
TARGET.report_id = SOURCE.report_id,
TARGET.report_type = SOURCE.report_type,
TARGET.start_date = SOURCE.start_date,
TARGET.end_date = SOURCE.end_date,
TARGET.created_on = SOURCE.created_on,
TARGET.inventory_type = SOURCE.inventory_type,
TARGET.ee_extracted_a = SOURCE.ee_extracted_at
WHEN NOT MATCHED
THEN INSERT
(
  warehouseLocation,
  poNo,
  poDate,
  Mrp,
  poRef,
  grnNo,
  grnDetailsDate,
  vendorName,
  vendorInvoiceNo,
  vendorInvoiceDate,
  productName,
  companyProductId,
  sku,
  ean,
  unitPrice,
  taxableAmount,
  poStatus,
  poQty,
  receivedQty,
  receivedValue,
  userName,
  batchCode,
  exipryDate,
  report_id,
  report_type,
  start_date,
  end_date,
  created_on,
  inventory_type,
  ee_extracted_at
)
VALUES
(
SOURCE.warehouseLocation,
SOURCE.poNo,
SOURCE.CAST(poDate AS DATETIME) AS poDate,
SOURCE.CAST(Mrp AS FLOAT64) AS Mrp,
SOURCE.poRef,
SOURCE.grnNo,
SOURCE.CAST(grnDetailsDate AS DATETIME) AS grnDetailsDate,
SOURCE.vendorName,
SOURCE.vendorInvoiceNo,
SOURCE.CAST(vendorInvoiceDate AS DATETIME) AS vendorInvoiceDate,
SOURCE.productName,
SOURCE.companyProductId,
SOURCE.sku,
SOURCE.ean,
SOURCE.CAST(unitPrice AS FLOAT64) AS unitPrice,
SOURCE.CAST(taxableAmount AS FLOAT64) AS taxableAmount,
SOURCE.poStatus,
SOURCE.CAST(poQty AS FLOAT64) AS poQty,
SOURCE.CAST(receivedQty AS FLOAT64) AS receivedQty,
SOURCE.CAST(receivedValue AS FLOAT64) AS receivedValue,
SOURCE.userName,
SOURCE.batchCode,
SOURCE.CAST(exipryDate AS DATETIME) AS exipryDate,
SOURCE.report_id,
SOURCE.report_type,
SOURCE.start_date,
SOURCE.end_date,
SOURCE.created_on,
SOURCE.inventory_type,
SOURCE.ee_extracted_a

)
