CREATE OR REPLACE TABLE `shopify-pubsub-project.Data_Warehouse_GoogleAds_Staging.ad_listing_group_criterion`
PARTITION BY DATE_TRUNC(_airbyte_extracted_at, DAY)
AS
SELECT
_airbyte_extracted_at,
_airbyte_generation_id,
_airbyte_meta,
_airbyte_raw_id,
ad_group_criterion_criterion_id,
ad_group_criterion_listing_group_case_value_product_category_level,
ad_group_criterion_listing_group_case_value_product_channel_channel,
ad_group_criterion_listing_group_case_value_product_channel_exclusivity_channel_exclusivity,
ad_group_criterion_listing_group_case_value_product_condition_condition,
ad_group_criterion_listing_group_case_value_product_custom_attribute_index,
ad_group_criterion_listing_group_case_value_product_custom_attribute_value,
ad_group_criterion_listing_group_case_value_product_item_id_value,
ad_group_criterion_listing_group_case_value_product_type_level,
ad_group_criterion_listing_group_case_value_product_type_value,
ad_group_criterion_listing_group_parent_ad_group_criterion,
ad_group_criterion_listing_group_type,
ad_group_criterion_resource_name,
ad_group_id,
change_status_last_change_date_time,
deleted_at,
FROM
  shopify-pubsub-project.pilgrim_bi_google_ads.ad_listing_group_criterion
