
MERGE INTO `shopify-pubsub-project.Data_Warehouse_Easyecom_Staging.Orderitem` AS target

USING (
SELECT
distinct
  SAFE_CAST(order_id as STRING) as order_id,
  SAFE_CAST(invoice_id as STRING) as invoice_id,
  order_date,
  order_status,
  SAFE_CAST(JSON_EXTRACT_SCALAR(suborder_flat,'$[suborder_id]') as STRING) AS suborder_id,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[suborder_num]') AS suborder_num,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[reference_code]') AS reference_code,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[item_status]') AS item_status,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[shipment_type]') AS shipment_type,
  SAFE_CAST(JSON_EXTRACT_SCALAR(suborder_flat,'$[suborder_quantity]') as FLOAT64) AS suborder_quantity,
  SAFE_CAST(JSON_EXTRACT_SCALAR(suborder_flat,'$[item_quantity]') as FLOAT64) AS item_quantity,
  SAFE_CAST(JSON_EXTRACT_SCALAR(suborder_flat,'$[returned_quantity]') as FLOAT64) AS returned_quantity,
  SAFE_CAST(JSON_EXTRACT_SCALAR(suborder_flat,'$[cancelled_quantity]') as FLOAT64) AS cancelled_quantity,
  SAFE_CAST(JSON_EXTRACT_SCALAR(suborder_flat,'$[shipped_quantity]') as FLOAT64) AS shipped_quantity,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[batch_codes]') AS batch_codes,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[serial_nums]') AS serial_nums,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[batchcode_serial]') AS batchcode_serial,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[batchcode_expiry]') AS batchcode_expiry,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[tax_type]') AS tax_type,
  SAFE_CAST(JSON_EXTRACT_SCALAR(suborder_flat,'$[suborder_history].qc_pass_datetime') as datetime) AS qc_pass_datetime,
  SAFE_CAST(JSON_EXTRACT_SCALAR(suborder_flat,'$[suborder_history].confirm_datetime') as datetime) AS confirm_datetime,
  SAFE_CAST(JSON_EXTRACT_SCALAR(suborder_flat,'$[suborder_history].print_datetime') as datetime) AS print_datetime,
  SAFE_CAST(JSON_EXTRACT_SCALAR(suborder_flat,'$[suborder_history].manifest_datetime') as datetime) AS manifest_datetime,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[meta]') AS meta,
  SAFE_CAST(JSON_EXTRACT_SCALAR(suborder_flat,'$[selling_price]') as FLOAT64) AS selling_price,
  SAFE_CAST(JSON_EXTRACT_SCALAR(suborder_flat,'$[total_shipping_charge]') as FLOAT64) AS total_shipping_charge,
  SAFE_CAST(JSON_EXTRACT_SCALAR(suborder_flat,'$[total_miscellaneous]') as FLOAT64) AS total_miscellaneous,
  SAFE_CAST(JSON_EXTRACT_SCALAR(suborder_flat,'$[tax_rate]') as FLOAT64) AS tax_rate,
  SAFE_CAST(JSON_EXTRACT_SCALAR(suborder_flat,'$[tax]') as FLOAT64) AS tax,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[product_id]') AS product_id,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[company_product_id]') AS company_product_id,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[sku]') AS sku,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[sku_type]') AS sku_type,
  SAFE_CAST(JSON_EXTRACT_SCALAR(suborder_flat,'$[sub_product_count]') as FLOAT64) AS sub_product_count,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[marketplace_sku]') AS marketplace_sku,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[productName]') AS productName,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[Identifier]') AS Identifier,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[description]') AS description,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[category]') AS category,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[brand]') AS brand,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[model_no]') AS model_no,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[product_tax_code]') AS product_tax_code,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[AccountingSku]') AS AccountingSku,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[accounting_unit]') AS accounting_unit,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[ean]') AS ean,
  JSON_EXTRACT_SCALAR(suborder_flat,'$[size]') AS size,
  SAFE_CAST(JSON_EXTRACT_SCALAR(suborder_flat,'$[cost]') as FLOAT64) AS cost,
  SAFE_CAST(JSON_EXTRACT_SCALAR(suborder_flat,'$[mrp]') as FLOAT64) AS mrp,
  SAFE_CAST(JSON_EXTRACT_SCALAR(suborder_flat,'$[weight]') as FLOAT64) AS weight,
  SAFE_CAST(JSON_EXTRACT_SCALAR(suborder_flat,'$[length]') as FLOAT64) AS length,
  SAFE_CAST(JSON_EXTRACT_SCALAR(suborder_flat,'$[width]') as FLOAT64) AS width,
  SAFE_CAST(JSON_EXTRACT_SCALAR(suborder_flat,'$[height]') as FLOAT64) AS height,
  SAFE_CAST(JSON_EXTRACT_SCALAR(suborder_flat,'$[scheme_applied]') as FLOAT64) AS scheme_applied,
  ee_extracted_at,
  
  FROM
    (
      SELECT
        order_id,
        order_date,
        order_status,
        ee_extracted_at,
        invoice_id,
        JSON_QUERY_ARRAY(suborders,'$[0]') AS suborder_array,
        row_number() over(partition by invoice_id order by last_update_date desc,ee_extracted_at desc) as ranking,
      FROM
        `shopify-pubsub-project.easycom.orders`),UNNEST(suborder_array) AS suborder_flat

  WHERE ranking=1 and date(order_date) >= DATE_SUB(CURRENT_DATE("Asia/Kolkata"), INTERVAL 30 DAY
  
  )
 

 ) AS source
ON target.order_id = source.order_id
and target.suborder_id = source.suborder_id
and target.invoice_id = source.invoice_id

WHEN MATCHED THEN UPDATE SET
target.order_id = source.order_id,
target.invoice_id = source.invoice_id,
target.order_date = source.order_date,
target.order_status = source.order_status,
target.suborder_id = source.suborder_id,
target.suborder_num = source.suborder_num,
target.reference_code = source.reference_code,
target.item_status = source.item_status,
target.shipment_type = source.shipment_type,
target.suborder_quantity = source.suborder_quantity,
target.item_quantity = source.item_quantity,
target.returned_quantity = source.returned_quantity,
target.cancelled_quantity = source.cancelled_quantity,
target.shipped_quantity = source.shipped_quantity,
target.batch_codes = source.batch_codes,
target.serial_nums = source.serial_nums,
target.batchcode_serial = source.batchcode_serial,
target.batchcode_expiry = source.batchcode_expiry,
target.tax_type = source.tax_type,
target.qc_pass_datetime = source.qc_pass_datetime,
target.confirm_datetime = source.confirm_datetime,
target.print_datetime = source.print_datetime,
target.manifest_datetime = source.manifest_datetime,
target.meta = source.meta,
target.selling_price = source.selling_price,
target.total_shipping_charge = source.total_shipping_charge,
target.total_miscellaneous = source.total_miscellaneous,
target.tax_rate = source.tax_rate,
target.tax = source.tax,
target.product_id = source.product_id,
target.company_product_id = source.company_product_id,
target.sku = source.sku,
target.sku_type = source.sku_type,
target.sub_product_count = source.sub_product_count,
target.marketplace_sku = source.marketplace_sku,
target.productName = source.productName,
target.Identifier = source.Identifier,
target.description = source.description,
target.category = source.category,
target.brand = source.brand,
target.model_no = source.model_no,
target.product_tax_code = source.product_tax_code,
target.AccountingSku = source.AccountingSku,
target.accounting_unit = source.accounting_unit,
target.ean = source.ean,
target.size = source.size,
target.cost = source.cost,
target.mrp = source.mrp,
target.weight = source.weight,
target.length = source.length,
target.width = source.width,
target.height = source.height,
target.scheme_applied = source.scheme_applied,
target.ee_extracted_at = source.ee_extracted_at

WHEN NOT MATCHED THEN INSERT (
order_id,
invoice_id,
order_date,
order_status,
suborder_id,
suborder_num,
reference_code,
item_status,
shipment_type,
suborder_quantity,
item_quantity,
returned_quantity,
cancelled_quantity,
shipped_quantity,
batch_codes,
serial_nums,
batchcode_serial,
batchcode_expiry,
tax_type,
qc_pass_datetime,
confirm_datetime,
print_datetime,
manifest_datetime,
meta,
selling_price,
total_shipping_charge,
total_miscellaneous,
tax_rate,
tax,
product_id,
company_product_id,
sku,
sku_type,
sub_product_count,
marketplace_sku,
productName,
Identifier,
description,
category,
brand,
model_no,
product_tax_code,
AccountingSku,
accounting_unit,
ean,
size,
cost,
mrp,
weight,
length,
width,
height,
scheme_applied,
ee_extracted_at

)
  VALUES (
source.order_id,
source.invoice_id,
source.order_date,
source.order_status,
source.suborder_id,
source.suborder_num,
source.reference_code,
source.item_status,
source.shipment_type,
source.suborder_quantity,
source.item_quantity,
source.returned_quantity,
source.cancelled_quantity,
source.shipped_quantity,
source.batch_codes,
source.serial_nums,
source.batchcode_serial,
source.batchcode_expiry,
source.tax_type,
source.qc_pass_datetime,
source.confirm_datetime,
source.print_datetime,
source.manifest_datetime,
source.meta,
source.selling_price,
source.total_shipping_charge,
source.total_miscellaneous,
source.tax_rate,
source.tax,
source.product_id,
source.company_product_id,
source.sku,
source.sku_type,
source.sub_product_count,
source.marketplace_sku,
source.productName,
source.Identifier,
source.description,
source.category,
source.brand,
source.model_no,
source.product_tax_code,
source.AccountingSku,
source.accounting_unit,
source.ean,
source.size,
source.cost,
source.mrp,
source.weight,
source.length,
source.width,
source.height,
source.scheme_applied,
source.ee_extracted_at

)