merge into `shopify-pubsub-project.Data_Warehouse_Facebook_Ads_Staging.ads_insights_action_product_id_normal` as target
using
(
SELECT
  _airbyte_extracted_at,
  cpc,
  cpm,
  ctr,
  ad_id,
  date_start,
  spend,
  clicks,
  ad_name,
  adset_id,
  date_stop,
  objective,
  account_id,
  adset_name,
  product_id,
  buying_type,
  campaign_id,
  impressions,
  account_name,
  created_time,
  updated_time,
  campaign_name,
  account_currency,
  optimization_goal,
  inline_link_clicks,
  full_view_impressions,
  inline_link_click_ctr,
  inline_post_engagement,
  cost_per_inline_link_click,
  cost_per_inline_post_engagement,


  -- website_ctr, --NORMAL
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(website_ctr, '$[0]'), '$.action_type') AS website_ctr_action_type,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(website_ctr, '$[0]'), '$.value') AS website_ctr_value,


  -- outbound_clicks,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(outbound_clicks, '$[0]'), '$.action_type') AS outbound_clicks_action_type,  
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(outbound_clicks, '$[0]'), '$.value') AS outbound_clicks_value,


  -- outbound_clicks_ctr,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(outbound_clicks_ctr, '$[0]'), '$.action_type') AS outbound_clicks_ctr_action_type,  
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(outbound_clicks_ctr, '$[0]'), '$.value') AS outbound_clicks_ctr_value,


  -- cost_per_outbound_click,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(cost_per_outbound_click, '$[0]'), '$.action_type') AS cost_per_outbound_click_action_type,  
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(cost_per_outbound_click, '$[0]'), '$.value') AS cost_per_outbound_click_value,


  -- mobile_app_purchase_roas,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(mobile_app_purchase_roas, '$[0]'), '$.action_type') AS mobile_app_purchase_roas_action_type,  
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(mobile_app_purchase_roas, '$[0]'), '$.value') AS mobile_app_purchase_roas_value,
FROM
(
select
*,
row_number() over(partition by ad_id,date_start,product_id order by _airbyte_extracted_at desc) as rn
from shopify-pubsub-project.pilgrim_bi_airbyte_facebook.ads_insights_action_product_id
)
where rn = 1 and date(_airbyte_extracted_at) >= date_sub(current_date("Asia/Kolkata"), INTERVAL 10 day)
) as source
on target.ad_id = source.ad_id
and target.date_start = source.date_start
and target.product_id = source.product_id
when matched and target.date_start < source.date_start
then update set
target._airbyte_extracted_at = source._airbyte_extracted_at,
target.cpc = source.cpc,
target.cpm = source.cpm,
target.ctr = source.ctr,
target.ad_id = source.ad_id,
target.date_start = source.date_start,
target.spend = source.spend,
target.clicks = source.clicks,
target.ad_name = source.ad_name,
target.adset_id = source.adset_id,
target.date_stop = source.date_stop,
target.objective = source.objective,
target.account_id = source.account_id,
target.adset_name = source.adset_name,
target.product_id = source.product_id,
target.buying_type = source.buying_type,
target.campaign_id = source.campaign_id,
target.impressions = source.impressions,
target.account_name = source.account_name,
target.created_time = source.created_time,
target.updated_time = source.updated_time,
target.campaign_name = source.campaign_name,
target.account_currency = source.account_currency,
target.optimization_goal = source.optimization_goal,
target.inline_link_clicks = source.inline_link_clicks,
target.full_view_impressions = source.full_view_impressions,
target.inline_link_click_ctr = source.inline_link_click_ctr,
target.inline_post_engagement = source.inline_post_engagement,
target.cost_per_inline_link_click = source.cost_per_inline_link_click,
target.cost_per_inline_post_engagement = source.cost_per_inline_post_engagement,
target.website_ctr_action_type = source.website_ctr_action_type,
target.website_ctr_value = source.website_ctr_value,
target.outbound_clicks_action_type = source.outbound_clicks_action_type,
target.outbound_clicks_value = source.outbound_clicks_value,
target.outbound_clicks_ctr_action_type = source.outbound_clicks_ctr_action_type,
target.outbound_clicks_ctr_value = source.outbound_clicks_ctr_value,
target.cost_per_outbound_click_action_type = source.cost_per_outbound_click_action_type,
target.cost_per_outbound_click_value = source.cost_per_outbound_click_value,
target.mobile_app_purchase_roas_action_type = source.mobile_app_purchase_roas_action_type,
target.mobile_app_purchase_roas_value = source.mobile_app_purchase_roas_value
when not matched
then insert
(
  _airbyte_extracted_at,
  cpc,
  cpm,
  ctr,
  ad_id,
  date_start,
  spend,
  clicks,
  ad_name,
  adset_id,
  date_stop,
  objective,
  account_id,
  adset_name,
  product_id,
  buying_type,
  campaign_id,
  impressions,
  account_name,
  created_time,
  updated_time,
  campaign_name,
  account_currency,
  optimization_goal,
  inline_link_clicks,
  full_view_impressions,
  inline_link_click_ctr,
  inline_post_engagement,
  cost_per_inline_link_click,
  cost_per_inline_post_engagement,
  website_ctr_action_type,
  website_ctr_value,
  outbound_clicks_action_type,  
  outbound_clicks_value,
  outbound_clicks_ctr_action_type,  
  outbound_clicks_ctr_value,
  cost_per_outbound_click_action_type,  
  cost_per_outbound_click_value,
  mobile_app_purchase_roas_action_type,  
  mobile_app_purchase_roas_value
)
values
(
source._airbyte_extracted_at,
source.cpc,
source.cpm,
source.ctr,
source.ad_id,
source.date_start,
source.spend,
source.clicks,
source.ad_name,
source.adset_id,
source.date_stop,
source.objective,
source.account_id,
source.adset_name,
source.product_id,
source.buying_type,
source.campaign_id,
source.impressions,
source.account_name,
source.created_time,
source.updated_time,
source.campaign_name,
source.account_currency,
source.optimization_goal,
source.inline_link_clicks,
source.full_view_impressions,
source.inline_link_click_ctr,
source.inline_post_engagement,
source.cost_per_inline_link_click,
source.cost_per_inline_post_engagement,
source.website_ctr_action_type,
source.website_ctr_value,
source.outbound_clicks_action_type,
source.outbound_clicks_value,
source.outbound_clicks_ctr_action_type,
source.outbound_clicks_ctr_value,
source.cost_per_outbound_click_action_type,
source.cost_per_outbound_click_value,
source.mobile_app_purchase_roas_action_type,
source.mobile_app_purchase_roas_value
)