MERGE INTO `shopify-pubsub-project.Data_Warehouse_ClickPost_Staging.Tracking` AS target
USING (
  SELECT
    `Order ID`,
    `Created at`,
    `Pickup Date`,
    `Current Location`,
    `Latest Timestamp`,
    `Latest Remark`,
    `Delivery Date`,
    `Updated at`,
    `Expected delivery date by Courier Partner`,
    `Expected Date Of Delivery Min`,
    `Expected Date Of Delivery Max`,
    `Out For Delivery 1st Attempt`,
    `Out For Delivery 2nd Attempt`,
    `Out For Delivery 3rd Attempt`,
    `Out For Delivery 4th Attempt`,
    `Out For Delivery 5th Attempt`,
    `Out For Delivery Attempts`,
    `Reason For Last Failed Delivery`,
    `TimeStamp Of Last Failed Delivery`,
    `Remark Of Last Failed Delivery`,
    `Is shipment stuck in lifecycle`,
    `RTO Mark Date`,
    `Out For Pickup 1st Attempt`,
    `Out For Pickup 2nd Attempt`,
    `Out For Pickup 3rd Attempt`,
    `Out For Pickup Attempts`,
    `Destination Hub In Scan Time`,
    `Origin Hub In Timestamp`,
    `Origin Hub Out Timestamp`,
    `RTO Intransit Timestamp`,
    `RTO Delivery Date`,
    `Original Appointment Start Time`,
    `Original Appointment End Time`,
    `Current Appointment Start Time`,
    `Current Appointment End Time`,
    `Ingestion Date`
  FROM (
    SELECT
      *,
      ROW_NUMBER() OVER(PARTITION BY `Order ID` ORDER BY `Ingestion Date` DESC) AS row_num
    FROM `shopify-pubsub-project.clickpost_data.tracking`
  )
  WHERE row_num = 1
) AS source
ON target.Order_ID = source.`Order ID`
WHEN MATCHED AND source.`Ingestion Date` > target.Ingestion_Date THEN
  UPDATE SET
    target.Order_ID =                                  source.`Order ID`,                                  
    target.Created_at =                                source.`Created at`,
    target.Pickup_Date =                               source.`Pickup Date`,
    target.Current_Location =                          source.`Current Location`,
    target.Latest_Timestamp =                          source.`Latest Timestamp`,
    target.Latest_Remark =                             source.`Latest Remark`,
    target.Delivery_Date =                             source.`Delivery Date`,
    target.Updated_at =                                source.`Updated at`,
    target.Expected_delivery_date_by_Courier_Partner = source.`Expected delivery date by Courier Partner`,
    target.Expected_Date_Of_Delivery_Min =             source.`Expected Date Of Delivery Min`,
    target.Expected_Date_Of_Delivery_Max =             source.`Expected Date Of Delivery Max`,
    target.Out_For_Delivery_1st_Attempt =              source.`Out For Delivery 1st Attempt`,
    target.Out_For_Delivery_2nd_Attempt =              source.`Out For Delivery 2nd Attempt`,
    target.Out_For_Delivery_3rd_Attempt =              source.`Out For Delivery 3rd Attempt`,
    target.Out_For_Delivery_4th_Attempt =              source.`Out For Delivery 4th Attempt`,
    target.Out_For_Delivery_5th_Attempt =              source.`Out For Delivery 5th Attempt`,
    target.Out_For_Delivery_Attempts =                 source.`Out For Delivery Attempts`,
    target.Reason_For_Last_Failed_Delivery =           source.`Reason For Last Failed Delivery`,
    target.TimeStamp_Of_Last_Failed_Delivery =         source.`TimeStamp Of Last Failed Delivery`,
    target.Remark_Of_Last_Failed_Delivery =            source.`Remark Of Last Failed Delivery`,
    target.Is_shipment_stuck_in_lifecycle =            source.`Is shipment stuck in lifecycle`,
    target.RTO_Mark_Date =                             source.`RTO Mark Date`,
    target.Out_For_Pickup_1st_Attempt =                source.`Out For Pickup 1st Attempt`,
    target.Out_For_Pickup_2nd_Attempt =                source.`Out For Pickup 2nd Attempt`,
    target.Out_For_Pickup_3rd_Attempt =                source.`Out For Pickup 3rd Attempt`,
    target.Out_For_Pickup_Attempts =                   source.`Out For Pickup Attempts`,
    target.Destination_Hub_In_Scan_Time =              source.`Destination Hub In Scan Time`,
    target.Origin_Hub_In_Timestamp =                   source.`Origin Hub In Timestamp`,
    target.Origin_Hub_Out_Timestamp =                  source.`Origin Hub Out Timestamp`,
    target.RTO_Intransit_Timestamp =                   source.`RTO Intransit Timestamp`,
    target.RTO_Delivery_Date =                         source.`RTO Delivery Date`,
    target.Original_Appointment_Start_Time =           source.`Original Appointment Start Time`,
    target.Original_Appointment_End_Time =             source.`Original Appointment End Time`,
    target.Current_Appointment_Start_Time =            source.`Current Appointment Start Time`,
    target.Current_Appointment_End_Time =              source.`Current Appointment End Time`,
    target.Ingestion_Date =                            source.`Ingestion Date`
WHEN NOT MATCHED THEN
  INSERT (
    Order_ID,
    Created_at,
    Pickup_Date,
    Current_Location,
    Latest_Timestamp,
    Latest_Remark,
    Delivery_Date,
    Updated_at,
    Expected_delivery_date_by_Courier_Partner,
    Expected_Date_Of_Delivery_Min,
    Expected_Date_Of_Delivery_Max,
    Out_For_Delivery_1st_Attempt,
    Out_For_Delivery_2nd_Attempt,
    Out_For_Delivery_3rd_Attempt,
    Out_For_Delivery_4th_Attempt,
    Out_For_Delivery_5th_Attempt,
    Out_For_Delivery_Attempts,
    Reason_For_Last_Failed_Delivery, 
    TimeStamp_Of_Last_Failed_Delivery,
    Remark_Of_Last_Failed_Delivery,
    Is_shipment_stuck_in_lifecycle,
    RTO_Mark_Date,
    Out_For_Pickup_1st_Attempt,
    Out_For_Pickup_2nd_Attempt,
    Out_For_Pickup_3rd_Attempt,
    Out_For_Pickup_Attempts,
    Destination_Hub_In_Scan_Time,
    Origin_Hub_In_Timestamp,
    Origin_Hub_Out_Timestamp,
    RTO_Intransit_Timestamp,
    RTO_Delivery_Date,
    Original_Appointment_Start_Time,
    Original_Appointment_End_Time,
    Current_Appointment_Start_Time,
    Current_Appointment_End_Time,
    Ingestion_Date
  )
  VALUES (
 `Order ID`,
    `Created at`,
    `Pickup Date`,
    `Current Location`,
    `Latest Timestamp`,
    `Latest Remark`,
    `Delivery Date`,
    `Updated at`,
    `Expected delivery date by Courier Partner`,
    `Expected Date Of Delivery Min`,
    `Expected Date Of Delivery Max`,
    `Out For Delivery 1st Attempt`,
    `Out For Delivery 2nd Attempt`,
    `Out For Delivery 3rd Attempt`,
    `Out For Delivery 4th Attempt`,
    `Out For Delivery 5th Attempt`,
    `Out For Delivery Attempts`,
    `Reason For Last Failed Delivery`,
    `TimeStamp Of Last Failed Delivery`,
    `Remark Of Last Failed Delivery`,
    `Is shipment stuck in lifecycle`,
    `RTO Mark Date`,
    `Out For Pickup 1st Attempt`,
    `Out For Pickup 2nd Attempt`,
    `Out For Pickup 3rd Attempt`,
    `Out For Pickup Attempts`,
    `Destination Hub In Scan Time`,
    `Origin Hub In Timestamp`,
    `Origin Hub Out Timestamp`,
    `RTO Intransit Timestamp`,
    `RTO Delivery Date`,
    `Original Appointment Start Time`,
    `Original Appointment End Time`,
    `Current Appointment Start Time`,
    `Current Appointment End Time`,
    `Ingestion Date`
  )
