merge into `shopify-pubsub-project.Data_Warehouse_Nykaa_Staging.assortments` as target
using
(
select
* except(rn)
from
(
select
brand_name,
sku_desc,
pack_size,
ean_code,
hsn_code,
sku_status,
coalesce(cast(mrp as float64),0) mrp,
coalesce(ahd, 0) ahd,
coalesce(blr, 0) blr,
coalesce(blr1, 0) blr1,
coalesce(blr2, 0) blr2,
coalesce(blrbeg, 0) blrbeg,
coalesce(blrdee, 0) blrdee,
coalesce(blryel, 0) blryel,
coalesce(bvi, 0) bvi,
coalesce(chn, 0) chn,
coalesce(cwh, 0) cwh,
coalesce(ded, 0) ded,
coalesce(del1, 0) del1,
coalesce(del2, 0) del2,
coalesce(ggn, 0) ggn,
coalesce(gkp, 0) gkp,
coalesce(guw, 0) guw,
coalesce(hyd, 0) hyd,
coalesce(ind, 0) ind,
coalesce(kkj, 0) kkj,
coalesce(kol1, 0) kol1,
coalesce(kol2, 0) kol2,
coalesce(mtl, 0) mtl,
coalesce(mum1_new, 0) mum1_new,
coalesce(mum2, 0) mum2,
coalesce(mumand, 0) mumand,
coalesce(mumtha, 0) mumtha,
coalesce(ncrpit, 0) ncrpit,
coalesce(nda, 0) nda,
coalesce(ngp, 0) ngp,
coalesce(nwl, 0) nwl,
coalesce(patna, 0) patna,
coalesce(pun, 0) pun,
coalesce(rjg, 0) rjg,
coalesce(rtn, 0) rtn,
coalesce(tauru, 0) tauru,
coalesce(wht, 0) wht,
coalesce(grand_total, 0) grand_total,
pg_extracted_at,
coalesce(mumsew, 0) mumsew,
coalesce(mumshi, 0) mumshi,
sku_code,
sku_velocity,
RIGHT(TRIM(pg_mail_subject), 6) AS reporting_week,
DATE(pg_mail_recieved_at) AS mail_received_at,
FORMAT_TIMESTAMP('%A', pg_mail_recieved_at) AS report_day,
row_number() over(partition by ean_code,sku_status,RIGHT(TRIM(pg_mail_subject), 6) order by DATE(pg_mail_recieved_at)) as rn
from shopify-pubsub-project.pilgrim_bi_nykaa.assortments
-- where ean_code = '8904482500008' and sku_status = 'Active'
-- order by ean_code
)
where rn = 1 and mail_received_at >= date_sub(current_date("Asia/Kolkata"), INTERVAL 10 day)
) as source

on target.brand_name = source.brand_name
and target.reporting_week = source.reporting_week

when matched and target.mail_received_at < source.mail_received_at
then update set

target.brand_name = source.brand_name,
target.sku_desc = source.sku_desc,
target.pack_size = source.pack_size,
target.ean_code = source.ean_code,
target.hsn_code = source.hsn_code,
target.sku_status = source.sku_status,
target.mrp = source.mrp,
target.ahd = source.ahd,
target.blr = source.blr,
target.blr1 = source.blr1,
target.blr2 = source.blr2,
target.blrbeg = source.blrbeg,
target.blrdee = source.blrdee,
target.blryel = source.blryel,
target.bvi = source.bvi,
target.chn = source.chn,
target.cwh = source.cwh,
target.ded = source.ded,
target.del1 = source.del1,
target.del2 = source.del2,
target.ggn = source.ggn,
target.gkp = source.gkp,
target.guw = source.guw,
target.hyd = source.hyd,
target.ind = source.ind,
target.kkj = source.kkj,
target.kol1 = source.kol1,
target.kol2 = source.kol2,
target.mtl = source.mtl,
target.mum1_new = source.mum1_new,
target.mum2 = source.mum2,
target.mumand = source.mumand,
target.mumtha = source.mumtha,
target.ncrpit = source.ncrpit,
target.nda = source.nda,
target.ngp = source.ngp,
target.nwl = source.nwl,
target.patna = source.patna,
target.pun = source.pun,
target.rjg = source.rjg,
target.rtn = source.rtn,
target.tauru = source.tauru,
target.wht = source.wht,
target.grand_total = source.grand_total,
target.pg_extracted_at = source.pg_extracted_at,
target.mumsew = source.mumsew,
target.mumshi = source.mumshi,
target.sku_code = source.sku_code,
target.sku_velocity = source.sku_velocity,
target.reporting_week = source.reporting_week,
target.mail_received_at = source.mail_received_at,
target.report_day = source.report_day


when not matched
then insert
(
brand_name,
sku_desc,
pack_size,
ean_code,
hsn_code,
sku_status,
mrp,
ahd,
blr,
blr1,
blr2,
blrbeg,
blrdee,
blryel,
bvi,
chn,
cwh,
ded,
del1,
del2,
ggn,
gkp,
guw,
hyd,
ind,
kkj,
kol1,
kol2,
mtl,
mum1_new,
mum2,
mumand,
mumtha,
ncrpit,
nda,
ngp,
nwl,
patna,
pun,
rjg,
rtn,
tauru,
wht,
grand_total,
pg_extracted_at,
mumsew,
mumshi,
sku_code,
sku_velocity,
reporting_week,
mail_received_at,
report_day
)
values
(
source.brand_name,
source.sku_desc,
source.pack_size,
source.ean_code,
source.hsn_code,
source.sku_status,
source.mrp,
source.ahd,
source.blr,
source.blr1,
source.blr2,
source.blrbeg,
source.blrdee,
source.blryel,
source.bvi,
source.chn,
source.cwh,
source.ded,
source.del1,
source.del2,
source.ggn,
source.gkp,
source.guw,
source.hyd,
source.ind,
source.kkj,
source.kol1,
source.kol2,
source.mtl,
source.mum1_new,
source.mum2,
source.mumand,
source.mumtha,
source.ncrpit,
source.nda,
source.ngp,
source.nwl,
source.patna,
source.pun,
source.rjg,
source.rtn,
source.tauru,
source.wht,
source.grand_total,
source.pg_extracted_at,
source.mumsew,
source.mumshi,
source.sku_code,
source.sku_velocity,
source.reporting_week,
source.mail_received_at,
source.report_day
)