MERGE INTO `shopify-pubsub-project.Data_Warehouse_Easyecom_Staging.Mini_Sales_report` AS TARGET
USING
(
select distinct
  rn,
  Client_Location,
  Seller_GST_Num,
  MP_Name,
  B2B_Sales_Channel,
  Order_Number,
  Suborder_No,
  Order_Type,
  Manifest_ID,
  EE_Invoice_No,
  MP_Ref_No_MP_Invoice_Number,
  Order_Status,
  Shipping_Status,
  SAFE_CAST(Import_Date AS DATE) AS Import_Date,
  SAFE_CAST(Order_Date AS DATE) AS Order_Date,
  SAFE_CAST(Assigned_At AS DATE) AS Assigned_At,
  SAFE_CAST(TAT AS DATE) AS TAT,
  SAFE_CAST(Invoice_Date AS DATE) AS Invoice_Date,
  SAFE_CAST(QC_Confirmed_At AS DATE) AS QC_Confirmed_At,
  SAFE_CAST(Confirmed_At AS DATE) AS Confirmed_At,
  SAFE_CAST(Printed_At AS DATE) AS Printed_At,
  SAFE_CAST(Manifested_At AS DATE) AS Manifested_At,
  SAFE_CAST(Cancelled_At AS DATE) AS Cancelled_At,
  SAFE_CAST(Delivered_At AS DATE) AS Delivered_At,
  SAFE_CAST(Handover_At AS DATE) AS Handover_At,
  Batch_ID,
  Message,
  Courier_Aggregator_Name,
  Courier_Name,
  Tracking_Number,
  Packing_Material_SKU,
  SAFE_CAST(Suborder_Quantity AS FLOAT64) AS Suborder_Quantity,
  SAFE_CAST(Item_Quantity AS FLOAT64) AS Item_Quantity,
  SKU,
  SKU_Type,
  SAFE_CAST(Sub_Product_Count AS FLOAT64) AS Sub_Product_Count,
  Marketplace_Sku,
  Product_Name,
  Category,
  Brand,
  Model_No,
  Product_Tax_Code,
  EAN,
  Size,
  SAFE_CAST(Cost AS FLOAT64) AS Cost,
  SAFE_CAST(MRP AS FLOAT64) AS MRP,
  JSON_EXTRACT_SCALAR(Packaging_Dimensions,'$.height') AS Packaging_height,
  JSON_EXTRACT_SCALAR(Packaging_Dimensions,'$.length') AS Packaging_length,
  JSON_EXTRACT_SCALAR(Packaging_Dimensions,'$.width') AS Packaging_width,
  JSON_EXTRACT_SCALAR(Packaging_Dimensions,'$.weight') AS Packaging_weight,
  SAFE_CAST(Product_Weight_grams_ AS FLOAT64) AS Product_Weight_grams_,
  SAFE_CAST(Product_Height AS FLOAT64) AS Product_Height,
  SAFE_CAST(Product_Length AS FLOAT64) AS Product_Length,
  SAFE_CAST(Product_Width AS FLOAT64) AS Product_Width,
  Payment_Mode,
  Payment_Gateway,
  Payment_Transaction_ID,
  Listing_Ref_No,
  Checkout_ID,
  Discount_Codes,
  Buyer_GST_Num,
  Shipping_Customer_Name,
  Mobile_No,
  Shipping_Address_Line_1,
  Shipping_Address_Line_2,
  Customer_Email,
  Shipping_City,
  Shipping_Zip_Code,
  Shipping_State,
  Shipping_Country,
  Billing_Customer_Name,
  Billing_Address_Line_1,
  Billing_Address_Line_2,
  Billing_City,
  Billing_Zip_Code,
  Billing_State,
  Billing_Country,
  Country_Code,
  Parent_Currency_Multiplier,
  SAFE_CAST(Order_Invoice_Amount AS FLOAT64) AS Order_Invoice_Amount,
  SAFE_CAST(Order_Invoice_Amount_Acc_to_Parent_Currency AS FLOAT64) AS Order_Invoice_Amount_Acc_to_Parent_Currency,
  SAFE_CAST(TCS_Rate AS FLOAT64) AS TCS_Rate,
  SAFE_CAST(TCS_Amount AS FLOAT64) AS TCS_Amount,
  SAFE_CAST(Selling_Price AS FLOAT64) AS Selling_Price,
  SAFE_CAST(Selling_Price_Acc_to_Parent_Currency AS FLOAT64) AS Selling_Price_Acc_to_Parent_Currency,
  Tax_Type,
  SAFE_CAST(Tax_Rate AS FLOAT64) AS Tax_Rate,
  SAFE_CAST(Order_Collectable_Amount AS FLOAT64) AS Order_Collectable_Amount,
  SAFE_CAST(Tax AS FLOAT64) AS Tax,
  SAFE_CAST(Item_Price_Excluding_Tax AS FLOAT64) AS Item_Price_Excluding_Tax,
  Custom_Fields,
  Sales_Channel,
  Accounting_Sku,
  Accounting_Unit,
  ERP_Customer_ID,
  EE_Client_ID,
  Shipment_Weight_g_,
  SAFE_CAST(Expected_Delivery_Date AS DATE) AS Expected_Delivery_Date,
  SAFE_CAST(Hold_Datetime AS DATE) AS Hold_Datetime,
  SAFE_CAST(Unhold_Datetime AS DATE) AS Unhold_Datetime,
  SAFE_CAST(start_date AS DATE) AS start_date,
  SAFE_CAST(end_date AS DATE) AS end_date,
  SAFE_CAST(created_on AS DATE) AS created_on,
  GRN_Batch_Codes,
  report_id,
  report_type,
  inventory_type,
  ee_extracted_at
from
(
select distinct
  *,
  row_number() over(partition by Order_Number, Suborder_No,report_id,Seller_GST_Num,Manifest_ID,GRN_Batch_Codes order by ee_extracted_at DESC) as rn
  FROM `shopify-pubsub-project.easycom.mini_sales_report`
)
where rn = 1
) AS SOURCE
ON TARGET.Order_Number = SOURCE.Order_Number
AND TARGET.Suborder_No = SOURCE.Suborder_No
AND TARGET.report_id = SOURCE.report_id
AND TARGET.Seller_GST_Num = SOURCE.Seller_GST_Num
AND TARGET.Manifest_ID = SOURCE.Manifest_ID
AND TARGET.GRN_Batch_Codes = SOURCE.GRN_Batch_Codes
WHEN MATCHED AND TARGET.Order_Date < SOURCE.Order_Date
THEN UPDATE SET
TARGET.Client_Location = SOURCE.Client_Location,
TARGET.Seller_GST_Num = SOURCE.Seller_GST_Num,
TARGET.MP_Name = SOURCE.MP_Name,
TARGET.B2B_Sales_Channel = SOURCE.B2B_Sales_Channel,
TARGET.Order_Number = SOURCE.Order_Number,
TARGET.Suborder_No = SOURCE.Suborder_No,
TARGET.Order_Type = SOURCE.Order_Type,
TARGET.Manifest_ID = SOURCE.Manifest_ID,
TARGET.EE_Invoice_No = SOURCE.EE_Invoice_No,
TARGET.MP_Ref_No_MP_Invoice_Number = SOURCE.MP_Ref_No_MP_Invoice_Number,
TARGET.Order_Status = SOURCE.Order_Status,
TARGET.Shipping_Status = SOURCE.Shipping_Status,
TARGET.Import_Date = SOURCE.Import_Date,
TARGET.Order_Date = SOURCE.Order_Date,
TARGET.Assigned_At = SOURCE.Assigned_At,
TARGET.TAT = SOURCE.TAT,
TARGET.Invoice_Date = SOURCE.Invoice_Date,
TARGET.QC_Confirmed_At = SOURCE.QC_Confirmed_At,
TARGET.Confirmed_At = SOURCE.Confirmed_At,
TARGET.Printed_At = SOURCE.Printed_At,
TARGET.Manifested_At = SOURCE.Manifested_At,
TARGET.Cancelled_At = SOURCE.Cancelled_At,
TARGET.Delivered_At = SOURCE.Delivered_At,
TARGET.Handover_At = SOURCE.Handover_At,
TARGET.Batch_ID = SOURCE.Batch_ID,
TARGET.Message = SOURCE.Message,
TARGET.Courier_Aggregator_Name = SOURCE.Courier_Aggregator_Name,
TARGET.Courier_Name = SOURCE.Courier_Name,
TARGET.Tracking_Number = SOURCE.Tracking_Number,
TARGET.Packing_Material_SKU = SOURCE.Packing_Material_SKU,
TARGET.Suborder_Quantity = SOURCE.Suborder_Quantity,
TARGET.Item_Quantity = SOURCE.Item_Quantity,
TARGET.SKU = SOURCE.SKU,
TARGET.SKU_Type = SOURCE.SKU_Type,
TARGET.Sub_Product_Count = SOURCE.Sub_Product_Count,
TARGET.Marketplace_Sku = SOURCE.Marketplace_Sku,
TARGET.Product_Name = SOURCE.Product_Name,
TARGET.Category = SOURCE.Category,
TARGET.Brand = SOURCE.Brand,
TARGET.Model_No = SOURCE.Model_No,
TARGET.Product_Tax_Code = SOURCE.Product_Tax_Code,
TARGET.EAN = SOURCE.EAN,
TARGET.Size = SOURCE.Size,
TARGET.Cost = SOURCE.Cost,
TARGET.MRP = SOURCE.MRP,
TARGET.Packaging_height = SOURCE.Packaging_height,
TARGET.Packaging_length = SOURCE.Packaging_length,
TARGET.Packaging_width = SOURCE.Packaging_width,
TARGET.Packaging_weight = SOURCE.Packaging_weight,
TARGET.Product_Weight_grams_ = SOURCE.Product_Weight_grams_,
TARGET.Product_Height = SOURCE.Product_Height,
TARGET.Product_Length = SOURCE.Product_Length,
TARGET.Product_Width = SOURCE.Product_Width,
TARGET.Payment_Mode = SOURCE.Payment_Mode,
TARGET.Payment_Gateway = SOURCE.Payment_Gateway,
TARGET.Payment_Transaction_ID = SOURCE.Payment_Transaction_ID,
TARGET.Listing_Ref_No = SOURCE.Listing_Ref_No,
TARGET.Checkout_ID = SOURCE.Checkout_ID,
TARGET.Discount_Codes = SOURCE.Discount_Codes,
TARGET.Buyer_GST_Num = SOURCE.Buyer_GST_Num,
TARGET.Shipping_Customer_Name = SOURCE.Shipping_Customer_Name,
TARGET.Mobile_No = SOURCE.Mobile_No,
TARGET.Shipping_Address_Line_1 = SOURCE.Shipping_Address_Line_1,
TARGET.Shipping_Address_Line_2 = SOURCE.Shipping_Address_Line_2,
TARGET.Customer_Email = SOURCE.Customer_Email,
TARGET.Shipping_City = SOURCE.Shipping_City,
TARGET.Shipping_Zip_Code = SOURCE.Shipping_Zip_Code,
TARGET.Shipping_State = SOURCE.Shipping_State,
TARGET.Shipping_Country = SOURCE.Shipping_Country,
TARGET.Billing_Customer_Name = SOURCE.Billing_Customer_Name,
TARGET.Billing_Address_Line_1 = SOURCE.Billing_Address_Line_1,
TARGET.Billing_Address_Line_2 = SOURCE.Billing_Address_Line_2,
TARGET.Billing_City = SOURCE.Billing_City,
TARGET.Billing_Zip_Code = SOURCE.Billing_Zip_Code,
TARGET.Billing_State = SOURCE.Billing_State,
TARGET.Billing_Country = SOURCE.Billing_Country,
TARGET.Country_Code = SOURCE.Country_Code,
TARGET.Parent_Currency_Multiplier = SOURCE.Parent_Currency_Multiplier,
TARGET.Order_Invoice_Amount = SOURCE.Order_Invoice_Amount,
TARGET.Order_Invoice_Amount_Acc_to_Parent_Currency = SOURCE.Order_Invoice_Amount_Acc_to_Parent_Currency,
TARGET.TCS_Rate = SOURCE.TCS_Rate,
TARGET.TCS_Amount = SOURCE.TCS_Amount,
TARGET.Selling_Price = SOURCE.Selling_Price,
TARGET.Selling_Price_Acc_to_Parent_Currency = SOURCE.Selling_Price_Acc_to_Parent_Currency,
TARGET.Tax_Type = SOURCE.Tax_Type,
TARGET.Tax_Rate = SOURCE.Tax_Rate,
TARGET.Order_Collectable_Amount = SOURCE.Order_Collectable_Amount,
TARGET.Tax = SOURCE.Tax,
TARGET.Item_Price_Excluding_Tax = SOURCE.Item_Price_Excluding_Tax,
TARGET.Custom_Fields = SOURCE.Custom_Fields,
TARGET.Sales_Channel = SOURCE.Sales_Channel,
TARGET.Accounting_Sku = SOURCE.Accounting_Sku,
TARGET.Accounting_Unit = SOURCE.Accounting_Unit,
TARGET.ERP_Customer_ID = SOURCE.ERP_Customer_ID,
TARGET.EE_Client_ID = SOURCE.EE_Client_ID,
TARGET.Shipment_Weight_g_ = SOURCE.Shipment_Weight_g_,
TARGET.Expected_Delivery_Date = SOURCE.Expected_Delivery_Date,
TARGET.Hold_Datetime = SOURCE.Hold_Datetime,
TARGET.Unhold_Datetime = SOURCE.Unhold_Datetime,
TARGET.start_date = SOURCE.start_date,
TARGET.end_date = SOURCE.end_date,
TARGET.created_on = SOURCE.created_on,
TARGET.GRN_Batch_Codes = SOURCE.GRN_Batch_Codes,
TARGET.report_id = SOURCE.report_id,
TARGET.report_type = SOURCE.report_type,
TARGET.inventory_type = SOURCE.inventory_type
-- TARGET.ee_extracted_at = SOURCE.ee_extracted_at
WHEN NOT MATCHED
THEN INSERT
(
  Client_Location,
  Seller_GST_Num,
  MP_Name,
  B2B_Sales_Channel,
  Order_Number,
  Suborder_No,
  Order_Type,
  Manifest_ID,
  EE_Invoice_No,
  MP_Ref_No_MP_Invoice_Number,
  Order_Status,
  Shipping_Status,
  Import_Date,
  Order_Date,
  Assigned_At,
  TAT,
  Invoice_Date,
  QC_Confirmed_At,
  Confirmed_At,
  Printed_At,
  Manifested_At,
  Cancelled_At,
  Delivered_At,
  Handover_At,
  Batch_ID,
  Message,
  Courier_Aggregator_Name,
  Courier_Name,
  Tracking_Number,
  Packing_Material_SKU,
  Suborder_Quantity,
  Item_Quantity,
  SKU,
  SKU_Type,
  Sub_Product_Count,
  Marketplace_Sku,
  Product_Name,
  Category,
  Brand,
  Model_No,
  Product_Tax_Code,
  EAN,
  Size,
  Cost,
  MRP,
  Packaging_height,
  Packaging_length,
  Packaging_width,
  Packaging_weight,
  Product_Weight_grams_,
  Product_Height,
  Product_Length,
  Product_Width,
  Payment_Mode,
  Payment_Gateway,
  Payment_Transaction_ID,
  Listing_Ref_No,
  Checkout_ID,
  Discount_Codes,
  Buyer_GST_Num,
  Shipping_Customer_Name,
  Mobile_No,
  Shipping_Address_Line_1,
  Shipping_Address_Line_2,
  Customer_Email,
  Shipping_City,
  Shipping_Zip_Code,
  Shipping_State,
  Shipping_Country,
  Billing_Customer_Name,
  Billing_Address_Line_1,
  Billing_Address_Line_2,
  Billing_City,
  Billing_Zip_Code,
  Billing_State,
  Billing_Country,
  Country_Code,
  Parent_Currency_Multiplier,
  Order_Invoice_Amount,
  Order_Invoice_Amount_Acc_to_Parent_Currency,
  TCS_Rate,
  TCS_Amount,
  Selling_Price,
  Selling_Price_Acc_to_Parent_Currency,
  Tax_Type,
  Tax_Rate,
  Order_Collectable_Amount,
  Tax,
  Item_Price_Excluding_Tax,
  Custom_Fields,
  Sales_Channel,
  Accounting_Sku,
  Accounting_Unit,
  ERP_Customer_ID,
  EE_Client_ID,
  Shipment_Weight_g_,
  Expected_Delivery_Date,
  Hold_Datetime,
  Unhold_Datetime,
  start_date,
  end_date,
  created_on,
  GRN_Batch_Codes,
  report_id,
  report_type,
  inventory_type
  -- ee_extracted_at
)
VALUES
(
SOURCE.Client_Location,
SOURCE.Seller_GST_Num,
SOURCE.MP_Name,
SOURCE.B2B_Sales_Channel,
SOURCE.Order_Number,
SOURCE.Suborder_No,
SOURCE.Order_Type,
SOURCE.Manifest_ID,
SOURCE.EE_Invoice_No,
SOURCE.MP_Ref_No_MP_Invoice_Number,
SOURCE.Order_Status,
SOURCE.Shipping_Status,
SOURCE.Import_Date,
SOURCE.Order_Date,
SOURCE.Assigned_At,
SOURCE.TAT,
SOURCE.Invoice_Date,
SOURCE.QC_Confirmed_At,
SOURCE.Confirmed_At,
SOURCE.Printed_At,
SOURCE.Manifested_At,
SOURCE.Cancelled_At,
SOURCE.Delivered_At,
SOURCE.Handover_At,
SOURCE.Batch_ID,
SOURCE.Message,
SOURCE.Courier_Aggregator_Name,
SOURCE.Courier_Name,
SOURCE.Tracking_Number,
SOURCE.Packing_Material_SKU,
SOURCE.Suborder_Quantity,
SOURCE.Item_Quantity,
SOURCE.SKU,
SOURCE.SKU_Type,
SOURCE.Sub_Product_Count,
SOURCE.Marketplace_Sku,
SOURCE.Product_Name,
SOURCE.Category,
SOURCE.Brand,
SOURCE.Model_No,
SOURCE.Product_Tax_Code,
SOURCE.EAN,
SOURCE.Size,
SOURCE.Cost,
SOURCE.MRP,
SOURCE.Packaging_height,
SOURCE.Packaging_length,
SOURCE.Packaging_width,
SOURCE.Packaging_weight,
SOURCE.Product_Weight_grams_,
SOURCE.Product_Height,
SOURCE.Product_Length,
SOURCE.Product_Width,
SOURCE.Payment_Mode,
SOURCE.Payment_Gateway,
SOURCE.Payment_Transaction_ID,
SOURCE.Listing_Ref_No,
SOURCE.Checkout_ID,
SOURCE.Discount_Codes,
SOURCE.Buyer_GST_Num,
SOURCE.Shipping_Customer_Name,
SOURCE.Mobile_No,
SOURCE.Shipping_Address_Line_1,
SOURCE.Shipping_Address_Line_2,
SOURCE.Customer_Email,
SOURCE.Shipping_City,
SOURCE.Shipping_Zip_Code,
SOURCE.Shipping_State,
SOURCE.Shipping_Country,
SOURCE.Billing_Customer_Name,
SOURCE.Billing_Address_Line_1,
SOURCE.Billing_Address_Line_2,
SOURCE.Billing_City,
SOURCE.Billing_Zip_Code,
SOURCE.Billing_State,
SOURCE.Billing_Country,
SOURCE.Country_Code,
SOURCE.Parent_Currency_Multiplier,
SOURCE.Order_Invoice_Amount,
SOURCE.Order_Invoice_Amount_Acc_to_Parent_Currency,
SOURCE.TCS_Rate,
SOURCE.TCS_Amount,
SOURCE.Selling_Price,
SOURCE.Selling_Price_Acc_to_Parent_Currency,
SOURCE.Tax_Type,
SOURCE.Tax_Rate,
SOURCE.Order_Collectable_Amount,
SOURCE.Tax,
SOURCE.Item_Price_Excluding_Tax,
SOURCE.Custom_Fields,
SOURCE.Sales_Channel,
SOURCE.Accounting_Sku,
SOURCE.Accounting_Unit,
SOURCE.ERP_Customer_ID,
SOURCE.EE_Client_ID,
SOURCE.Shipment_Weight_g_,
SOURCE.Expected_Delivery_Date,
SOURCE.Hold_Datetime,
SOURCE.Unhold_Datetime,
SOURCE.start_date,
SOURCE.end_date,
SOURCE.created_on,
SOURCE.GRN_Batch_Codes,
SOURCE.report_id,
SOURCE.report_type,
SOURCE.inventory_type
-- SOURCE.ee_extracted_at
)
