CREATE or replace TABLE `shopify-pubsub-project.Data_Warehouse_Easyecom_Staging.Mini_Sales_report`
PARTITION BY start_date
-- CLUSTER BY 
-- OPTIONS(
--  description = "Mini Sales Report table is partitioned on order date at day level"
--  require_partition_filter = False
--  )
 AS


select
  Client_Location,
  Seller_GST_Num,
  MP_Name,
  B2B_Sales_Channel,
  Order_Number,
  Suborder_No,
  Order_Type,
  Manifest_ID,
  EE_Invoice_No,
  MP_Ref_No_MP_Invoice_Number,
  Order_Status,
  Shipping_Status,
  SAFE_CAST(Import_Date AS DATE) AS Import_Date,
  SAFE_CAST(Order_Date AS DATE) AS Order_Date,
  SAFE_CAST(Assigned_At AS DATE) AS Assigned_At,
  SAFE_CAST(TAT AS DATE) AS TAT,
  SAFE_CAST(Invoice_Date AS DATE) AS Invoice_Date,
  SAFE_CAST(QC_Confirmed_At AS DATE) AS QC_Confirmed_At,
  SAFE_CAST(Confirmed_At AS DATE) AS Confirmed_At,
  SAFE_CAST(Printed_At AS DATE) AS Printed_At,
  SAFE_CAST(Manifested_At AS DATE) AS Manifested_At,
  SAFE_CAST(Cancelled_At AS DATE) AS Cancelled_At,
  SAFE_CAST(Delivered_At AS DATE) AS Delivered_At,
  SAFE_CAST(Handover_At AS DATE) AS Handover_At,
  Batch_ID,
  Message,
  Courier_Aggregator_Name,
  Courier_Name,
  Tracking_Number,
  Packing_Material_SKU,
  SAFE_CAST(Suborder_Quantity AS FLOAT64) AS Suborder_Quantity,
  SAFE_CAST(Item_Quantity AS FLOAT64) AS Item_Quantity,
  SKU,
  SKU_Type,
  SAFE_CAST(Sub_Product_Count AS FLOAT64) AS Sub_Product_Count,
  Marketplace_Sku,
  Product_Name,
  Category,
  Brand,
  Model_No,
  Product_Tax_Code,
  EAN,
  Size,
  SAFE_CAST(Cost AS FLOAT64) AS Cost,
  SAFE_CAST(MRP AS FLOAT64) AS MRP,
  JSON_EXTRACT_SCALAR(Packaging_Dimensions,'$.height') AS Packaging_height,
  JSON_EXTRACT_SCALAR(Packaging_Dimensions,'$.length') AS Packaging_length,
  JSON_EXTRACT_SCALAR(Packaging_Dimensions,'$.width') AS Packaging_width,
  JSON_EXTRACT_SCALAR(Packaging_Dimensions,'$.weight') AS Packaging_weight,
  SAFE_CAST(Product_Weight_grams_ AS FLOAT64) AS Product_Weight_grams_,
  SAFE_CAST(Product_Height AS FLOAT64) AS Product_Height,
  SAFE_CAST(Product_Length AS FLOAT64) AS Product_Length,
  SAFE_CAST(Product_Width AS FLOAT64) AS Product_Width,
  Payment_Mode,
  Payment_Gateway,
  Payment_Transaction_ID,
  Listing_Ref_No,
  Checkout_ID,
  Discount_Codes,
  Buyer_GST_Num,
  Shipping_Customer_Name,
  Mobile_No,
  Shipping_Address_Line_1,
  Shipping_Address_Line_2,
  Customer_Email,
  Shipping_City,
  Shipping_Zip_Code,
  Shipping_State,
  Shipping_Country,
  Billing_Customer_Name,
  Billing_Address_Line_1,
  Billing_Address_Line_2,
  Billing_City,
  Billing_Zip_Code,
  Billing_State,
  Billing_Country,
  Country_Code,
  Parent_Currency_Multiplier,
  SAFE_CAST(Order_Invoice_Amount AS FLOAT64) AS Order_Invoice_Amount,
  SAFE_CAST(Order_Invoice_Amount_Acc_to_Parent_Currency AS FLOAT64) AS Order_Invoice_Amount_Acc_to_Parent_Currency,
  SAFE_CAST(TCS_Rate AS FLOAT64) AS TCS_Rate,
  SAFE_CAST(TCS_Amount AS FLOAT64) AS TCS_Amount,
  SAFE_CAST(Selling_Price AS FLOAT64) AS Selling_Price,
  SAFE_CAST(Selling_Price_Acc_to_Parent_Currency AS FLOAT64) AS Selling_Price_Acc_to_Parent_Currency,
  Tax_Type,
  SAFE_CAST(Tax_Rate AS FLOAT64) AS Tax_Rate,
  SAFE_CAST(Order_Collectable_Amount AS FLOAT64) AS Order_Collectable_Amount,
  SAFE_CAST(Tax AS FLOAT64) AS Tax,
  SAFE_CAST(Item_Price_Excluding_Tax AS FLOAT64) AS Item_Price_Excluding_Tax,
  Custom_Fields,
  Sales_Channel,
  Accounting_Sku,
  Accounting_Unit,
  ERP_Customer_ID,
  EE_Client_ID,
  Shipment_Weight_g_,
  SAFE_CAST(Expected_Delivery_Date AS DATE) AS Expected_Delivery_Date,
  SAFE_CAST(Hold_Datetime AS DATE) AS Hold_Datetime,
  SAFE_CAST(Unhold_Datetime AS DATE) AS Unhold_Datetime,
  SAFE_CAST(start_date AS DATE) AS start_date,
  SAFE_CAST(end_date AS DATE) AS end_date,
  SAFE_CAST(created_on AS DATE) AS created_on,
  GRN_Batch_Codes,
  report_id,
  report_type,
  inventory_type,
  ee_extracted_at
from
(
select distinct
  *,
  row_number() over(partition by Order_Number, Suborder_No, report_id order by ee_extracted_at DESC) as rn
  FROM `shopify-pubsub-project.easycom.mini_sales_report`
)
where rn = 1


