MERGE INTO `shopify-pubsub-project.Data_Warehouse_Amazon_ads.brands_report_stream` AS target
USING (
  WITH CTE1 AS (
    SELECT 
      _airbyte_extracted_at,
      recordId, 
      profileId, 
      recordType, 
      reportDate, 
      JSON_EXTRACT_SCALAR(metric, '$.adGroupId') AS adGroupId, 
      JSON_EXTRACT_SCALAR(metric, '$.adGroupName') AS adGroupName,
      JSON_EXTRACT_SCALAR(metric, '$.applicableBudgetRuleId') AS applicableBudgetRuleId,
      JSON_EXTRACT_SCALAR(metric, '$.applicableBudgetRuleName') AS applicableBudgetRuleName,
      JSON_EXTRACT_SCALAR(metric, '$.attributedBrandedSearches14d') AS attributedBrandedSearches14d,
      JSON_EXTRACT_SCALAR(metric, '$.attributedConversions14d') AS attributedConversions14d,
      JSON_EXTRACT_SCALAR(metric, '$.attributedConversions14dSameSKU') AS attributedConversions14dSameSKU,
      JSON_EXTRACT_SCALAR(metric, '$.attributedDetailPageViewsClicks14d') AS attributedDetailPageViewsClicks14d,
      JSON_EXTRACT_SCALAR(metric, '$.attributedOrderRateNewToBrand14d') AS attributedOrderRateNewToBrand14d,
      JSON_EXTRACT_SCALAR(metric, '$.attributedOrdersNewToBrand14d') AS attributedOrdersNewToBrand14d,
      JSON_EXTRACT_SCALAR(metric, '$.attributedOrdersNewToBrandPercentage14d') AS attributedOrdersNewToBrandPercentage14d,
      JSON_EXTRACT_SCALAR(metric, '$.attributedSales14d') AS attributedSales14d,
      JSON_EXTRACT_SCALAR(metric, '$.attributedSales14dSameSKU') AS attributedSales14dSameSKU,
      JSON_EXTRACT_SCALAR(metric, '$.attributedSalesNewToBrand14d') AS attributedSalesNewToBrand14d,
      JSON_EXTRACT_SCALAR(metric, '$.attributedSalesNewToBrandPercentage14d') AS attributedSalesNewToBrandPercentage14d,
      JSON_EXTRACT_SCALAR(metric, '$.attributedUnitsOrderedNewToBrand14d') AS attributedUnitsOrderedNewToBrand14d,
      JSON_EXTRACT_SCALAR(metric, '$.attributedUnitsOrderedNewToBrandPercentage14d') AS attributedUnitsOrderedNewToBrandPercentage14d,
      JSON_EXTRACT_SCALAR(metric, '$.campaignBudget') AS campaignBudget,
      JSON_EXTRACT_SCALAR(metric, '$.campaignBudgetType') AS campaignBudgetType,
      JSON_EXTRACT_SCALAR(metric, '$.campaignId') AS campaignId,
      JSON_EXTRACT_SCALAR(metric, '$.campaignName') AS campaignName,
      JSON_EXTRACT_SCALAR(metric, '$.campaignRuleBasedBudget') AS campaignRuleBasedBudget,
      JSON_EXTRACT_SCALAR(metric, '$.campaignStatus') AS campaignStatus,
      JSON_EXTRACT_SCALAR(metric, '$.clicks') AS clicks,
      JSON_EXTRACT_SCALAR(metric, '$.cost') AS cost,
      JSON_EXTRACT_SCALAR(metric, '$.dpv14d') AS dpv14d,
      JSON_EXTRACT_SCALAR(metric, '$.impressions') AS impressions,
      JSON_EXTRACT_SCALAR(metric, '$.keywordBid') AS keywordBid,
      JSON_EXTRACT_SCALAR(metric, '$.keywordId') AS keywordId,
      JSON_EXTRACT_SCALAR(metric, '$.keywordStatus') AS keywordStatus,
      JSON_EXTRACT_SCALAR(metric, '$.keywordText') AS keywordText,
      JSON_EXTRACT_SCALAR(metric, '$.matchType') AS matchType,
      JSON_EXTRACT_SCALAR(metric, '$.searchTermImpressionRank') AS searchTermImpressionRank,
      JSON_EXTRACT_SCALAR(metric, '$.searchTermImpressionShare') AS searchTermImpressionShare,
      JSON_EXTRACT_SCALAR(metric, '$.unitsSold14d') AS unitsSold14d,
      ROW_NUMBER() OVER (PARTITION BY recordId ORDER BY reportDate) AS rn
    FROM `shopify-pubsub-project.pilgrim_bi_airbyte_amazon_ads.sponsored_brands_report_stream`
  )
  SELECT * FROM CTE1
  --WHERE rn = 1AND
  WHERE _airbyte_extracted_at > (
    SELECT MAX(_airbyte_extracted_at) 
    FROM `shopify-pubsub-project.Data_Warehouse_Amazon_ads.brands_report_stream`
  )
) AS source
ON FALSE  -- No matching condition, always results in "NOT MATCHED"
WHEN NOT MATCHED THEN
  INSERT (
    _airbyte_extracted_at, 
    recordId, 
    profileId, 
    recordType, 
    reportDate, 
    adGroupId, 
    adGroupName, 
    applicableBudgetRuleId, 
    applicableBudgetRuleName, 
    attributedBrandedSearches14d, 
    attributedConversions14d, 
    attributedConversions14dSameSKU, 
    attributedDetailPageViewsClicks14d, 
    attributedOrderRateNewToBrand14d, 
    attributedOrdersNewToBrand14d, 
    attributedOrdersNewToBrandPercentage14d, 
    attributedSales14d, 
    attributedSales14dSameSKU, 
    attributedSalesNewToBrand14d, 
    attributedSalesNewToBrandPercentage14d, 
    attributedUnitsOrderedNewToBrand14d, 
    attributedUnitsOrderedNewToBrandPercentage14d, 
    campaignBudget, 
    campaignBudgetType, 
    campaignId, 
    campaignName, 
    campaignRuleBasedBudget, 
    campaignStatus, 
    clicks, 
    cost, 
    dpv14d, 
    impressions, 
    keywordBid, 
    keywordId, 
    keywordStatus, 
    keywordText, 
    matchType, 
    searchTermImpressionRank, 
    searchTermImpressionShare, 
    unitsSold14d
  )
  VALUES (
    source._airbyte_extracted_at, 
    source.recordId, 
    source.profileId, 
    source.recordType, 
    source.reportDate, 
    source.adGroupId, 
    source.adGroupName, 
    source.applicableBudgetRuleId, 
    source.applicableBudgetRuleName, 
    source.attributedBrandedSearches14d, 
    source.attributedConversions14d, 
    source.attributedConversions14dSameSKU, 
    source.attributedDetailPageViewsClicks14d, 
    source.attributedOrderRateNewToBrand14d, 
    source.attributedOrdersNewToBrand14d, 
    source.attributedOrdersNewToBrandPercentage14d, 
    source.attributedSales14d, 
    source.attributedSales14dSameSKU, 
    source.attributedSalesNewToBrand14d, 
    source.attributedSalesNewToBrandPercentage14d, 
    source.attributedUnitsOrderedNewToBrand14d, 
    source.attributedUnitsOrderedNewToBrandPercentage14d, 
    source.campaignBudget, 
    source.campaignBudgetType, 
    source.campaignId, 
    source.campaignName, 
    source.campaignRuleBasedBudget, 
    source.campaignStatus, 
    source.clicks, 
    source.cost, 
    source.dpv14d, 
    source.impressions, 
    source.keywordBid, 
    source.keywordId, 
    source.keywordStatus, 
    source.keywordText, 
    source.matchType, 
    source.searchTermImpressionRank, 
    source.searchTermImpressionShare, 
    source.unitsSold14d
  );
