merge into `shopify-pubsub-project.Data_Warehouse_Easyecom_Staging.Tax_report_new` as target
using
(
select distinct
-- regex expression to remove trailing decimal and digits after decimal from the strings
REGEXP_REPLACE(Company_Name,'\\.\\d+', '') as Company_Name,
REGEXP_REPLACE(Seller_GST_Num,'\\.\\d+', '') as Seller_GST_Num,
REGEXP_REPLACE(MP_Name,'\\.\\d+', '') as MP_Name,
REGEXP_REPLACE(Reference_Code,'\\.\\d+', '') as Reference_Code,
REGEXP_REPLACE(Suborder_No,'\\.\\d+', '') as Suborder_No,
REGEXP_REPLACE(Order_Type,'\\.\\d+', '') as Order_Type,
REGEXP_REPLACE(EE_Invoice_No,'\\.\\d+', '') as EE_Invoice_No,
REGEXP_REPLACE(MP_Ref_No,'\\.\\d+', '') as MP_Ref_No,
REGEXP_REPLACE(Order_Status,'\\.\\d+', '') as Order_Status,
REGEXP_REPLACE(Invoice_Status,'\\.\\d+', '') as Invoice_Status,
REGEXP_REPLACE(Credit_Note_ID,'\\.\\d+', '') as Credit_Note_ID,
Return_Date,
REGEXP_REPLACE(CR_Voucher_Num,'\\.\\d+', '') as CR_Voucher_Num,
Import_Date,
Order_Date,
Invoice_Date,
REGEXP_REPLACE(Parent_Courier_Partner,'\\.\\d+', '') as Parent_Courier_Partner,
REGEXP_REPLACE(Courier,'\\.\\d+', '') as Courier,
REGEXP_REPLACE(AWB_No,'\\.\\d+', '') as AWB_No,
Parent_Quantity,
Item_Quantity,
REGEXP_REPLACE(Product_Config,'\\.\\d+', '') as Product_Config,
REGEXP_REPLACE(Parent_SKU,'\\.\\d+', '') as Parent_SKU,
Parent_SKU_Weight,
REGEXP_REPLACE(Component_SKU,'\\.\\d+', '') as Component_SKU,
Component_SKU_Weight,
REGEXP_REPLACE(Component_SKU_Description,'\\.\\d+', '') as Component_SKU_Description,
REGEXP_REPLACE(Component_SKU_Name,'\\.\\d+', '') as Component_SKU_Name,
REGEXP_REPLACE(Component_SKU_HSN,'\\.\\d+', '') as Component_SKU_HSN,
REGEXP_REPLACE(Component_SKU_Category,'\\.\\d+', '') as Component_SKU_Category,
REGEXP_REPLACE(Component_SKU_Brand,'\\.\\d+', '') as Component_SKU_Brand,
Component_SKU_Cost,
Component_SKU_MRP,
REGEXP_REPLACE(Payment_Mode,'\\.\\d+', '') as Payment_Mode,
REGEXP_REPLACE(Buyer_GST_Num,'\\.\\d+', '') as Buyer_GST_Num,
REGEXP_REPLACE(Customer_Name,'\\.\\d+', '') as Customer_Name,
REGEXP_REPLACE(Mobile_No,'\\.\\d+', '') as Mobile_No,
REGEXP_REPLACE(Address_Line_1,'\\.\\d+', '') as Address_Line_1,
REGEXP_REPLACE(Address_Line_2,'\\.\\d+', '') as Address_Line_2,
REGEXP_REPLACE(Customer_Email,'\\.\\d+', '') as Customer_Email,
REGEXP_REPLACE(City,'\\.\\d+', '') as City,
REGEXP_REPLACE(Zip_Code,'\\.\\d+', '') as Zip_Code,
REGEXP_REPLACE(State,'\\.\\d+', '') as State,
REGEXP_REPLACE(Tax_Type,'\\.\\d+', '') as Tax_Type,
Tax_Rate,
Sr_No,
Collectible_Amount,
Order_Invoice_Amount,
TCS_Rate,
TCS,
Selling_Price,
Wallet_Discount,
Item_Price_Excluding_Tax_,
COD_Excluding_Tax_,
Shipping_Charge_Excluding_Tax_,
Shipping_Discount_Excluding_Tax_,
Promotion_Discount_Excluding_Tax_,
Miscellaneous_Excluding_Tax_,
Gift_Wrap_Charges_Excluding_Tax_,
Prepaid_Discount_Excluding_Tax_,
Promocode_Discount_Excluding_Tax_,
Taxable_Value,
Tax,
IGST,
CGST,
SGST,
CESS,
UTGST,
TDS,
IRN_Number,
Acknowledgement_Num,
Acknowledgement_Date,
Eway_Bill_Number,
Eway_Bill_Date,
CRN_Number,
CreditNote_Acknowledgement_Num,
CreditNote_Acknowledgement_Date,
REGEXP_REPLACE(Debit_Note_Number,'\\.\\d+', '') as Debit_Note_Number,
REGEXP_REPLACE(Sales_Channel,'\\.\\d+', '') as Sales_Channel,
Manifest_Date,
REGEXP_REPLACE(ERP_Customer_ID,'\\.\\d+', '') as ERP_Customer_ID,
REGEXP_REPLACE(EE_Client_ID,'\\.\\d+', '') as EE_Client_ID,
REGEXP_REPLACE(Invoice_ERP_Transaction_ID,'\\.\\d+', '') as Invoice_ERP_Transaction_ID,
REGEXP_REPLACE(Billing_Customer_Name,'\\.\\d+', '') as Billing_Customer_Name,
REGEXP_REPLACE(Billing_Mobile_No,'\\.\\d+', '') as Billing_Mobile_No,
REGEXP_REPLACE(Billing_Customer_Email,'\\.\\d+', '') as Billing_Customer_Email,
REGEXP_REPLACE(Billing_Address_Line_1,'\\.\\d+', '') as Billing_Address_Line_1,
REGEXP_REPLACE(Billing_Address_Line_2,'\\.\\d+', '') as Billing_Address_Line_2,
REGEXP_REPLACE(Billing_City,'\\.\\d+', '') as Billing_City,
REGEXP_REPLACE(Billing_Zip_Code,'\\.\\d+', '') as Billing_Zip_Code,
REGEXP_REPLACE(Billing_State,'\\.\\d+', '') as Billing_State,
REGEXP_REPLACE(Billing_Country,'\\.\\d+', '') as Billing_Country,
REGEXP_REPLACE(A_c_SKu,'\\.\\d+', '') as A_c_SKu,
A_c_Unit,
REGEXP_REPLACE(External_Order_Code,'\\.\\d+', '') as External_Order_Code,
GRN_Cost_per_unit,
Additional_cost_per_unit,
Cost_of_Goods_Purchased,
Delivery_Appointment_Date,
REGEXP_REPLACE(report_id,'\\.\\d+', '') as report_id,
REGEXP_REPLACE(report_type,'\\.\\d+', '') as report_type,
start_date,
end_date,
created_on,
inventory_type,
ee_extracted_at,

from 
(
select *,
row_number() over(partition by Reference_Code, Suborder_No, Component_SKU order by ee_extracted_at desc) as rn
from shopify-pubsub-project.easycom.tax_reports
)
where rn =1 and Invoice_Date >= DATE_SUB(CURRENT_DATE("Asia/Kolkata"), INTERVAL 10 DAY)
) as source
on target.Reference_Code = source.Reference_Code
and target.Suborder_No = source.Suborder_No
and target.Component_SKU = source.Component_SKU
when matched and target.ee_extracted_at < source.ee_extracted_at
then update set
target.Company_Name = source.Company_Name,
target.Seller_GST_Num = source.Seller_GST_Num,
target.MP_Name = source.MP_Name,
target.Reference_Code = source.Reference_Code,
target.Suborder_No = source.Suborder_No,
target.Order_Type = source.Order_Type,
target.EE_Invoice_No = source.EE_Invoice_No,
target.MP_Ref_No = source.MP_Ref_No,
target.Order_Status = source.Order_Status,
target.Invoice_Status = source.Invoice_Status,
target.Credit_Note_ID = source.Credit_Note_ID,
target.CR_Voucher_Num = source.CR_Voucher_Num,
target.Return_Date = source.Return_Date,
target.Import_Date = source.Import_Date,
target.Order_Date = source.Order_Date,
target.Invoice_Date = source.Invoice_Date,
target.Parent_Courier_Partner = source.Parent_Courier_Partner,
target.Courier = source.Courier,
target.AWB_No = source.AWB_No,
target.Component_SKU = source.Component_SKU,
target.Product_Config = source.Product_Config,
target.Parent_SKU = source.Parent_SKU,
target.Parent_Quantity = source.Parent_Quantity,
target.Item_Quantity = source.Item_Quantity,
target.Parent_SKU_Weight = source.Parent_SKU_Weight,
target.Component_SKU_Weight = source.Component_SKU_Weight,
target.Component_SKU_Description = source.Component_SKU_Description,
target.Component_SKU_Name = source.Component_SKU_Name,
target.Component_SKU_HSN = source.Component_SKU_HSN,
target.Component_SKU_Category = source.Component_SKU_Category,
target.Component_SKU_Brand = source.Component_SKU_Brand,
target.Component_SKU_Cost = source.Component_SKU_Cost,
target.Component_SKU_MRP = source.Component_SKU_MRP,
target.Payment_Mode = source.Payment_Mode,
target.Buyer_GST_Num = source.Buyer_GST_Num,
target.Customer_Name = source.Customer_Name,
target.Mobile_No = source.Mobile_No,
target.Address_Line_1 = source.Address_Line_1,
target.Address_Line_2 = source.Address_Line_2,
target.Customer_Email = source.Customer_Email,
target.City = source.City,
target.Zip_Code = source.Zip_Code,
target.State = source.State,
target.Tax_Type = source.Tax_Type,
target.Tax_Rate = source.Tax_Rate,
target.Sr_No = source.Sr_No,
target.Collectible_Amount = source.Collectible_Amount,
target.Order_Invoice_Amount = source.Order_Invoice_Amount,
target.TCS_Rate = source.TCS_Rate,
target.TCS = source.TCS,
target.Selling_Price = source.Selling_Price,
target.Wallet_Discount = source.Wallet_Discount,
target.Item_Price_Excluding_Tax_ = source.Item_Price_Excluding_Tax_,
target.COD_Excluding_Tax_ = source.COD_Excluding_Tax_,
target.Shipping_Charge_Excluding_Tax_ = source.Shipping_Charge_Excluding_Tax_,
target.Shipping_Discount_Excluding_Tax_ = source.Shipping_Discount_Excluding_Tax_,
target.Promotion_Discount_Excluding_Tax_ = source.Promotion_Discount_Excluding_Tax_,
target.Miscellaneous_Excluding_Tax_ = source.Miscellaneous_Excluding_Tax_,
target.Gift_Wrap_Charges_Excluding_Tax_ = source.Gift_Wrap_Charges_Excluding_Tax_,
target.Prepaid_Discount_Excluding_Tax_ = source.Prepaid_Discount_Excluding_Tax_,
target.Promocode_Discount_Excluding_Tax_ = source.Promocode_Discount_Excluding_Tax_,
target.Taxable_Value = source.Taxable_Value,
target.Tax = source.Tax,
target.IGST = source.IGST,
target.CGST = source.CGST,
target.SGST = source.SGST,
target.CESS = source.CESS,
target.UTGST = source.UTGST,
target.TDS = source.TDS,
target.IRN_Number = source.IRN_Number,
target.Acknowledgement_Num = source.Acknowledgement_Num,
target.Acknowledgement_Date = source.Acknowledgement_Date,
target.Eway_Bill_Number = source.Eway_Bill_Number,
target.Eway_Bill_Date = source.Eway_Bill_Date,
target.CRN_Number = source.CRN_Number,
target.CreditNote_Acknowledgement_Num = source.CreditNote_Acknowledgement_Num,
target.CreditNote_Acknowledgement_Date = source.CreditNote_Acknowledgement_Date,
target.Debit_Note_Number = source.Debit_Note_Number,
target.Sales_Channel = source.Sales_Channel,
target.Manifest_Date = source.Manifest_Date,
target.ERP_Customer_ID = source.ERP_Customer_ID,
target.EE_Client_ID = source.EE_Client_ID,
target.Invoice_ERP_Transaction_ID = source.Invoice_ERP_Transaction_ID,
target.Billing_Customer_Name = source.Billing_Customer_Name,
target.Billing_Mobile_No = source.Billing_Mobile_No,
target.Billing_Customer_Email = source.Billing_Customer_Email,
target.Billing_Address_Line_1 = source.Billing_Address_Line_1,
target.Billing_Address_Line_2 = source.Billing_Address_Line_2,
target.Billing_City = source.Billing_City,
target.Billing_Zip_Code = source.Billing_Zip_Code,
target.Billing_State = source.Billing_State,
target.Billing_Country = source.Billing_Country,
target.A_c_SKu = source.A_c_SKu,
target.External_Order_Code = source.External_Order_Code,
target.A_c_Unit = source.A_c_Unit,
target.GRN_Cost_per_unit = source.GRN_Cost_per_unit,
target.Additional_cost_per_unit = source.Additional_cost_per_unit,
target.Cost_of_Goods_Purchased = source.Cost_of_Goods_Purchased,
target.Delivery_Appointment_Date = source.Delivery_Appointment_Date,
target.report_id = source.report_id,
target.report_type = source.report_type,
target.start_date = source.start_date,
target.end_date = source.end_date,
target.created_on = source.created_on,
target.inventory_type = source.inventory_type,
target.ee_extracted_at = source.ee_extracted_at
when not matched
then insert
(
Company_Name,
Seller_GST_Num,
MP_Name,
Reference_Code,
Suborder_No,
Order_Type,
EE_Invoice_No,
MP_Ref_No,
Order_Status,
Invoice_Status,
Credit_Note_ID,
CR_Voucher_Num,
Return_Date,
Import_Date,
Order_Date,
Invoice_Date,
Parent_Courier_Partner,
Courier,
AWB_No,
Component_SKU,
Product_Config,
Parent_SKU,
Parent_Quantity,
Item_Quantity,
Parent_SKU_Weight,
Component_SKU_Weight,
Component_SKU_Description,
Component_SKU_Name,
Component_SKU_HSN,
Component_SKU_Category,
Component_SKU_Brand,
Component_SKU_Cost,
Component_SKU_MRP,
Payment_Mode,
Buyer_GST_Num,
Customer_Name,
Mobile_No,
Address_Line_1,
Address_Line_2,
Customer_Email,
City,
Zip_Code,
State,
Tax_Type,
Tax_Rate,
Sr_No,
Collectible_Amount,
Order_Invoice_Amount,
TCS_Rate,
TCS,
Selling_Price,
Wallet_Discount,
Item_Price_Excluding_Tax_,
COD_Excluding_Tax_,
Shipping_Charge_Excluding_Tax_,
Shipping_Discount_Excluding_Tax_,
Promotion_Discount_Excluding_Tax_,
Miscellaneous_Excluding_Tax_,
Gift_Wrap_Charges_Excluding_Tax_,
Prepaid_Discount_Excluding_Tax_,
Promocode_Discount_Excluding_Tax_,
Taxable_Value,
Tax,
IGST,
CGST,
SGST,
CESS,
UTGST,
TDS,
IRN_Number,
Acknowledgement_Num,
Acknowledgement_Date,
Eway_Bill_Number,
Eway_Bill_Date,
CRN_Number,
CreditNote_Acknowledgement_Num,
CreditNote_Acknowledgement_Date,
Debit_Note_Number,
Sales_Channel,
Manifest_Date,
ERP_Customer_ID,
EE_Client_ID,
Invoice_ERP_Transaction_ID,
Billing_Customer_Name,
Billing_Mobile_No,
Billing_Customer_Email,
Billing_Address_Line_1,
Billing_Address_Line_2,
Billing_City,
Billing_Zip_Code,
Billing_State,
Billing_Country,
A_c_SKu,
External_Order_Code,
A_c_Unit,
GRN_Cost_per_unit,
Additional_cost_per_unit,
Cost_of_Goods_Purchased,
Delivery_Appointment_Date,
report_id,
report_type,
start_date,
end_date,
created_on,
inventory_type,
ee_extracted_at
)
values
(
Company_Name,
Seller_GST_Num,
MP_Name,
Reference_Code,
Suborder_No,
Order_Type,
EE_Invoice_No,
MP_Ref_No,
Order_Status,
Invoice_Status,
Credit_Note_ID,
CR_Voucher_Num,
Return_Date,
Import_Date,
Order_Date,
Invoice_Date,
Parent_Courier_Partner,
Courier,
AWB_No,
Component_SKU,
Product_Config,
Parent_SKU,
Parent_Quantity,
Item_Quantity,
Parent_SKU_Weight,
Component_SKU_Weight,
Component_SKU_Description,
Component_SKU_Name,
Component_SKU_HSN,
Component_SKU_Category,
Component_SKU_Brand,
Component_SKU_Cost,
Component_SKU_MRP,
Payment_Mode,
Buyer_GST_Num,
Customer_Name,
Mobile_No,
Address_Line_1,
Address_Line_2,
Customer_Email,
City,
Zip_Code,
State,
Tax_Type,
Tax_Rate,
Sr_No,
Collectible_Amount,
Order_Invoice_Amount,
TCS_Rate,
TCS,
Selling_Price,
Wallet_Discount,
Item_Price_Excluding_Tax_,
COD_Excluding_Tax_,
Shipping_Charge_Excluding_Tax_,
Shipping_Discount_Excluding_Tax_,
Promotion_Discount_Excluding_Tax_,
Miscellaneous_Excluding_Tax_,
Gift_Wrap_Charges_Excluding_Tax_,
Prepaid_Discount_Excluding_Tax_,
Promocode_Discount_Excluding_Tax_,
Taxable_Value,
Tax,
IGST,
CGST,
SGST,
CESS,
UTGST,
TDS,
IRN_Number,
Acknowledgement_Num,
Acknowledgement_Date,
Eway_Bill_Number,
Eway_Bill_Date,
CRN_Number,
CreditNote_Acknowledgement_Num,
CreditNote_Acknowledgement_Date,
Debit_Note_Number,
Sales_Channel,
Manifest_Date,
ERP_Customer_ID,
EE_Client_ID,
Invoice_ERP_Transaction_ID,
Billing_Customer_Name,
Billing_Mobile_No,
Billing_Customer_Email,
Billing_Address_Line_1,
Billing_Address_Line_2,
Billing_City,
Billing_Zip_Code,
Billing_State,
Billing_Country,
A_c_SKu,
External_Order_Code,
A_c_Unit,
GRN_Cost_per_unit,
Additional_cost_per_unit,
Cost_of_Goods_Purchased,
Delivery_Appointment_Date,
report_id,
report_type,
start_date,
end_date,
created_on,
inventory_type,
ee_extracted_at
)