merge into `shopify-pubsub-project.Data_Warehouse_Facebook_Ads_Staging.ads_insights_conversion_data` as target
using
(
SELECT
  _airbyte_extracted_at,
  campaign_id,
  adset_id,
  ad_id,
  date_start,
  JSON_EXTRACT_SCALAR(web_ctr, '$.action_type') as website_ctr_action_type,
  JSON_EXTRACT_SCALAR(web_ctr, '$.value') as website_ctr_value,
  JSON_EXTRACT_SCALAR(conversion, '$.28d_click') AS conversions_28d_click,
  JSON_EXTRACT_SCALAR(conversion, '$.7d_click') AS conversions_7d_click,
  JSON_EXTRACT_SCALAR(conversion, '$.action_type') AS conversions_action_type,
  JSON_EXTRACT_SCALAR(conversion, '$.value') AS conversions_value,
  JSON_EXTRACT_SCALAR(conv, '$.1d_click') AS conv_1d_click,
  JSON_EXTRACT_SCALAR(conv, '$.1d_view') AS conv_1d_view,
  JSON_EXTRACT_SCALAR(conv, '$.28d_click') AS conv_28d_click,
  JSON_EXTRACT_SCALAR(conv, '$.28d_view') AS conv_28d_view,
  JSON_EXTRACT_SCALAR(conv, '$.7d_click') AS conv_7d_click,
  JSON_EXTRACT_SCALAR(conv, '$.7d_view') AS conv_7d_view,
  JSON_EXTRACT_SCALAR(conv, '$.action_type') AS conv_action_type,
  JSON_EXTRACT_SCALAR(conv, '$.value') AS conv_value,
  JSON_EXTRACT_SCALAR(cost_per_conv, '$.1d_click') AS cost_per_conv_1d_click,
  JSON_EXTRACT_SCALAR(cost_per_conv, '$.1d_view') AS cost_per_conv_1d_view,
  JSON_EXTRACT_SCALAR(cost_per_conv, '$.28d_click') AS cost_per_conv_28d_click,
  JSON_EXTRACT_SCALAR(cost_per_conv, '$.28d_view') AS cost_per_conv_28d_view,
  JSON_EXTRACT_SCALAR(cost_per_conv, '$.7d_click') AS cost_per_conv_7d_click,
  JSON_EXTRACT_SCALAR(cost_per_conv, '$.7d_view') AS cost_per_conv_7d_view,
  JSON_EXTRACT_SCALAR(cost_per_conv, '$.action_type') AS cost_per_conv_action_type,
  JSON_EXTRACT_SCALAR(cost_per_conv, '$.value') AS cost_per_conv_value,
FROM
(
  select *,
  row_number() over(partition by ad_id,date_start order by _airbyte_extracted_at desc) as rn
  from shopify-pubsub-project.pilgrim_bi_airbyte_facebook.ads_insights,
  UNNEST(JSON_EXTRACT_ARRAY(conversion_values)) AS conversion,
  UNNEST(JSON_EXTRACT_ARRAY(conversions)) AS conv,
  UNNEST(JSON_EXTRACT_ARRAY(cost_per_conversion)) AS cost_per_conv,
  UNNEST(JSON_EXTRACT_ARRAY(website_ctr)) AS web_ctr
) 
where rn =1 and date(_airbyte_extracted_at) >= date_sub(current_date("Asia/Kolkata"), interval 10 day)
) as source
on target.ad_id = source.ad_id
and target.date_start = source.date_start
when matched and target._airbyte_extracted_at < source._airbyte_extracted_at
then update set
  target._airbyte_extracted_at = source._airbyte_extracted_at,
  target.campaign_id = source.campaign_id,
  target.adset_id = source.adset_id,
  target.ad_id = source.ad_id,
  target.date_start = source.date_start,
  target.website_ctr_action_type = source.website_ctr_action_type,
  target.website_ctr_value = source.website_ctr_value,
  target.conversions_28d_click = source.conversions_28d_click,
  target.conversions_7d_click = source.conversions_7d_click,
  target.conversions_action_type = source.conversions_action_type,
  target.conversions_value = source.conversions_value,
  target.conv_1d_click = source.conv_1d_click,
  target.conv_1d_view = source.conv_1d_view,
  target.conv_28d_click = source.conv_28d_click,
  target.conv_28d_view = source.conv_28d_view,
  target.conv_7d_click = source.conv_7d_click,
  target.conv_7d_view = source.conv_7d_view,
  target.conv_action_type = source.conv_action_type,
  target.conv_value = source.conv_value,
  target.cost_per_conv_1d_click = source.cost_per_conv_1d_click,
  target.cost_per_conv_1d_view = source.cost_per_conv_1d_view,
  target.cost_per_conv_28d_click = source.cost_per_conv_28d_click,
  target.cost_per_conv_28d_view = source.cost_per_conv_28d_view,
  target.cost_per_conv_7d_click = source.cost_per_conv_7d_click,
  target.cost_per_conv_7d_view = source.cost_per_conv_7d_view,
  target.cost_per_conv_action_type = source.cost_per_conv_action_type,
  target.cost_per_conv_value = source.cost_per_conv_value
when not matched
then insert
(
  _airbyte_extracted_at,
  campaign_id,
  adset_id,
  ad_id,
  date_start,
  website_ctr_action_type,
  website_ctr_value,
  conversions_28d_click,
  conversions_7d_click,
  conversions_action_type,
  conversions_value,
  conv_1d_click,
  conv_1d_view,
  conv_28d_click,
  conv_28d_view,
  conv_7d_click,
  conv_7d_view,
  conv_action_type,
  conv_value,
  cost_per_conv_1d_click,
  cost_per_conv_1d_view,
  cost_per_conv_28d_click,
  cost_per_conv_28d_view,
  cost_per_conv_7d_click,
  cost_per_conv_7d_view,
  cost_per_conv_action_type,
  cost_per_conv_value
)
values
(
  source._airbyte_extracted_at,
  source.campaign_id,
  source.adset_id,
  source.ad_id,
  source.date_start,
  source.website_ctr_action_type,
  source.website_ctr_value,
  source.conversions_28d_click,
  source.conversions_7d_click,
  source.conversions_action_type,
  source.conversions_value,
  source.conv_1d_click,
  source.conv_1d_view,
  source.conv_28d_click,
  source.conv_28d_view,
  source.conv_7d_click,
  source.conv_7d_view,
  source.conv_action_type,
  source.conv_value,
  source.cost_per_conv_1d_click,
  source.cost_per_conv_1d_view,
  source.cost_per_conv_28d_click,
  source.cost_per_conv_28d_view,
  source.cost_per_conv_7d_click,
  source.cost_per_conv_7d_view,
  source.cost_per_conv_action_type,
  source.cost_per_conv_value
)