MERGE INTO `shopify-pubsub-project.Data_Warehouse_Amazon_ads.products_report_stream` AS target
USING (
  SELECT 
    _airbyte_extracted_at,
    JSON_EXTRACT_SCALAR(metric, '$.adGroupId') AS adGroupId,
    JSON_EXTRACT_SCALAR(metric, '$.adGroupName') AS adGroupName,
    JSON_EXTRACT_SCALAR(metric, '$.adId') AS adId,
    JSON_EXTRACT_SCALAR(metric, '$.advertisedAsin') AS advertisedAsin,
    JSON_EXTRACT_SCALAR(metric, '$.advertisedSku') AS advertisedSku,
    JSON_EXTRACT_SCALAR(metric, '$.attributedSalesSameSku14d') AS attributedSalesSameSku14d,
    JSON_EXTRACT_SCALAR(metric, '$.attributedSalesSameSku1d') AS attributedSalesSameSku1d,
    JSON_EXTRACT_SCALAR(metric, '$.attributedSalesSameSku30d') AS attributedSalesSameSku30d,
    JSON_EXTRACT_SCALAR(metric, '$.attributedSalesSameSku7d') AS attributedSalesSameSku7d,
    JSON_EXTRACT_SCALAR(metric, '$.campaignApplicableBudgetRuleId') AS campaignApplicableBudgetRuleId,
    JSON_EXTRACT_SCALAR(metric, '$.campaignApplicableBudgetRuleName') AS campaignApplicableBudgetRuleName,
    JSON_EXTRACT_SCALAR(metric, '$.campaignBudgetAmount') AS campaignBudgetAmount,
    JSON_EXTRACT_SCALAR(metric, '$.campaignBudgetCurrencyCode') AS campaignBudgetCurrencyCode,
    JSON_EXTRACT_SCALAR(metric, '$.campaignId') AS campaignId,
    JSON_EXTRACT_SCALAR(metric, '$.campaignName') AS campaignName,
    JSON_EXTRACT_SCALAR(metric, '$.campaignRuleBasedBudgetAmount') AS campaignRuleBasedBudgetAmount,
    JSON_EXTRACT_SCALAR(metric, '$.campaignStatus') AS campaignStatus,
    JSON_EXTRACT_SCALAR(metric, '$.clicks') AS clicks,
    JSON_EXTRACT_SCALAR(metric, '$.cost') AS cost,
    JSON_EXTRACT_SCALAR(metric, '$.impressions') AS impressions,
    JSON_EXTRACT_SCALAR(metric, '$.keyword') AS keyword,
    JSON_EXTRACT_SCALAR(metric, '$.keywordId') AS keywordId,
    JSON_EXTRACT_SCALAR(metric, '$.keywordType') AS keywordType,
    JSON_EXTRACT_SCALAR(metric, '$.matchType') AS matchType,
    JSON_EXTRACT_SCALAR(metric, '$.purchasedAsin') AS purchasedAsin,
    JSON_EXTRACT_SCALAR(metric, '$.purchases14d') AS purchases14d,
    JSON_EXTRACT_SCALAR(metric, '$.purchases1d') AS purchases1d,
    JSON_EXTRACT_SCALAR(metric, '$.purchases30d') AS purchases30d,
    JSON_EXTRACT_SCALAR(metric, '$.purchases7d') AS purchases7d,
    JSON_EXTRACT_SCALAR(metric, '$.purchasesSameSku14d') AS purchasesSameSku14d,
    JSON_EXTRACT_SCALAR(metric, '$.purchasesSameSku1d') AS purchasesSameSku1d,
    JSON_EXTRACT_SCALAR(metric, '$.purchasesSameSku30d') AS purchasesSameSku30d,
    JSON_EXTRACT_SCALAR(metric, '$.purchasesSameSku7d') AS purchasesSameSku7d,
    JSON_EXTRACT_SCALAR(metric, '$.sales14d') AS sales14d,
    JSON_EXTRACT_SCALAR(metric, '$.sales1d') AS sales1d,
    JSON_EXTRACT_SCALAR(metric, '$.sales30d') AS sales30d,
    JSON_EXTRACT_SCALAR(metric, '$.sales7d') AS sales7d,
    JSON_EXTRACT_SCALAR(metric, '$.salesOtherSku14d') AS salesOtherSku14d,
    JSON_EXTRACT_SCALAR(metric, '$.salesOtherSku1d') AS salesOtherSku1d,
    JSON_EXTRACT_SCALAR(metric, '$.salesOtherSku30d') AS salesOtherSku30d,
    JSON_EXTRACT_SCALAR(metric, '$.salesOtherSku7d') AS salesOtherSku7d,
    JSON_EXTRACT_SCALAR(metric, '$.targeting') AS targeting,
    JSON_EXTRACT_SCALAR(metric, '$.unitsSoldClicks14d') AS unitsSoldClicks14d,
    JSON_EXTRACT_SCALAR(metric, '$.unitsSoldClicks1d') AS unitsSoldClicks1d,
    JSON_EXTRACT_SCALAR(metric, '$.unitsSoldClicks30d') AS unitsSoldClicks30d,
    JSON_EXTRACT_SCALAR(metric, '$.unitsSoldClicks7d') AS unitsSoldClicks7d,
    JSON_EXTRACT_SCALAR(metric, '$.unitsSoldOtherSku14d') AS unitsSoldOtherSku14d,
    JSON_EXTRACT_SCALAR(metric, '$.unitsSoldOtherSku1d') AS unitsSoldOtherSku1d,
    JSON_EXTRACT_SCALAR(metric, '$.unitsSoldOtherSku30d') AS unitsSoldOtherSku30d,
    JSON_EXTRACT_SCALAR(metric, '$.unitsSoldOtherSku7d') AS unitsSoldOtherSku7d,
    JSON_EXTRACT_SCALAR(metric, '$.unitsSoldSameSku14d') AS unitsSoldSameSku14d,
    JSON_EXTRACT_SCALAR(metric, '$.unitsSoldSameSku1d') AS unitsSoldSameSku1d,
    JSON_EXTRACT_SCALAR(metric, '$.unitsSoldSameSku30d') AS unitsSoldSameSku30d,
    JSON_EXTRACT_SCALAR(metric, '$.unitsSoldSameSku7d') AS unitsSoldSameSku7d,
    recordId,
    profileId,
    recordType,
    reportDate 
  FROM 
  (
    SELECT * 
    FROM `shopify-pubsub-project.pilgrim_bi_airbyte_amazon_ads.sponsored_products_report_stream`
  )
  WHERE _airbyte_extracted_at > (
    SELECT MAX(_airbyte_extracted_at) 
    FROM `shopify-pubsub-project.Data_Warehouse_Amazon_ads.products_report_stream`
  )
) AS source
ON FALSE 
WHEN NOT MATCHED THEN
  INSERT (
    _airbyte_extracted_at,
    adGroupId,
    adGroupName,
    adId,
    advertisedAsin,
    advertisedSku,
    attributedSalesSameSku14d,
    attributedSalesSameSku1d,
    attributedSalesSameSku30d,
    attributedSalesSameSku7d,
    campaignApplicableBudgetRuleId,
    campaignApplicableBudgetRuleName,
    campaignBudgetAmount,
    campaignBudgetCurrencyCode,
    campaignId,
    campaignName,
    campaignRuleBasedBudgetAmount,
    campaignStatus,
    clicks,
    cost,
    impressions,
    keyword,
    keywordId,
    keywordType,
    matchType,
    purchasedAsin,
    purchases14d,
    purchases1d,
    purchases30d,
    purchases7d,
    purchasesSameSku14d,
    purchasesSameSku1d,
    purchasesSameSku30d,
    purchasesSameSku7d,
    sales14d,
    sales1d,
    sales30d,
    sales7d,
    salesOtherSku14d,
    salesOtherSku1d,
    salesOtherSku30d,
    salesOtherSku7d,
    targeting,
    unitsSoldClicks14d,
    unitsSoldClicks1d,
    unitsSoldClicks30d,
    unitsSoldClicks7d,
    unitsSoldOtherSku14d,
    unitsSoldOtherSku1d,
    unitsSoldOtherSku30d,
    unitsSoldOtherSku7d,
    unitsSoldSameSku14d,
    unitsSoldSameSku1d,
    unitsSoldSameSku30d,
    unitsSoldSameSku7d,
    recordId,
    profileId,
    recordType,
    reportDate
  )
  VALUES (
    source._airbyte_extracted_at,
    source.adGroupId,
    source.adGroupName,
    source.adId,
    source.advertisedAsin,
    source.advertisedSku,
    source.attributedSalesSameSku14d,
    source.attributedSalesSameSku1d,
    source.attributedSalesSameSku30d,
    source.attributedSalesSameSku7d,
    source.campaignApplicableBudgetRuleId,
    source.campaignApplicableBudgetRuleName,
    source.campaignBudgetAmount,
    source.campaignBudgetCurrencyCode,
    source.campaignId,
    source.campaignName,
    source.campaignRuleBasedBudgetAmount,
    source.campaignStatus,
    source.clicks,
    source.cost,
    source.impressions,
    source.keyword,
    source.keywordId,
    source.keywordType,
    source.matchType,
    source.purchasedAsin,
    source.purchases14d,
    source.purchases1d,
    source.purchases30d,
    source.purchases7d,
    source.purchasesSameSku14d,
    source.purchasesSameSku1d,
    source.purchasesSameSku30d,
    source.purchasesSameSku7d,
    source.sales14d,
    source.sales1d,
    source.sales30d,
    source.sales7d,
    source.salesOtherSku14d,
    source.salesOtherSku1d,
    source.salesOtherSku30d,
    source.salesOtherSku7d,
    source.targeting,
    source.unitsSoldClicks14d,
    source.unitsSoldClicks1d,
    source.unitsSoldClicks30d,
    source.unitsSoldClicks7d, 
    source.unitsSoldOtherSku14d,
    source.unitsSoldOtherSku1d,
    source.unitsSoldOtherSku30d,
    source.unitsSoldOtherSku7d,
    source.unitsSoldSameSku14d,
    source.unitsSoldSameSku1d,
    source.unitsSoldSameSku30d,
    source.unitsSoldSameSku7d,
    source.recordId,
    source.profileId,
    source.recordType,
    source.reportDate
    )
