CREATE OR REPLACE TABLE `shopify-pubsub-project.Data_Warehouse_Amazon_ads.products_report_stream` 
PARTITION BY DATE_TRUNC(_airbyte_extracted_at, DAY)
AS 
SELECT 
_airbyte_extracted_at,
JSON_EXTRACT_SCALAR(metric, '$.adGroupId') AS adGroupId,
JSON_EXTRACT_SCALAR(metric, '$.adGroupName') AS adGroupName,
JSON_EXTRACT_SCALAR(metric, '$.adId') AS adId,
JSON_EXTRACT_SCALAR(metric, '$.advertisedAsin') AS advertisedAsin,
JSON_EXTRACT_SCALAR(metric, '$.advertisedSku') AS advertisedSku,
JSON_EXTRACT_SCALAR(metric, '$.attributedSalesSameSku14d') AS attributedSalesSameSku14d,
JSON_EXTRACT_SCALAR(metric, '$.attributedSalesSameSku1d') AS attributedSalesSameSku1d,
JSON_EXTRACT_SCALAR(metric, '$.attributedSalesSameSku30d') AS attributedSalesSameSku30d,
JSON_EXTRACT_SCALAR(metric, '$.attributedSalesSameSku7d') AS attributedSalesSameSku7d,
JSON_EXTRACT_SCALAR(metric, '$.campaignApplicableBudgetRuleId') AS campaignApplicableBudgetRuleId,
JSON_EXTRACT_SCALAR(metric, '$.campaignApplicableBudgetRuleName') AS campaignApplicableBudgetRuleName,
JSON_EXTRACT_SCALAR(metric, '$.campaignBudgetAmount') AS campaignBudgetAmount,
JSON_EXTRACT_SCALAR(metric, '$.campaignBudgetCurrencyCode') AS campaignBudgetCurrencyCode,
JSON_EXTRACT_SCALAR(metric, '$.campaignId') AS campaignId,
JSON_EXTRACT_SCALAR(metric, '$.campaignName') AS campaignName,
JSON_EXTRACT_SCALAR(metric, '$.campaignRuleBasedBudgetAmount') AS campaignRuleBasedBudgetAmount,
JSON_EXTRACT_SCALAR(metric, '$.campaignStatus') AS campaignStatus,
JSON_EXTRACT_SCALAR(metric, '$.clicks') AS clicks,
JSON_EXTRACT_SCALAR(metric, '$.cost') AS cost,
JSON_EXTRACT_SCALAR(metric, '$.impressions') AS impressions,
JSON_EXTRACT_SCALAR(metric, '$.keyword') AS keyword,
JSON_EXTRACT_SCALAR(metric, '$.keywordId') AS keywordId,
JSON_EXTRACT_SCALAR(metric, '$.keywordType') AS keywordType,
JSON_EXTRACT_SCALAR(metric, '$.matchType') AS matchType,
JSON_EXTRACT_SCALAR(metric, '$.purchasedAsin') AS purchasedAsin,
JSON_EXTRACT_SCALAR(metric, '$.purchases14d') AS purchases14d,
JSON_EXTRACT_SCALAR(metric, '$.purchases1d') AS purchases1d,
JSON_EXTRACT_SCALAR(metric, '$.purchases30d') AS purchases30d,
JSON_EXTRACT_SCALAR(metric, '$.purchases7d') AS purchases7d,
JSON_EXTRACT_SCALAR(metric, '$.purchasesSameSku14d') AS purchasesSameSku14d,
JSON_EXTRACT_SCALAR(metric, '$.purchasesSameSku1d') AS purchasesSameSku1d,
JSON_EXTRACT_SCALAR(metric, '$.purchasesSameSku30d') AS purchasesSameSku30d,
JSON_EXTRACT_SCALAR(metric, '$.purchasesSameSku7d') AS purchasesSameSku7d,
JSON_EXTRACT_SCALAR(metric, '$.sales14d') AS sales14d,
JSON_EXTRACT_SCALAR(metric, '$.sales1d') AS sales1d,
JSON_EXTRACT_SCALAR(metric, '$.sales30d') AS sales30d,
JSON_EXTRACT_SCALAR(metric, '$.sales7d') AS sales7d,
JSON_EXTRACT_SCALAR(metric, '$.salesOtherSku14d') AS salesOtherSku14d,
JSON_EXTRACT_SCALAR(metric, '$.salesOtherSku1d') AS salesOtherSku1d,
JSON_EXTRACT_SCALAR(metric, '$.salesOtherSku30d') AS salesOtherSku30d,
JSON_EXTRACT_SCALAR(metric, '$.salesOtherSku7d') AS salesOtherSku7d,
JSON_EXTRACT_SCALAR(metric, '$.targeting') AS targeting,
JSON_EXTRACT_SCALAR(metric, '$.unitsSoldClicks14d') AS unitsSoldClicks14d,
JSON_EXTRACT_SCALAR(metric, '$.unitsSoldClicks1d') AS unitsSoldClicks1d,
JSON_EXTRACT_SCALAR(metric, '$.unitsSoldClicks30d') AS unitsSoldClicks30d,
JSON_EXTRACT_SCALAR(metric, '$.unitsSoldClicks7d') AS unitsSoldClicks7d,
JSON_EXTRACT_SCALAR(metric, '$.unitsSoldOtherSku14d') AS unitsSoldOtherSku14d,
JSON_EXTRACT_SCALAR(metric, '$.unitsSoldOtherSku1d') AS unitsSoldOtherSku1d,
JSON_EXTRACT_SCALAR(metric, '$.unitsSoldOtherSku30d') AS unitsSoldOtherSku30d,
JSON_EXTRACT_SCALAR(metric, '$.unitsSoldOtherSku7d') AS unitsSoldOtherSku7d,
JSON_EXTRACT_SCALAR(metric, '$.unitsSoldSameSku14d') AS unitsSoldSameSku14d,
JSON_EXTRACT_SCALAR(metric, '$.unitsSoldSameSku1d') AS unitsSoldSameSku1d,
JSON_EXTRACT_SCALAR(metric, '$.unitsSoldSameSku30d') AS unitsSoldSameSku30d,
JSON_EXTRACT_SCALAR(metric, '$.unitsSoldSameSku7d') AS unitsSoldSameSku7d,
recordId,
profileId,
recordType,
reportDate 
FROM 
(
  SELECT * FROM `shopify-pubsub-project.pilgrim_bi_airbyte_amazon_ads.sponsored_products_report_stream` --WHERE recordId='B0D5DBM7G7'
)