MERGE INTO `shopify-pubsub-project.Data_Warehouse_GoogleAds_Staging.shopping_performance_view` as TARGET
USING
(
  SELECT
    _airbyte_extracted_at,
    ad_group_id,
    ad_group_name,
    ad_group_status,
    campaign_id,
    campaign_name,
    campaign_status,
    customer_descriptive_name,
    customer_id,
    metrics_all_conversions,
    metrics_all_conversions_from_interactions_rate,
    metrics_all_conversions_value,
    metrics_average_cpc,
    metrics_clicks,
    metrics_conversions,
    metrics_conversions_from_interactions_rate,
    metrics_conversions_value,
    metrics_cost_micros,
    metrics_cost_per_all_conversions,
    metrics_cost_per_conversion,
    metrics_cross_device_conversions,
    metrics_ctr,
    metrics_impressions,
    metrics_value_per_all_conversions,
    metrics_value_per_conversion,
    segments_ad_network_type,
    segments_click_type,
    segments_date,
    segments_day_of_week,
    segments_device,
    segments_month,
    segments_product_aggregator_id,
    segments_product_brand,
    segments_product_category_level1,
    segments_product_category_level2,
    segments_product_category_level3,
    segments_product_category_level4,
    segments_product_category_level5,
    segments_product_channel,
    segments_product_channel_exclusivity,
    segments_product_condition,
    segments_product_country,
    segments_product_custom_attribute0,
    segments_product_custom_attribute1,
    segments_product_custom_attribute2,
    segments_product_custom_attribute3,
    segments_product_custom_attribute4,
    segments_product_item_id,
    segments_product_language,
    segments_product_merchant_id,
    segments_product_store_id,
    segments_product_title,
    segments_product_type_l1,
    segments_product_type_l2,
    segments_product_type_l3,
    segments_product_type_l4,
    segments_product_type_l5,
    segments_quarter,
    segments_week,
    segments_year

  FROM
  (
    SELECT
      *,
      ROW_NUMBER() OVER(PARTITION BY segments_product_item_id ORDER BY segments_product_item_id DESC) AS ROW_NUM
    FROM
     `shopify-pubsub-project.pilgrim_bi_google_ads.shopping_performance_view`
    WHERE
      DATE(_airbyte_extracted_at) >= DATE_SUB(CURRENT_DATE("Asia/Kolkata"), INTERVAL 10 DAY)
  )
  WHERE
    ROW_NUM = 1
) AS SOURCE
ON TARGET.segments_product_item_id = SOURCE.segments_product_item_id
WHEN MATCHED AND SOURCE._airbyte_extracted_at > TARGET._airbyte_extracted_at
THEN UPDATE SET
  TARGET._airbyte_extracted_at = SOURCE._airbyte_extracted_at,
  TARGET.ad_group_id = SOURCE.ad_group_id,
  TARGET.ad_group_name = SOURCE.ad_group_name,
  TARGET.ad_group_status = SOURCE.ad_group_status,
  TARGET.campaign_id = SOURCE.campaign_id,
  TARGET.campaign_name = SOURCE.campaign_name,
  TARGET.campaign_status = SOURCE.campaign_status,
  TARGET.customer_descriptive_name = SOURCE.customer_descriptive_name,
  TARGET.customer_id = SOURCE.customer_id,
  TARGET.metrics_all_conversions = SOURCE.metrics_all_conversions,
  TARGET.metrics_all_conversions_from_interactions_rate = SOURCE.metrics_all_conversions_from_interactions_rate,
  TARGET.metrics_all_conversions_value = SOURCE.metrics_all_conversions_value,
  TARGET.metrics_average_cpc = SOURCE.metrics_average_cpc,
  TARGET.metrics_clicks = SOURCE.metrics_clicks,
  TARGET.metrics_conversions = SOURCE.metrics_conversions,
  TARGET.metrics_conversions_from_interactions_rate = SOURCE.metrics_conversions_from_interactions_rate,
  TARGET.metrics_conversions_value = SOURCE.metrics_conversions_value,
  TARGET.metrics_cost_micros = SOURCE.metrics_cost_micros,
  TARGET.metrics_cost_per_all_conversions = SOURCE.metrics_cost_per_all_conversions,
  TARGET.metrics_cost_per_conversion = SOURCE.metrics_cost_per_conversion,
  TARGET.metrics_cross_device_conversions = SOURCE.metrics_cross_device_conversions,
  TARGET.metrics_ctr = SOURCE.metrics_ctr,
  TARGET.metrics_impressions = SOURCE.metrics_impressions,
  TARGET.metrics_value_per_all_conversions = SOURCE.metrics_value_per_all_conversions,
  TARGET.metrics_value_per_conversion = SOURCE.metrics_value_per_conversion,
  TARGET.segments_ad_network_type = SOURCE.segments_ad_network_type,
  TARGET.segments_click_type = SOURCE.segments_click_type,
  TARGET.segments_date = SOURCE.segments_date,
  TARGET.segments_day_of_week = SOURCE.segments_day_of_week,
  TARGET.segments_device = SOURCE.segments_device,
  TARGET.segments_month = SOURCE.segments_month,
  TARGET.segments_product_aggregator_id = SOURCE.segments_product_aggregator_id,
  TARGET.segments_product_brand = SOURCE.segments_product_brand,
  TARGET.segments_product_category_level1 = SOURCE.segments_product_category_level1,
  TARGET.segments_product_category_level2 = SOURCE.segments_product_category_level2,
  TARGET.segments_product_category_level3 = SOURCE.segments_product_category_level3,
  TARGET.segments_product_category_level4 = SOURCE.segments_product_category_level4,
  TARGET.segments_product_category_level5 = SOURCE.segments_product_category_level5,
  TARGET.segments_product_channel = SOURCE.segments_product_channel,
  TARGET.segments_product_channel_exclusivity = SOURCE.segments_product_channel_exclusivity,
  TARGET.segments_product_condition = SOURCE.segments_product_condition,
  TARGET.segments_product_country = SOURCE.segments_product_country,
  TARGET.segments_product_custom_attribute0 = SOURCE.segments_product_custom_attribute0,
  TARGET.segments_product_custom_attribute1 = SOURCE.segments_product_custom_attribute1,
  TARGET.segments_product_custom_attribute2 = SOURCE.segments_product_custom_attribute2,
  TARGET.segments_product_custom_attribute3 = SOURCE.segments_product_custom_attribute3,
  TARGET.segments_product_custom_attribute4 = SOURCE.segments_product_custom_attribute4,
  TARGET.segments_product_item_id = SOURCE.segments_product_item_id,
  TARGET.segments_product_language = SOURCE.segments_product_language,
  TARGET.segments_product_merchant_id = SOURCE.segments_product_merchant_id,
  TARGET.segments_product_store_id = SOURCE.segments_product_store_id,
  TARGET.segments_product_title = SOURCE.segments_product_title,
  TARGET.segments_product_type_l1 = SOURCE.segments_product_type_l1,
  TARGET.segments_product_type_l2 = SOURCE.segments_product_type_l2,
  TARGET.segments_product_type_l3 = SOURCE.segments_product_type_l3,
  TARGET.segments_product_type_l4 = SOURCE.segments_product_type_l4,
  TARGET.segments_product_type_l5 = SOURCE.segments_product_type_l5,
  TARGET.segments_quarter = SOURCE.segments_quarter,
  TARGET.segments_week = SOURCE.segments_week,
  TARGET.segments_year = SOURCE.segments_year
WHEN NOT MATCHED
THEN INSERT
(
  _airbyte_extracted_at,
  ad_group_id,
  ad_group_name,
  ad_group_status,
  campaign_id,
  campaign_name,
  campaign_status,
  customer_descriptive_name,
  customer_id,
  metrics_all_conversions,
  metrics_all_conversions_from_interactions_rate,
  metrics_all_conversions_value,
  metrics_average_cpc,
  metrics_clicks,
  metrics_conversions,
  metrics_conversions_from_interactions_rate,
  metrics_conversions_value,
  metrics_cost_micros,
  metrics_cost_per_all_conversions,
  metrics_cost_per_conversion,
  metrics_cross_device_conversions,
  metrics_ctr,
  metrics_impressions,
  metrics_value_per_all_conversions,
  metrics_value_per_conversion,
  segments_ad_network_type,
  segments_click_type,
  segments_date,
  segments_day_of_week,
  segments_device,
  segments_month,
  segments_product_aggregator_id,
  segments_product_brand,
  segments_product_category_level1,
  segments_product_category_level2,
  segments_product_category_level3,
  segments_product_category_level4,
  segments_product_category_level5,
  segments_product_channel,
  segments_product_channel_exclusivity,
  segments_product_condition,
  segments_product_country,
  segments_product_custom_attribute0,
  segments_product_custom_attribute1,
  segments_product_custom_attribute2,
  segments_product_custom_attribute3,
  segments_product_custom_attribute4,
  segments_product_item_id,
  segments_product_language,
  segments_product_merchant_id,
  segments_product_store_id,
  segments_product_title,
  segments_product_type_l1,
  segments_product_type_l2,
  segments_product_type_l3,
  segments_product_type_l4,
  segments_product_type_l5,
  segments_quarter,
  segments_week,
  segments_year
)
VALUES
(
  SOURCE._airbyte_extracted_at,
  SOURCE.ad_group_id,
  SOURCE.ad_group_name,
  SOURCE.ad_group_status,
  SOURCE.campaign_id,
  SOURCE.campaign_name,
  SOURCE.campaign_status,
  SOURCE.customer_descriptive_name,
  SOURCE.customer_id,
  SOURCE.metrics_all_conversions,
  SOURCE.metrics_all_conversions_from_interactions_rate,
  SOURCE.metrics_all_conversions_value,
  SOURCE.metrics_average_cpc,
  SOURCE.metrics_clicks,
  SOURCE.metrics_conversions,
  SOURCE.metrics_conversions_from_interactions_rate,
  SOURCE.metrics_conversions_value,
  SOURCE.metrics_cost_micros,
  SOURCE.metrics_cost_per_all_conversions,
  SOURCE.metrics_cost_per_conversion,
  SOURCE.metrics_cross_device_conversions,
  SOURCE.metrics_ctr,
  SOURCE.metrics_impressions,
  SOURCE.metrics_value_per_all_conversions,
  SOURCE.metrics_value_per_conversion,
  SOURCE.segments_ad_network_type,
  SOURCE.segments_click_type,
  SOURCE.segments_date,
  SOURCE.segments_day_of_week,
  SOURCE.segments_device,
  SOURCE.segments_month,
  SOURCE.segments_product_aggregator_id,
  SOURCE.segments_product_brand,
  SOURCE.segments_product_category_level1,
  SOURCE.segments_product_category_level2,
  SOURCE.segments_product_category_level3,
  SOURCE.segments_product_category_level4,
  SOURCE.segments_product_category_level5,
  SOURCE.segments_product_channel,
  SOURCE.segments_product_channel_exclusivity,
  SOURCE.segments_product_condition,
  SOURCE.segments_product_country,
  SOURCE.segments_product_custom_attribute0,
  SOURCE.segments_product_custom_attribute1,
  SOURCE.segments_product_custom_attribute2,
  SOURCE.segments_product_custom_attribute3,
  SOURCE.segments_product_custom_attribute4,
  SOURCE.segments_product_item_id,
  SOURCE.segments_product_language,
  SOURCE.segments_product_merchant_id,
  SOURCE.segments_product_store_id,
  SOURCE.segments_product_title,
  SOURCE.segments_product_type_l1,
  SOURCE.segments_product_type_l2,
  SOURCE.segments_product_type_l3,
  SOURCE.segments_product_type_l4,
  SOURCE.segments_product_type_l5,
  SOURCE.segments_quarter,
  SOURCE.segments_week,
  SOURCE.segments_year
)