name: Sync DAGs to Cloud Composer

on:
  push:
    branches:
      - main 
jobs:
  sync-dags:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v3

      
      - name: List DAGs folder
        run: ls -al ./dags/

      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.5.0  # Use the latest version
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}  # Reference the secret here

      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: shopify-pubsub-project

      
      - name: Sync DAGs to Composer
        run: |
          gsutil -m rsync -r ./dags/ gs://asia-south2-composer-pilgri-b5eb683d-bucket/dags/
