name: Sync DAGs to Cloud Composer

on:
  push:
    branches:
      - main  # Trigger the action on every push to the main branch

jobs:
  sync-dags:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          project_id: YOUR_GOOGLE_CLOUD_PROJECT_ID

      # Step 3: Sync DAGs to Composer GCS Bucket
      - name: Sync DAGs to Composer
        run: |
          gsutil -m rsync -r ./dags gs://YOUR_COMPOSER_BUCKET/dags/
