merge into `shopify-pubsub-project.Data_Warehouse_Facebook_Ads_Staging.ads_insights_action_carousel_card_non_json` as target
using
(
SELECT
  _airbyte_extracted_at,
  cpc,
  cpm,
  cpp,
  ctr,
  ad_id,
  reach,
  spend,
  clicks,
  ad_name,
  adset_id,
  date_stop,
  frequency,
  objective,
  account_id,
  adset_name,
  date_start,
  unique_ctr,
  buying_type,
  campaign_id,
  impressions,
  account_name,
  created_time,
  social_spend,
  updated_time,
  campaign_name,
  unique_clicks,
  full_view_reach,
  quality_ranking,
  account_currency,
  optimization_goal,
  canvas_avg_view_time,
  cost_per_unique_click,
  full_view_impressions,
  inline_link_click_ctr,
  estimated_ad_recallers,
  inline_post_engagement,
  canvas_avg_view_percent,
  conversion_rate_ranking,
  engagement_rate_ranking,
  unique_inline_link_clicks,
  cost_per_inline_link_click,
  unique_inline_link_click_ctr,
  cost_per_inline_post_engagement,
  cost_per_unique_inline_link_click,
  instant_experience_clicks_to_open,
  instant_experience_clicks_to_start,
  qualifying_question_qualify_answer_rate,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(video_play_curve_actions, '$[0]'), '$.action_type') AS video_play_curve_actions_type,
  JSON_EXTRACT(JSON_EXTRACT(video_play_curve_actions, '$[0]'), '$.value') AS video_play_curve_actions_value_array,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(video_p95_watched_actions, '$[0]'), '$.action_type') AS video_p95_watched_actions_type,
  JSON_EXTRACT(JSON_EXTRACT(video_p95_watched_actions, '$[0]'), '$.value') AS video_p95_watched_actions_value,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(video_15_sec_watched_actions, '$[0]'), '$.action_type') AS video_15_sec_watched_actions_type,
  JSON_EXTRACT(JSON_EXTRACT(video_15_sec_watched_actions, '$[0]'), '$.value') AS video_15_sec_watched_actions_value,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(video_30_sec_watched_actions, '$[0]'), '$.action_type') AS video_30_sec_watched_actions_type,
  JSON_EXTRACT(JSON_EXTRACT(video_30_sec_watched_actions, '$[0]'), '$.value') AS video_30_sec_watched_actions_value,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(video_avg_time_watched_actions, '$[0]'), '$.action_carousel_card_id') AS video_avg_time_watched_actions_carousel_card_id,
  JSON_EXTRACT(JSON_EXTRACT(video_avg_time_watched_actions, '$[0]'), '$.action_carousel_card_name') AS video_avg_time_watched_actions_carousel_card_name,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(video_avg_time_watched_actions, '$[0]'), '$.action_type') AS video_avg_time_watched_actions_type,
  JSON_EXTRACT(JSON_EXTRACT(video_avg_time_watched_actions, '$[0]'), '$.value') AS video_avg_time_watched_actions_value,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(video_continuous_2_sec_watched_actions, '$[0]'), '$.action_type') AS video_2sec_actions_type,
  JSON_EXTRACT(JSON_EXTRACT(video_continuous_2_sec_watched_actions, '$[0]'), '$.value') AS video_2sec_value,
FROM
(
select
*,
row_number() over(partition by ad_id,date_start order by _airbyte_extracted_at desc) as rn
from shopify-pubsub-project.pilgrim_bi_airbyte_facebook.ads_insights_action_carousel_card
)
where rn = 1 and date(_airbyte_extracted_at) >= date_sub(current_date("Asia/Kolkata"), INTERVAL 10 day)
) as source
on target.ad_id = source.ad_id
and target.date_start = source.date_start
when matched and target._airbyte_extracted_at < source._airbyte_extracted_at
then update set
target._airbyte_extracted_at = source._airbyte_extracted_at,
target.cpc = source.cpc,
target.cpm = source.cpm,
target.cpp = source.cpp,
target.ctr = source.ctr,
target.ad_id = source.ad_id,
target.reach = source.reach,
target.spend = source.spend,
target.clicks = source.clicks,
target.ad_name = source.ad_name,
target.adset_id = source.adset_id,
target.date_stop = source.date_stop,
target.frequency = source.frequency,
target.objective = source.objective,
target.account_id = source.account_id,
target.adset_name = source.adset_name,
target.date_start = source.date_start,
target.unique_ctr = source.unique_ctr,
target.buying_type = source.buying_type,
target.campaign_id = source.campaign_id,
target.impressions = source.impressions,
target.account_name = source.account_name,
target.created_time = source.created_time,
target.social_spend = source.social_spend,
target.updated_time = source.updated_time,
target.campaign_name = source.campaign_name,
target.unique_clicks = source.unique_clicks,
target.full_view_reach = source.full_view_reach,
target.quality_ranking = source.quality_ranking,
target.account_currency = source.account_currency,
target.optimization_goal = source.optimization_goal,
target.canvas_avg_view_time = source.canvas_avg_view_time,
target.cost_per_unique_click = source.cost_per_unique_click,
target.full_view_impressions = source.full_view_impressions,
target.inline_link_click_ctr = source.inline_link_click_ctr,
target.estimated_ad_recallers = source.estimated_ad_recallers,
target.inline_post_engagement = source.inline_post_engagement,
target.canvas_avg_view_percent = source.canvas_avg_view_percent,
target.conversion_rate_ranking = source.conversion_rate_ranking,
target.engagement_rate_ranking = source.engagement_rate_ranking,
target.unique_inline_link_clicks = source.unique_inline_link_clicks,
target.cost_per_inline_link_click = source.cost_per_inline_link_click,
target.unique_inline_link_click_ctr = source.unique_inline_link_click_ctr,
target.cost_per_inline_post_engagement = source.cost_per_inline_post_engagement,
target.cost_per_unique_inline_link_click = source.cost_per_unique_inline_link_click,
target.instant_experience_clicks_to_open = source.instant_experience_clicks_to_open,
target.instant_experience_clicks_to_start = source.instant_experience_clicks_to_start,
target.qualifying_question_qualify_answer_rate = source.qualifying_question_qualify_answer_rate,
target.video_play_curve_actions_type = source.video_play_curve_actions_type,
target.video_play_curve_actions_value_array = source.video_play_curve_actions_value_array,
target.video_p95_watched_actions_type = source.video_p95_watched_actions_type,
target.video_p95_watched_actions_value = source.video_p95_watched_actions_value,
target.video_15_sec_watched_actions_type = source.video_15_sec_watched_actions_type,
target.video_15_sec_watched_actions_value = source.video_15_sec_watched_actions_value,
target.video_30_sec_watched_actions_type = source.video_30_sec_watched_actions_type,
target.video_30_sec_watched_actions_value = source.video_30_sec_watched_actions_value,
target.video_avg_time_watched_actions_carousel_card_id = source.video_avg_time_watched_actions_carousel_card_id,
target.video_avg_time_watched_actions_carousel_card_name = source.video_avg_time_watched_actions_carousel_card_name,
target.video_avg_time_watched_actions_type = source.video_avg_time_watched_actions_type,
target.video_avg_time_watched_actions_value = source.video_avg_time_watched_actions_value,
target.video_2sec_actions_type = source.video_2sec_actions_type,
target.video_2sec_value = source.video_2sec_value
when not matched
then insert
(
_airbyte_extracted_at,
cpc,
cpm,
cpp,
ctr,
ad_id,
reach,
spend,
clicks,
ad_name,
adset_id,
date_stop,
frequency,
objective,
account_id,
adset_name,
date_start,
unique_ctr,
buying_type,
campaign_id,
impressions,
account_name,
created_time,
social_spend,
updated_time,
campaign_name,
unique_clicks,
full_view_reach,
quality_ranking,
account_currency,
optimization_goal,
canvas_avg_view_time,
cost_per_unique_click,
full_view_impressions,
inline_link_click_ctr,
estimated_ad_recallers,
inline_post_engagement,
canvas_avg_view_percent,
conversion_rate_ranking,
engagement_rate_ranking,
unique_inline_link_clicks,
cost_per_inline_link_click,
unique_inline_link_click_ctr,
cost_per_inline_post_engagement,
cost_per_unique_inline_link_click,
instant_experience_clicks_to_open,
instant_experience_clicks_to_start,
qualifying_question_qualify_answer_rate,
video_play_curve_actions_type,
video_play_curve_actions_value_array,
video_p95_watched_actions_type,
video_p95_watched_actions_value,
video_15_sec_watched_actions_type,
video_15_sec_watched_actions_value,
video_30_sec_watched_actions_type,
video_30_sec_watched_actions_value,
video_avg_time_watched_actions_carousel_card_id,
video_avg_time_watched_actions_carousel_card_name,
video_avg_time_watched_actions_type,
video_avg_time_watched_actions_value,
video_2sec_actions_type,
video_2sec_value
)
values
(
source._airbyte_extracted_at,
source.cpc,
source.cpm,
source.cpp,
source.ctr,
source.ad_id,
source.reach,
source.spend,
source.clicks,
source.ad_name,
source.adset_id,
source.date_stop,
source.frequency,
source.objective,
source.account_id,
source.adset_name,
source.date_start,
source.unique_ctr,
source.buying_type,
source.campaign_id,
source.impressions,
source.account_name,
source.created_time,
source.social_spend,
source.updated_time,
source.campaign_name,
source.unique_clicks,
source.full_view_reach,
source.quality_ranking,
source.account_currency,
source.optimization_goal,
source.canvas_avg_view_time,
source.cost_per_unique_click,
source.full_view_impressions,
source.inline_link_click_ctr,
source.estimated_ad_recallers,
source.inline_post_engagement,
source.canvas_avg_view_percent,
source.conversion_rate_ranking,
source.engagement_rate_ranking,
source.unique_inline_link_clicks,
source.cost_per_inline_link_click,
source.unique_inline_link_click_ctr,
source.cost_per_inline_post_engagement,
source.cost_per_unique_inline_link_click,
source.instant_experience_clicks_to_open,
source.instant_experience_clicks_to_start,
source.qualifying_question_qualify_answer_rate,
source.video_play_curve_actions_type,
source.video_play_curve_actions_value_array,
source.video_p95_watched_actions_type,
source.video_p95_watched_actions_value,
source.video_15_sec_watched_actions_type,
source.video_15_sec_watched_actions_value,
source.video_30_sec_watched_actions_type,
source.video_30_sec_watched_actions_value,
source.video_avg_time_watched_actions_carousel_card_id,
source.video_avg_time_watched_actions_carousel_card_name,
source.video_avg_time_watched_actions_type,
source.video_avg_time_watched_actions_value,
source.video_2sec_actions_type,
source.video_2sec_value
)