MERGE INTO `shopify-pubsub-project.Data_Warehouse_Facebook_Ads_Staging.ads_insights_action_carousel_card_non_json` AS TARGET
USING
(
  SELECT
    _airbyte_extracted_at,
    cpc,
    cpm,
    cpp,
    ctr,
    ad_id,
    reach,
    spend,
    clicks,
    ad_name,
    adset_id,
    date_stop,
    frequency,
    objective,
    account_id,
    adset_name,
    date_start,
    unique_ctr,
    buying_type,
    campaign_id,
    impressions,
    account_name,
    created_time,
    social_spend,
    updated_time,
    campaign_name,
    unique_clicks,
    full_view_reach,
    quality_ranking,
    account_currency,
    optimization_goal,
    canvas_avg_view_time,
    cost_per_unique_click,
    full_view_impressions,
    inline_link_click_ctr,
    estimated_ad_recallers,
    inline_post_engagement,
    canvas_avg_view_percent,
    conversion_rate_ranking,
    engagement_rate_ranking,
    unique_inline_link_clicks,
    cost_per_inline_link_click,
    unique_inline_link_click_ctr,
    cost_per_inline_post_engagement,
    cost_per_unique_inline_link_click,
    instant_experience_clicks_to_open,
    instant_experience_clicks_to_start,
    qualifying_question_qualify_answer_rate,


 
  -- video_play_curve_actions,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(video_play_curve_actions, '$[0]'), '$.action_type') AS video_play_curve_actions_type,
  JSON_EXTRACT(JSON_EXTRACT(video_play_curve_actions, '$[0]'), '$.value') AS video_play_curve_actions_value_array,


  -- video_p95_watched_actions,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(video_p95_watched_actions, '$[0]'), '$.action_type') AS video_p95_watched_actions_type,
  JSON_EXTRACT(JSON_EXTRACT(video_p95_watched_actions, '$[0]'), '$.value') AS video_p95_watched_actions_value,


  -- video_15_sec_watched_actions,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(video_15_sec_watched_actions, '$[0]'), '$.action_type') AS video_15_sec_watched_actions_type,
  JSON_EXTRACT(JSON_EXTRACT(video_15_sec_watched_actions, '$[0]'), '$.value') AS video_15_sec_watched_actions_value,


  -- video_30_sec_watched_actions,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(video_30_sec_watched_actions, '$[0]'), '$.action_type') AS video_30_sec_watched_actions_type,
  JSON_EXTRACT(JSON_EXTRACT(video_30_sec_watched_actions, '$[0]'), '$.value') AS video_30_sec_watched_actions_value,


  -- video_avg_time_watched_actions,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(video_avg_time_watched_actions, '$[0]'), '$.action_carousel_card_id') AS video_avg_time_watched_actions_carousel_card_id,
  JSON_EXTRACT(JSON_EXTRACT(video_avg_time_watched_actions, '$[0]'), '$.action_carousel_card_name') AS video_avg_time_watched_actions_carousel_card_name,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(video_avg_time_watched_actions, '$[0]'), '$.action_type') AS video_avg_time_watched_actions_type,
  JSON_EXTRACT(JSON_EXTRACT(video_avg_time_watched_actions, '$[0]'), '$.value') AS video_avg_time_watched_actions_value,


  -- video_continuous_2_sec_watched_actions,
  JSON_EXTRACT_SCALAR(JSON_EXTRACT(video_continuous_2_sec_watched_actions, '$[0]'), '$.action_type') AS video_2sec_actions_type,
  JSON_EXTRACT(JSON_EXTRACT(video_continuous_2_sec_watched_actions, '$[0]'), '$.value') AS video_2sec_value,
    FROM
    (
      SELECT
        *,
        ROW_NUMBER() OVER(PARTITION BY adset_id ORDER BY _airbyte_extracted_at) AS row_num
      FROM
        shopify-pubsub-project.pilgrim_bi_airbyte_facebook.ads_insights_action_carousel_card
      WHERE
        DATE(_airbyte_extracted_at) > DATE_SUB(CURRENT_DATE("Asia/Kolkata"), INTERVAL 10 DAY)
    )
    WHERE row_nuM = 1  
) AS SOURCE


ON TARGET.ad_id = SOURCE.ad_id
WHEN MATCHED AND TARGET._airbyte_extracted_at < SOURCE._airbyte_extracted_at
THEN UPDATE SET
  TARGET._airbyte_extracted_at = SOURCE._airbyte_extracted_at,
  TARGET.cpc = SOURCE.cpc,
  TARGET.cpm = SOURCE.cpm,
  TARGET.cpp = SOURCE.cpp,
  TARGET.ctr = SOURCE.ctr,
  TARGET.ad_id = SOURCE.ad_id,
  TARGET.reach = SOURCE.reach,
  TARGET.spend = SOURCE.spend,
  TARGET.clicks = SOURCE.clicks,
  TARGET.ad_name = SOURCE.ad_name,
  TARGET.adset_id = SOURCE.adset_id,
  TARGET.date_stop = SOURCE.date_stop,
  TARGET.frequency = SOURCE.frequency,
  TARGET.objective = SOURCE.objective,
  TARGET.account_id = SOURCE.account_id,
  TARGET.adset_name = SOURCE.adset_name,
  TARGET.date_start = SOURCE.date_start,
  TARGET.unique_ctr = SOURCE.unique_ctr,
  TARGET.buying_type = SOURCE.buying_type,
  TARGET.campaign_id = SOURCE.campaign_id,
  TARGET.impressions = SOURCE.impressions,
  TARGET.account_name = SOURCE.account_name,
  TARGET.created_time = SOURCE.created_time,
  TARGET.social_spend = SOURCE.social_spend,
  TARGET.updated_time = SOURCE.updated_time,
  TARGET.campaign_name = SOURCE.campaign_name,
  TARGET.unique_clicks = SOURCE.unique_clicks,
  TARGET.full_view_reach = SOURCE.full_view_reach,
  TARGET.quality_ranking = SOURCE.quality_ranking,
  TARGET.account_currency = SOURCE.account_currency,
  TARGET.optimization_goal = SOURCE.optimization_goal,
  TARGET.canvas_avg_view_time = SOURCE.canvas_avg_view_time,
  TARGET.cost_per_unique_click = SOURCE.cost_per_unique_click,
  TARGET.full_view_impressions = SOURCE.full_view_impressions,
  TARGET.inline_link_click_ctr = SOURCE.inline_link_click_ctr,
  TARGET.estimated_ad_recallers = SOURCE.estimated_ad_recallers,
  TARGET.inline_post_engagement = SOURCE.inline_post_engagement,
  TARGET.canvas_avg_view_percent = SOURCE.canvas_avg_view_percent,
  TARGET.conversion_rate_ranking = SOURCE.conversion_rate_ranking,
  TARGET.engagement_rate_ranking = SOURCE.engagement_rate_ranking,
  TARGET.unique_inline_link_clicks = SOURCE.unique_inline_link_clicks,
  TARGET.cost_per_inline_link_click = SOURCE.cost_per_inline_link_click,
  TARGET.unique_inline_link_click_ctr = SOURCE.unique_inline_link_click_ctr,
  TARGET.cost_per_inline_post_engagement = SOURCE.cost_per_inline_post_engagement,
  TARGET.cost_per_unique_inline_link_click = SOURCE.cost_per_unique_inline_link_click,
  TARGET.instant_experience_clicks_to_open = SOURCE.instant_experience_clicks_to_open,
  TARGET.instant_experience_clicks_to_start = SOURCE.instant_experience_clicks_to_start,
  TARGET.qualifying_question_qualify_answer_rate = SOURCE.qualifying_question_qualify_answer_rate
WHEN NOT MATCHED
THEN INSERT
(
  _airbyte_extracted_at,
  cpc,
  cpm,
  cpp,
  ctr,
  ad_id,
  reach,
  spend,
  clicks,
  ad_name,
  adset_id,
  date_stop,
  frequency,
  objective,
  account_id,
  adset_name,
  date_start,
  unique_ctr,
  buying_type,
  campaign_id,
  impressions,
  account_name,
  created_time,
  social_spend,
  updated_time,
  campaign_name,
  unique_clicks,
  full_view_reach,
  quality_ranking,
  account_currency,
  optimization_goal,
  canvas_avg_view_time,
  cost_per_unique_click,
  full_view_impressions,
  inline_link_click_ctr,
  estimated_ad_recallers,
  inline_post_engagement,
  canvas_avg_view_percent,
  conversion_rate_ranking,
  engagement_rate_ranking,
  unique_inline_link_clicks,
  cost_per_inline_link_click,
  unique_inline_link_click_ctr,
  cost_per_inline_post_engagement,
  cost_per_unique_inline_link_click,
  instant_experience_clicks_to_open,
  instant_experience_clicks_to_start,
  qualifying_question_qualify_answer_rate
)
VALUES
(
  SOURCE._airbyte_extracted_at,
  SOURCE.cpc,
  SOURCE.cpm,
  SOURCE.cpp,
  SOURCE.ctr,
  SOURCE.ad_id,
  SOURCE.reach,
  SOURCE.spend,
  SOURCE.clicks,
  SOURCE.ad_name,
  SOURCE.adset_id,
  SOURCE.date_stop,
  SOURCE.frequency,
  SOURCE.objective,
  SOURCE.account_id,
  SOURCE.adset_name,
  SOURCE.date_start,
  SOURCE.unique_ctr,
  SOURCE.buying_type,
  SOURCE.campaign_id,
  SOURCE.impressions,
  SOURCE.account_name,
  SOURCE.created_time,
  SOURCE.social_spend,
  SOURCE.updated_time,
  SOURCE.campaign_name,
  SOURCE.unique_clicks,
  SOURCE.full_view_reach,
  SOURCE.quality_ranking,
  SOURCE.account_currency,
  SOURCE.optimization_goal,
  SOURCE.canvas_avg_view_time,
  SOURCE.cost_per_unique_click,
  SOURCE.full_view_impressions,
  SOURCE.inline_link_click_ctr,
  SOURCE.estimated_ad_recallers,
  SOURCE.inline_post_engagement,
  SOURCE.canvas_avg_view_percent,
  SOURCE.conversion_rate_ranking,
  SOURCE.engagement_rate_ranking,
  SOURCE.unique_inline_link_clicks,
  SOURCE.cost_per_inline_link_click,
  SOURCE.unique_inline_link_click_ctr,
  SOURCE.cost_per_inline_post_engagement,
  SOURCE.cost_per_unique_inline_link_click,
  SOURCE.instant_experience_clicks_to_open,
  SOURCE.instant_experience_clicks_to_start,
  SOURCE.qualifying_question_qualify_answer_rate
)
