merge into `shopify-pubsub-project.Data_Warehouse_Easyecom_Staging.pending_return_orders` as target
using
(
select
*
from
(
select distinct
*,
row_number() over(partition by invoice_id order by ee_extracted_at desc) as rn 
from shopify-pubsub-project.easycom.pending_return_orders
)
where rn = 1 and order_date >= DATE_SUB(CURRENT_DATE("Asia/Kolkata"), INTERVAL 10 DAY)
) as source
on target.invoice_id = source.invoice_id
when matched and target.ee_extracted_at < source.ee_extracted_at
then update set
target.invoice_id = source.invoice_id,
target.order_id = source.order_id,
target.reference_code = source.reference_code,
target.company_name = source.company_name,
target.ware_house_id = source.ware_house_id,
target.seller_gst = source.seller_gst,
target.forward_shipment_pickup_address = source.forward_shipment_pickup_address,
target.forward_shipment_pickup_city = source.forward_shipment_pickup_city,
target.forward_shipment_pickup_state = source.forward_shipment_pickup_state,
target.forward_shipment_pickup_pin_code = source.forward_shipment_pickup_pin_code,
target.forward_shipment_pickup_country = source.forward_shipment_pickup_country,
target.order_type = source.order_type,
target.order_type_key = source.order_type_key,
target.replacement_order = source.replacement_order,
target.marketplace = source.marketplace,
target.marketplace_id = source.marketplace_id,
target.salesman_user_id = source.salesman_user_id,
target.order_date = source.order_date,
target.invoice_date = source.invoice_date,
target.import_date = source.import_date,
target.last_update_date = source.last_update_date,
target.manifest_date = source.manifest_date,
target.return_date = source.return_date,
target.manifest_no = source.manifest_no,
target.invoice_number = source.invoice_number,
target.marketplace_credit_note_num = source.marketplace_credit_note_num,
target.marketplace_invoice_num = source.marketplace_invoice_num,
target.batch_id = source.batch_id,
target.batch_created_at = source.batch_created_at,
target.payment_mode = source.payment_mode,
target.payment_mode_id = source.payment_mode_id,
target.buyer_gst = source.buyer_gst,
target.forward_shipment_customer_name = source.forward_shipment_customer_name,
target.forward_shipment_customer_contact_num = source.forward_shipment_customer_contact_num,
target.forward_shipment_customer_address_line_1 = source.forward_shipment_customer_address_line_1,
target.forward_shipment_customer_address_line_2 = source.forward_shipment_customer_address_line_2,
target.forward_shipment_customer_city = source.forward_shipment_customer_city,
target.forward_shipment_customer_pin_code = source.forward_shipment_customer_pin_code,
target.forward_shipment_customer_state = source.forward_shipment_customer_state,
target.forward_shipment_customer_country = source.forward_shipment_customer_country,
target.forward_shipment_customer_email = source.forward_shipment_customer_email,
target.forward_shipment_billing_name = source.forward_shipment_billing_name,
target.forward_shipment_billing_address_1 = source.forward_shipment_billing_address_1,
target.forward_shipment_billing_address_2 = source.forward_shipment_billing_address_2,
target.forward_shipment_billing_city = source.forward_shipment_billing_city,
target.forward_shipment_billing_state = source.forward_shipment_billing_state,
target.forward_shipment_billing_pin_code = source.forward_shipment_billing_pin_code,
target.forward_shipment_billing_country = source.forward_shipment_billing_country,
target.forward_shipment_billing_mobile = source.forward_shipment_billing_mobile,
target.order_quantity = source.order_quantity,
target.total_invoice_amount = source.total_invoice_amount,
target.total_invoice_tax = source.total_invoice_tax,
target.invoice_collectable_amount = source.invoice_collectable_amount,
target.items = source.items,
target.ee_extracted_at = source.ee_extracted_at
when not matched
then insert
(
invoice_id,
order_id,
reference_code,
company_name,
ware_house_id,
seller_gst,
forward_shipment_pickup_address,
forward_shipment_pickup_city,
forward_shipment_pickup_state,
forward_shipment_pickup_pin_code,
forward_shipment_pickup_country,
order_type,
order_type_key,
replacement_order,
marketplace,
marketplace_id,
salesman_user_id,
order_date,
invoice_date,
import_date,
last_update_date,
manifest_date,
return_date,
manifest_no,
invoice_number,
marketplace_credit_note_num,
marketplace_invoice_num,
batch_id,
batch_created_at,
payment_mode,
payment_mode_id,
buyer_gst,
forward_shipment_customer_name,
forward_shipment_customer_contact_num,
forward_shipment_customer_address_line_1,
forward_shipment_customer_address_line_2,
forward_shipment_customer_city,
forward_shipment_customer_pin_code,
forward_shipment_customer_state,
forward_shipment_customer_country,
forward_shipment_customer_email,
forward_shipment_billing_name,
forward_shipment_billing_address_1,
forward_shipment_billing_address_2,
forward_shipment_billing_city,
forward_shipment_billing_state,
forward_shipment_billing_pin_code,
forward_shipment_billing_country,
forward_shipment_billing_mobile,
order_quantity,
total_invoice_amount,
total_invoice_tax,
invoice_collectable_amount,
items,
ee_extracted_at
)
values
(
source.invoice_id,
source.order_id,
source.reference_code,
source.company_name,
source.ware_house_id,
source.seller_gst,
source.forward_shipment_pickup_address,
source.forward_shipment_pickup_city,
source.forward_shipment_pickup_state,
source.forward_shipment_pickup_pin_code,
source.forward_shipment_pickup_country,
source.order_type,
source.order_type_key,
source.replacement_order,
source.marketplace,
source.marketplace_id,
source.salesman_user_id,
source.order_date,
source.invoice_date,
source.import_date,
source.last_update_date,
source.manifest_date,
source.return_date,
source.manifest_no,
source.invoice_number,
source.marketplace_credit_note_num,
source.marketplace_invoice_num,
source.batch_id,
source.batch_created_at,
source.payment_mode,
source.payment_mode_id,
source.buyer_gst,
source.forward_shipment_customer_name,
source.forward_shipment_customer_contact_num,
source.forward_shipment_customer_address_line_1,
source.forward_shipment_customer_address_line_2,
source.forward_shipment_customer_city,
source.forward_shipment_customer_pin_code,
source.forward_shipment_customer_state,
source.forward_shipment_customer_country,
source.forward_shipment_customer_email,
source.forward_shipment_billing_name,
source.forward_shipment_billing_address_1,
source.forward_shipment_billing_address_2,
source.forward_shipment_billing_city,
source.forward_shipment_billing_state,
source.forward_shipment_billing_pin_code,
source.forward_shipment_billing_country,
source.forward_shipment_billing_mobile,
source.order_quantity,
source.total_invoice_amount,
source.total_invoice_tax,
source.invoice_collectable_amount,
source.items,
source.ee_extracted_at
);


